### ISSUE TITLE
global-prefix raises wrong type argument with evil

### ISSUE THREAD

**Issue by EdwardJRoss** [noctuid/general.el#100]
When using general-define-key with :global-prefix I get an error

Example:
``` elisp
(require 'general)
(require 'evil)

(general-define-key
 :global-prefix "C-<SPC>"
 :states 'emacs
  "f" 'find-file)
```

Expected output: Evil Emacs state binding of "C-SPC f" runs find-file

Actual output: Error
```
Debugger entered--Lisp error: (wrong-type-argument arrayp emacs)
  lookup-key((keymap (26 . evil-exit-emacs-state)) emacs)
```
[Full stack trace](https://pastebin.com/bxCccsGz)

Running git bisect tracks down the issue to 91761aad79665a7c8b5ea6838eedf584e846ddbb.

Running latest git versions of general.el (cc9983470cc5152c9de584e971ffc8bd38413616) and evil (2992858748e6fe8ae706d182b86b684e7b9be8b9).

**Comment by noctuid** [comment]
Thanks for the bug report; it should be fixed now.
