### ISSUE TITLE
Evil motion state error: non-prefix key

### ISSUE THREAD

**Issue by EdwardJRoss** [noctuid/general.el#101]
Hi, thanks for your great package and quickly resolving #100 .

I get an error when using a prefix with motion state and general-define-key

Example:
``` elisp
(require 'general)
(require 'evil)

(general-define-key
 :prefix ","
 :states 'motion
  "f" 'find-file)
```
Result: (error "Key sequence , f starts with non-prefix key ,")

Bisect traces this issue to 66e5c943c46dd91000e03d775262a28447afd5c9

**Comment by noctuid** [comment]
This is the expected behavior. Please see #97 and let me know if you have any further questions.
