### ISSUE TITLE
 Key sequence starts with non-prefix key 

### ISSUE THREAD

**Issue by PinkFLoyd92** [noctuid/general.el#103]
I just upgraded general, and now all my keybindings are not working. I don't see anything in the log if I debug emacs.

> This was the version I had.

![image](https://user-images.githubusercontent.com/8844096/36116836-a6074ffe-1005-11e8-807b-e0622d963a17.png)

![image](https://user-images.githubusercontent.com/8844096/36116789-739c4d9e-1005-11e8-8cd3-abb66313e54d.png)

**Comment by noctuid** [comment]
Please see #97 (and #101) and let me know if any further explanation is needed. I will add an FAQ entry about this issue soon.
