### ISSUE TITLE
:predicate doesn't seem to be working

### ISSUE THREAD

**Issue by rgrinberg** [noctuid/general.el#104]
I'm trying to create a binding like this:

```
(defun rg/shell-p ()
  (or
   (string= "*Async Shell Command*" (buffer-name))
   (string= "*Shell Command Output*" (buffer-name))))

  (general-define-key
   :states '(normal evilified motion)
   :keymaps 'local
   :predicate '(rg/shell-p)
   "q" #'quit-window)
```

But `q` keeps being macro button. Anything, I'm doing wrong? The predicate seems to be working as I tried it evaluating in a buffer.

**Comment by noctuid** [comment]
This works as expected for me. What hook are you using to run the `general-define-key`? It may be more appropriate to bind in `shell-mode-map` instead.

**Comment by rgrinberg** [comment]
The problem is that those buffers open in fundamental mode. I'm not using a
hook to run this command. Do I need to?

**Comment by noctuid** [comment]
> I'm not using a hook to run this command. Do I need to?

Yes, that `general-define-key` makes keybindings for the current buffer only, so you'd need to run it for every new buffer. It would probably be preferable to bind in a globally active keymap though (e.g. you could reuse `:keymaps 'override` for this purpose).

**Comment by rgrinberg** [comment]
I see. Ok that make sense. It might be worth clarifying a little in the
docs.

Thanks again for making general and helping me out.
