### ISSUE TITLE
Binding ESC

### ISSUE THREAD

**Issue by Grimscythe1983** [noctuid/general.el#105]
I use escape for escaping "things", such as Evil's insert mode, emacs to evil switch etc.

In my previous setup I also had `ESC` in company-mode-map to do `company-abort`.
I am getting a non-prefix error. So the question is: how do I correctly unbind `ESC` to make it usable by `general`?

My current attempt:

```elisp
(general-define-key :keymaps 'company-active-map
                    "M-j" 'company-select-next
                    "M-k" 'company-select-previous
                    "TAB" 'expand-snippet-or-complete-selection
                    "ESC" 'company-abort)
```

EDIT:
Amazing package!!! The best thus far in terms of keybinding management!!!

**Comment by noctuid** [comment]
`ESC` is bound to a keymap by default in `company-active-map`, so you have to unbind it first before binding it directly to a command. See [this FAQ entry](https://github.com/noctuid/general.el#how-do-i-prevent-key-sequence-starts-with-non-prefix-key-errors) for more information.

**Comment by Grimscythe1983** [comment]
So something like this, does not work:
```elisp
(general-define-key :keymaps 'company-active-map
                    "ESC" 'nil
                    "M-j" 'company-select-next
                    "M-k" 'company-select-previous
                    "TAB" 'expand-snippet-or-complete-selection
                    "C-g" 'company-abort
                    "ESC" 'company-abort)
```

Tried restarting emacs to make sure that the maps get re-evaluated. With the above code non of the keys work.

**Comment by Grimscythe1983** [comment]
That's sort of wierd because I am not in terminal mode.

But sure! I'll try it later on today.

**Comment by Grimscythe1983** [comment]
Works like a charm, thank you @noctuid , General rocks!

**Comment by noctuid** [comment]
I could have phrased that better. `ESC` is always handled like that even when emacs is not run in a terminal.

**Comment by Grimscythe1983** [comment]
No worries, got there in the end. This conversation might help other people as well, so hopefully no time has been wasted.
