### ISSUE TITLE
Leader key as top priority

### ISSUE THREAD

**Issue by Grimscythe1983** [noctuid/general.el#107]
I personally use Space as my leader key. I cannot figure out a way to make Space the number one priority in all maps. 

I recently started using `evil-collections` and some integrations use Space. Unbinding Space seems to be rather difficult for whatever reason :/ Easier would be just making Space the top priority, I think.

Sorry for my dumbness I just cannot figure it out, out of the the documentation.

[This is my current setup for the leader key](https://github.com/Grimscythe1983/.emacs.d/blob/master/setup-files/key-leaders-setup.el)

**Comment by dieggsy** [comment]
You can use an [override keymap](https://github.com/noctuid/general.el#override-keymaps-and-buffer-local-keybindings).

**Comment by Grimscythe1983** [comment]
Evil-collections have a little snippet on how to do it in their FAQ
