### ISSUE TITLE
Multiple KBDs for same function

### ISSUE THREAD

**Issue by wpcarro** [noctuid/general.el#109]
Forgive me if this is documented and I missed it somehow. I tried to thoroughly read through the documentation. There is a lot to digest, however, so I may have missed something.

Does General have an answer for a use case like this:

```elisp
(general-def
  "C-s" 'swiper
  "C-r" 'swiper)
```

...where both `C-s` and `C-r` are being mapped to the same thing.

After refactoring my `init.el` to accommodate General, I have a lot of code that looks like this:

```elisp
(use-package evil
  :general
  (nmap
    "s" nil
    "M-." nil)
  (imap
    "C-d" nil
    "C-a" nil
    "C-e" nil
    "C-n" nil
    "C-p" nil
    "C-k" nil)
```

Where I am unbinding multiple KBDs. It would be nice if that could be written as this:

```elisp
(use-package evil
  :general
  (nmap
    ("s" "M-.") nil)
  (imap
    ("C-d" "C-a" "C-e" "C-n" "C-p" "C-k" nil))
```

**Comment by noctuid** [comment]
Currently, this isn't possible. I've considered in the past, but it would be more complicated to implement (allowing lists of keys) than I think is worth it. I don't really see a huge use case for binding different keys to the same command. For example, abo-abo binds `C-r` to `swiper` and `C-s` to `counsel-grep-or-swiper`. I think it's better to make use of free keys in some other way instead of having duplicate keybindings.

I definitely see the use case for wanting to unbind several keys at once though. I'd rather add something like an `:unbind` or `:bind`:
```elisp
(use-package evil
  :general
  (i :unbind t "C-d" "C-a" "C-e" "C-n" "C-p" "C-k"))
```

I could potentially see it useful to bind several keys to `'ignore`, so I guess I could implement this in a way that would work for any command (e.g. `:bind 'ignore`).

**Comment by wpcarro** [comment]
@noctuid 

I completely agree. I also enjoy the API you're proposing.

By the way - I didn't know that I could use `i` instead of `imap` as your snippet shows. That's great!

Let me know if you'd like help implementing any of this. Although I can't promise that my Elisp is acceptable.

**Comment by noctuid** [comment]
An `:unbind` keyword now exists (see [here](https://github.com/noctuid/general.el#mass-key-unbinding)).

> By the way - I didn't know that I could use i instead of imap as your snippet shows. That's great!

Right, `i` is by default a keymap alias for `evil-insert-state-map`.

Also, I saw your issue on use-package about `:hook`. I've considered adding a use-package keyword for `general-add-hook` if I can get a better understanding of how use-package's extension system works. Your example would work without any backquotes:
```
(use-package term
  ;; same as (general-add-hook 'term-mode-hook (lambda ()...))
  :ghook (disable linum-mode))
```

Basically, for a function (or something that evaluates to a function in the above case), it would add that function to the hook corresponding to `<package>-hook` or `<package>-mode-hook` when the package doesn't end in `mode`. An actual list would just correspond to the arglist for [general-add-hook](https://github.com/noctuid/general.el#hooks-and-advice) maybe with some special substitution for the package name:
```
(use-package evil
  :ghook
  ;; same as (general-add-hook 'evil-mode-hook #'my-evil-setup)
  #'my-evil-mode-setup
  ;; same as (general-add-hook '(some-evil-hook some other evil-hook) (list #'some-func #'some-other-func))
  ('(some-evil-hook some-other-evil-hook) (list #'some-func #'some-other-func)))
```

If you'd find this useful feel free to make an issue requesting it.

**Comment by wpcarro** [comment]
@noctuid impressively fast turnaround! Thanks for doing this. I'm working on refactoring my configuration and running into an issue. 

I read the documentation, and was able to get things working with `general-define-key`. However, I'm having trouble using the `:general` kwarg with `use-package`. Here's what I tried:

```elisp
(use-package rjsx-mode
  :general
  (rjsx-mode-map :unbind t "<" "C-d" ">")
  (nmap
    :keymaps 'rjsx-mode-map
    "K" 'flow-minor-type-at-pos)
  :hook (rjsx-mode . evil-text-objects-javascript/install)
  :after (evil-text-objects-javascript)
  :mode "\\.js\\'"
  :config
  (setq js2-mode-show-parse-errors nil
        js2-mode-show-strict-warnings nil))
```

The error that I'm getting says:

```
Error (use-package): rjsx-mode/:catch: Wrong type argument: sequencep, :package
Error (use-package): rjsx-mode/:catch: Autoloading failed to define function :keymaps
```

**Comment by noctuid** [comment]
Thanks a lot for bringing this to my attention. Normally commands are extracted by iterating over the key/def pairs. Now with `:unbind`, there are no longer key/def pairs (there will never be any commands), and the number of keys can be odd, which is probably the cause of this error. I'll update the keyword to handle the `:unbind` case and see if this is the cause of the other error as well.

As a side node, `nmap` wraps `general-def`, so you can specify that as `nmap rjsx-mode-map` or `n rsjx-mode-map` instead of `nmap :keymaps 'rjsx-mode-map` if you'd like.

**Comment by wpcarro** [comment]
@noctuid Good to know it wasn't a configuration problem on my end.

As for the feedback, many thanks for the `general` tips! They're always welcome.

**Comment by noctuid** [comment]
Unfortunately, it looks like `cl-defun` cannot properly handle keyword argument parsing when there are an odd number of keys specified, so this cannot be implemented directly in `general-define-key` (without me re-implementing keyword argument parsing myself). Please try using `general-unbind` now instead and let me know if you have any issues:
```
(use-package evil
  :general
  (general-unbind i "C-d" "C-a" "C-e" "C-n" "C-p" "C-k"))
```

**Comment by wpcarro** [comment]
@noctuid That's too bad RE: `cl-defun`... frankly, I think `general-unbind` is pretty ergonomic, so it hardly feels like a downgrade to me.

I wasn't able to get this working, however. It seems the even/odd problem persists...

```elisp
;; JSX highlighting
(use-package rjsx-mode
  :after (evil-text-objects-javascript)
  :general
  (general-unbind rjsx-mode-map "<" ">" "C-d")
  (n rjsx-mode-map
     "K" 'flow-minor-type-at-pos)
  :gfhook #'evil-text-objects-javascript/install
  :mode "\\.js\\'"
  :config
  (setq js2-mode-show-parse-errors nil
        js2-mode-show-strict-warnings nil))
```

**Comment by noctuid** [comment]
It should work with the positional map argument now. Please try with the latest version.

**Comment by wpcarro** [comment]
@noctuid couldn't find latest until I switched over to Quelpa. Everything's working fine now. I appreciate the followup!
