### ISSUE TITLE
local leader does not work in evil mode until I execute an evil function

### ISSUE THREAD

**Issue by CeleritasCelery** [noctuid/general.el#116]
I am using the following config for `, ,` to exit a org source code buffer:

 ```elisp
(general-create-definer leader-local-set-key
    :prefix ","
    :states 'motion)
(leader-local-set-key
    :keymaps 'org-src-mode-map
    "," 'org-edit-src-exit)
```
However when I first open the org src block, `,` is still bound to  `evil-repeat-find-char-reverse`. once I execute any evil action (change states, copy/paste, etc) the binding will be fixed and I can use `,` as my major-mode leader. How can I make it behave correctly when I first open the org src editor?

**Comment by dieggsy** [comment]
I do something like this, and I needed `:definer minor-mode` for it to work properly.

**Comment by noctuid** [comment]
See the [FAQ](https://github.com/noctuid/general.el#why-dont-some-evil-keybindings-work-immediately). @dieggsy is correct. You can use `evil-define-minor-mode-key` (`:definer 'minor-mode` with `:keymaps 'org-src-mode`) or `(add-hook 'org-src-mode-hook #'evil-normalize-keymaps)`.
