### ISSUE TITLE
Cannot assign prefix under a prefix (keymap in keymap)

### ISSUE THREAD

**Issue by guraltsev** [noctuid/general.el#117]
I want to replicate some of the nice organization of keys done by spacemacs In paticular I am trying to
make a leader keymap `gumacs/km/leader/map` that gets assigned to the prefix `gumacs/km/leader/key` that I define to be `M-,`. 

I have done it as follows and it works well

```
(defvar gumacs/km/leader/map (make-sparse-keymap) 
  "gumacs leader keymap for gumacs/km/leader/key")  
(general-create-definer gumacs/km/leader/def 
  :keymaps 'gumacs/km/leader/map)

  (setq gumacs/km/leader/key "M-,")
  (general-define-key gumacs/km/leader/key gumacs/km/leader/map)

```

For sake of example I can bind `dired` under `M-, d` by doing

```
(gumacs/km/leader/def "d" `dired)
```

This works **great**!

Now the part I cannot make to work. I want to make a buffer management keymap that I can access from `M-, b'.  I begin as before
```
  (defvar gumacs/km/buffer/map (make-sparse-keymap) 
    "GU buffer management keymap for gumacs/km/buffer/key")  
  (general-create-definer gumacs/km/buffer/def 
    :keymaps 'gumacs/km/buffer/map)  

  (setq gumacs/km/buffer/key "b")
  (gumacs/km/buffer/def "B" 'ibuffer)
```
Up to now everything is fine.

Now I try to assign the `gumacs/km/buffer/map` to the key `b` in `gumacs/km/leader/map` and nothing happens

```
  (gumacs/km/leader/def gumacs/km/buffer/key gumacs/km/buffer/map)

```
Furthermore I noticed that if I do 
```
(define-key  gumacs/km/leader/map gumacs/km/buffer/key gumacs/km/buffer/map)
```
it **works** while
```
(general-def gumacs/km/leader/map gumacs/km/buffer/key gumacs/km/buffer/map)
```
**doesn't**. This seems to contradict the fact that `general-def` should be a substitute for `define-key`

Why? Please help

**Comment by noctuid** [comment]
> This seems to contradict the fact that general-def should be a substitute for define-key

`general-def` does not claim to be a perfect drop-in replacement. (`general-def can act as a drop-in replacement for the following definers (see the documentation below for a minor caveat)`). If you feel that the documentation could be made more clear, let me know. Since this and #118 are the same, I'm going reply in more detail there with some potential solutions.

**Comment by guraltsev** [comment]
Yeah, I just continued debugging and got to a more focused issue. Sorry for opening two reports.
