### ISSUE TITLE
problem??

### ISSUE THREAD

**Issue by xianghx** [noctuid/general.el#12]
(general-define-key :states '(normal motion insert emacs)
                    :keymaps 'emacs-lisp-mode-map
                    :prefix ","
                    :non-normal-prefix "M-m"
                    "/" 'swiper)

M-m , /          We want M-m / 
problem or you mean it ??

Did you hava a good idea? 
 I want a "M-m" can be used in normal motion insert emacs,etc.. not just in insert emacs mode.
like this:
(general-define-key :states '(normal motion insert emacs)
                    :keymaps 'emacs-lisp-mode-map
                    :prefix "," <<<normal motion ,this is working
                    :global-prefix "M-m"   <<< normal motion insert emacs
                    "/" 'swiper)
Alll I mean : M-m / can be used in all ,  and ", /" in normal motion
Thanks..

**Comment by noctuid** [comment]
Sure, I will add this.

**Comment by noctuid** [comment]
You can now use `:global-prefix` like you suggested to bind in all states:
```
(general-define-key :states '(normal motion insert emacs)
                    :keymaps 'emacs-lisp-mode-map
                    :prefix ","
                    :global-prefix "M-m"
                    "/" #'swiper)
```

If you're using this a lot, you may want to abbreviate it like this:
```
(general-create-definer general-nmie-evil-define-key
                        :states '(normal motion insert emacs))

(general-nmie-evil-define-key
 :keymaps 'emacs-lisp-mode-map
 :prefix ","
 :global-prefix "M-m"
 "/" #'swiper)
```
