### ISSUE TITLE
Problem with SPACE prefix and evil commands

### ISSUE THREAD

**Issue by aqua36** [noctuid/general.el#124]
Compare these two pieces of code 
``` 
(general-define-key
 :states '(normal visual insert emacs)
 :prefix "C-c"
 "x" 'evil-delete)
```

```
(general-define-key
 :states '(normal visual insert emacs)
 :prefix "SPC"
 "x" 'evil-delete)
```

In the first case (with C-c as the prefix) when I press C-c x  the editor waits for another command. If I press x again the whole line on which I am will be deleted (everything works as expected)
In the second case (with Space as the prefix) after pressing SPC x, you cannot delete the whole line with another x because x retains its previous binding. Instead you must press the prefix key(SPC here) in order to delete the whole line. Is there any way I can bypass this "quirk" and have SPC work like the other prefixes? 

P.S. I don't wish to rebind evil-delete, I just chose it for simplicity's sake because it exhibits the same behaviour as, let's say evil-commentary

**Comment by noctuid** [comment]
This isn't related to general, but I've made an issue on the evil repository that you can follow.

Also, make sure you remove `insert` when you actually make that `SPC` keybinding or you won't be able to type space normally.

**Comment by aqua36** [comment]
Thank you!

**Comment by noctuid** [comment]
It's not an issue with general. You can test this by just using `define-key`:
```
(define-key evil-normal-state-map (kbd "SPC x") #'evil-delete)
```

Evil leader doesn't use evil's global maps which is probably why you're not having the issue.

**Comment by aqua36** [comment]
Understood, thank you for the explanation
