### ISSUE TITLE
Key sequence SPC b b starts with non-prefix key SPC b

### ISSUE THREAD

**Issue by codygman** [noctuid/general.el#125]
I have the following code and I'm using evil:

```
(use-package general :ensure t :defer t :config
  (general-create-definer my-leader-def :prefix "SPC")

  ;; SPC SPC
  (my-leader-def :keymaps 'normal "SPC" 'helm-M-x)

  ;; SPC f
  (general-create-definer my-local-leader-def :prefix "SPC f")
  ;; SPC f f
  (my-local-leader-def :keymaps 'normal "f" 'helm-find-files)

  ;; SPC b
  (general-create-definer my-local-leader-def2 :prefix "SPC b")
  ;; SPC b b
  (my-local-leader-def2 :keymaps 'normal "b" 'helm-mini)
  )
```

And I'm unsure why I'm getting the error:

```
Error (use-package): general/:config: Key sequence SPC b b starts with non-prefix key SPC b
```

I believe I have a misunderstanding of the library. In addition to figuring out how to make this work, I'm interested in finding out what that misunderstanding is.

Thanks,

Cody

**Comment by noctuid** [comment]
Do you have `SPC b` bound to something else (e.g. check with `C-h k SPC b`). See the FAQ in general's readme for more information, and let me know if this isn't the problem.

**Comment by codygman** [comment]
@noctuid Yes I do. I haven't had a chance to test, but I'm guessing that means `my-local-leader-def2` needs to use `:override`.

**Comment by noctuid** [comment]
> Yes I do

Then the error is expected. If you want both `SPC b` and `SPC b b` bound, you can use `general-key-dispatch`.

**Comment by codygman** [comment]
I never really found my answer directly since I wanted to unbind `SPC b` and only have `SPC b b` and other `SPC b ${letter}` bindings. However for those wanting the same thing, I found someone has already defined a lot of spacemacs keybindings in this [emacs config file](https://github.com/dsdshcym/.emacs.d/blob/master/lisp/init-keybinding.el#L74) talked about in [this blog post](https://dsdshcym.github.io/blog/2018/01/22/compare-doom-emacs-spacemacs-vanilla-emacs/).

**Comment by noctuid** [comment]
Does the [faq entry](https://github.com/noctuid/general.el/blob/master/README.org#how-do-i-prevent-key-sequence-starts-with-non-prefix-key-errors) not address your question? I may not be understanding your question correctly.

**Comment by creasyw** [comment]
Thank you, @noctuid! I have the exactly same symptom and the FAQ resolve my issue. The problem is that the `SPC b` had been bound to `list-buffer` (in my case, it is `helm-mini`) before I decided to use `SPC b` for all buffer-related operations. Removing the previous bindings does fix the problem.
