### ISSUE TITLE
Cannot bind keys to sh-mode-map

### ISSUE THREAD

**Issue by sondr3** [noctuid/general.el#128]
I've hit a small snag where I'm not really sure what the problem is, I have the following configuration for `general.el`:

```elisp
(use-package general
  :demand t
  :commands (general-define-key general-override-mode general-evil-setup general--simulate-keys)
  :config
  (progn
    (setq general-override-states '(insert emacs hybrid normal visual motion operator replace))
    (general-override-mode)
    (general-evil-setup)
    (general-create-definer amalthea-leader
      :states '(normal insert emacs)
      :prefix amalthea-leader-key
      :non-normal-prefix amalthea-leader-secondary-key)
    (general-create-definer amalthea-major-leader
      :states '(normal insert emacs)
      :prefix amalthea-major-leader-key
      :non-normal-prefix amalthea-major-leader-secondary-key)
    (general-nmap "SPC m" (general-simulate-key "," :which-key "major mode"))))
```

And then I'm trying to bind some keys to the `sh-mode-map`, but the keybindings don't show up. It works for all other modes I've used it for, but not for `sh-mode`. My configuration for it is:

```elisp
(use-package sh-script
  :general
  (amalthea-major-leader 'sh-mode-map
    "i" '(:ignore t :wk "insert")
    "i c" '(sh-case :wk "case")))
```

But it just don't want to bind. I've tried googling around but can't find a good answer, I know there's a `sh-mode-map` variable, I just can't seem to bind anything to it.

**Comment by noctuid** [comment]
I'll look at this when I get the chance. In the meantime, I'd suggest using evil-define-key directly to see if that works. If you check sh-mode-map with `C-h v`, do your keybindings not show up?

As a side not, you don't need :commands in your general use-package statement since you are using :demand (and all but general--simulate-keys should already have autoloads). You also don't need to wrap your :config section in a progn.

**Comment by sondr3** [comment]
I'll try `evil-define-key`. However, I know I don't strictly need `:commands`, but otherwise the byte compiler complains. And yeah, I only do the wrapping with `progn` because I think it looks good 😄

**Comment by noctuid** [comment]
See `:functions` for satisfying the byte compiler.

**Comment by sondr3** [comment]
Are you sure the two are the same? Even the README for `use-package` shows `:commands` first and then `:functions` if that doesn't work, though I haven't looked too closely.

**Comment by noctuid** [comment]
`:commands` is specifically for creating autoloads.

**Comment by noctuid** [comment]
I've just tested and cannot replicate your issue with general. Could you describe exactly what is not working? Do your keybindings show up in `sh-mode-map`? If they do, then is the issue that they are not working in `sh-mode`?

**Comment by sondr3** [comment]
I'm fairly certain I'm doing something wrong because I can see it when I run `C-h v sh-mode-map`, it just doesn't pop up in a buffer with a `test.sh` file. I've been pulling my hair out with this today, it seems `sh-mode` is never actually called.

And thanks, I wasn't aware of that. I'll have to change things in my config then 😃

**Comment by noctuid** [comment]
What is the major of your buffer (e.g. evaling `major-mode` should show `sh-mode`; `Shell-script` should show as the major mode in the modeline)?

**Comment by sondr3** [comment]
Sorry, this was totally my fault. I named my shell script configuration `shell.el` and then did `(require 'shell)` from my `init.el`, but loaded something completely different. I renamed my files and now it works. Sorry for bothering you, and thanks for all the help 😓
