### ISSUE TITLE
Bind a key in insert state of a minor mode that take precedence over other evil bindings 

### ISSUE THREAD

**Issue by casouri** [noctuid/general.el#129]
I want to bind <kbd>C-p</kbd> in `insert` state in `eshell-mode-map`. However, if I just bind lik this:

```emacs-lisp
(general-define-key
       :states 'insert
       :keymaps 'eshell-mode-map
       "C-p" #'eshell-previous-matching-input-from-input
       "C-n" #'eshell-next-matching-input-from-input)
```

Evil has some other keys that shallow them. (`evil-complete-previous` and `evil-complete-next`).

I don't want to bind my commands in `override` map because I only want them in Eshell.

Is there any way to make my binding in `eshell-mode-map` to override evil default bindings?

Thanks!

**Comment by noctuid** [comment]
Eshell's keymaps are broken. You need to use Eshell's hook and bind locally instead. I am on mobile and unable to explain better, but there are several existing issues that should be of help; search for eshell.

**Comment by casouri** [comment]
So I had a look at the source code, and eshell seems to set its keymap locally. This is my second try:
```emacs-lisp
(add-hook
   'eshell-mode-hook
   (lambda ()
     (general-define-key
      :states 'insert
      :keymaps 'eshell-mode-map
      "C-p" #'eshell-previous-matching-input-from-input
      "C-n" #'eshell-next-matching-input-from-input
      )))
```
And it worked! Thanks! 😄
