### ISSUE TITLE
define key with lambda function

### ISSUE THREAD

**Issue by samrayleung** [noctuid/general.el#130]
I am not sure is there a way to go, I want to do somethings like this:
```emacs-lisp
(general-define-key
 "C-c b" '(if condition-equal-t (func-a) (func-other)))
```
But I could not find document about this, could I do this with general?

**Comment by noctuid** [comment]
This is possible with a menu-item.  See [`general-predicate-dispatch`](https://github.com/noctuid/general.el#choosing-definitions-based-on-predicates)

**Comment by samrayleung** [comment]
thanks, it works with `general-predicate-dispatch`, but I have the same problem with this issue https://github.com/noctuid/general.el/issues/79, is there any solution now?

**Comment by noctuid** [comment]
Follow [the which-key issue](https://github.com/justbur/emacs-which-key/issues/177). It is not possible to my knowledge.
