### ISSUE TITLE
Can't bind S-hjkl

### ISSUE THREAD

**Issue by ChrisBuchholz** [noctuid/general.el#131]
Hi

I'm having trouble binding S-hjkl.

I'm using evil, and it already binds the keys, and it seems my attempts at (re-)binding them doesn't overwrite what evil has put in place. I've tried all kinds of permutations of the following

```
(general-define-key
 :keymaps 'motion
 "S-k" 'evil-window-up
 "S-j" 'evil-window-down
 "S-h" 'evil-window-left
 "S-l" 'evil-window-right)
```

but to no avail.

How do I get general to override these bindings evil has put in place?

**Comment by noctuid** [comment]
You should be binding `K`, `J`, etc., and you should use `keymaps 'normal` because `J` is bound in normal state by default. Generally, you don't need to use `S-`.

**Comment by ChrisBuchholz** [comment]
Ah, thanks!
