### ISSUE TITLE
Mappings that work everywhere

### ISSUE THREAD

**Issue by ChrisBuchholz** [noctuid/general.el#132]
Hi

So I have the following mapping set up

```
(general-create-definer leader
 :prefix "SPC")

(leader
 :states '(normal visual)
 :keymaps 'override
...
 "f" 'treemacs
...)
```

And this allows me to toggle treemacs with 'SPC f'. However, this only works from a "not treemacs wielded" buffer. So I can do it for example in a normal buffer, but if focus is inside the treemacs buffer, the mapping doesn't work.

How do I get my mappings to work where ever I'd like, both in a treemacs buffer, and in any other buffer that doesn't behave?

**Comment by noctuid** [comment]
For reference, I've never used treemacs. What is `treemacs` supposed to do in the treemacs buffer (close treemacs?)? You should check to make sure that you are actually in normal state in the treemacs buffer. What does `C-h k SPC f` tell you in the treemacs buffer?

**Comment by ChrisBuchholz** [comment]
> What is treemacs supposed to do in the treemacs buffer (close treemacs?)?

Yes, the treemacs-function toggle the treemac buffer. It works if I call the function directly, or fire the keyboard shortcut in another buffer.

> What does C-h k SPC f tell you in the treemacs buffer

When I press C-h k, it starts the "describe the following key, mouse click, or menu item" dialog, and when I click SPC, it opens a buffer that says "SPC runs the command evil-forward-char ...". That happens when I press SPC, as in I don't get to press "SPC f".

**Comment by noctuid** [comment]
That suggests you are in motion state. Does it work if you run `evil-normal-state` in the treemacs buffer first? If so, you can either change the initial treemacs state to normal or add motion state to your override definition. Let me know if thus is not the issue.

**Comment by ChrisBuchholz** [comment]
Running `evil-normal-state` as well as adding 'motion' state to my override definition seems to work.

> you can either change the initial treemacs state to norma

How would I go about doing that?

**Comment by ChrisBuchholz** [comment]
Never mind, I discovered the following solution by digging through the evil-docs:

```
(evil-set-initial-state 'treemacs-mode 'normal)
```

Seems to function fine with treemacs and solve my problem. Thank you for your help!
