### ISSUE TITLE
Using :states for overriding keymap of major mode does not work

### ISSUE THREAD

**Issue by axelfischer** [noctuid/general.el#133]
Thanks for this great package! I have one issue though.

The desired behavior is that `SPC` in `paradox-menu-mode` is a prefix for the key bindings defined in `add-general-bindings ()`.

```
(use-package paradox
  :ensure t
  :defer t
  :config
  (setq paradox-spinner-type 'progress-bar
	paradox-execute-asynchronously t)
  :hook (paradox-menu-mode . (lambda () (add-general-bindings paradox-menu-mode-map))))

(defun add-general-bindings (keymaps)
  (general-unbind
    :states '(normal visual insert emacs motion)
    :keymaps 'keymaps
    "SPC")
  (general-define-key
   :states '(normal visual insert emacs motion)
   :keymaps 'keymaps
   :prefix "SPC"
   :non-normal-prefix "C-SPC"
   "x"   'counsel-M-x
   "SPC" 'avy-goto-char-2
   "/"   'swiper))
```

This only works if I remove the `:states`. However, `paradox-menu-mode` is in `emacs` state. Am I misunderstanding how to use this or is this a bug?

**Comment by noctuid** [comment]
I don't fully understand your issue. Are you saying that you are using `paradox-menu-mode` in emacs state only? In that case, you should remove `:non-normal-prefix`and `:states` because the expected behavior for your command is for `C-SPC` to be the prefix in emacs state not `SPC`. Or are you using paradox in normal state and that's where the issue is?

I'd just do something like this myself (`:hook` is also unnecessary/undesirable):
```elisp
(general-def 'normal paradox-menu-mode-map
  :prefix "SPC"
  "x" 'counsel-M-x)
```

**Comment by axelfischer** [comment]
Thanks for the explanation and sorry for not being more clear. Yes, that works (I was using paradox in non-normal state).
I liked to use `:hook` since I want to use those bindings for several packages. Using the hook allows me to specify the bindings within the the `use-package` function for the package - as opposed to list the mode-maps non-locally in one `general-def` function. But that is a minor issue.

**Comment by noctuid** [comment]
There's no need to define the keybindings every time you enter the paradox menu. You can call your `add-general-bindings` function directly (e.g. in `:init` or probably in `:config`). The unbind also generally shouldn't be necessary (is there a case where you get an error? if there is, general also can automatically unbind keys if you put `(general-auto-unbind-keys)` in your config).

Let me know if you encounter any other issues.
