### ISSUE TITLE
:general keyword does not seem functional out of the box

### ISSUE THREAD

**Issue by ajrouvoet** [noctuid/general.el#134]
The config below on a fresh system results in the following error:
`use-package-error: use-package: Unrecognized keyword: :general` 

```
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(eval-when-compile
  (require 'use-package))

(use-package general
  :ensure t
  :config
  (general-evil-setup t))

(use-package ranger
  :ensure t
  :general
  ("ar" 'ranger))
```

Where `use-package.el` should be on the load-path.

As far as I can by the manual, tell this should work.

**Comment by ajrouvoet** [comment]
@raxod502

**Comment by raxod502** [comment]
Cannot reproduce using latest versions of Emacs and all packages. I get this:

```
Error (use-package): ranger/:catch: Key sequence a r starts with non-prefix key a
```

**Comment by raxod502** [comment]
(I am assuming that you have manually installed `use-package` from `package.el`.)

**Comment by noctuid** [comment]
I cannot replicate either with this config:
```elisp
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-refresh-contents)

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package general
  :ensure t)

(use-package ranger
  :ensure t
  :general
  ("M-SPC" 'ranger))
```

**Comment by ajrouvoet** [comment]
The only difference as far as I can tell is that you are installing use-package from melpa. I changed that and everything works out. I had pulled use-package from the releases on github.

**Comment by raxod502** [comment]
The last release of `use-package` was over two years ago, and therefore incompatible. I don't think it's necessary to support old versions of `use-package`, but will defer to the maintainers here.

I would not recommend bypassing the package manager to install `use-package`, unless you need to run a custom fork (but see [alternative package managers](https://github.com/raxod502/straight.el)).

**Comment by ajrouvoet** [comment]
Thanks for clarifying!

**Comment by noctuid** [comment]
Yes, general doesn't support old releases of any of its optional dependencies (evil also).
