### ISSUE TITLE
Major Mode Map Prefix

### ISSUE THREAD

**Issue by rishisubramanian** [noctuid/general.el#135]
I want to make something like Spacemacs, where the major mode prefix is bound to "," or "SPC m". How can I do this with General?

**Comment by abeluck** [comment]
@rishisubramanian  How did you accomplish this?

**Comment by noctuid** [comment]
I'm not sure exactly want you want, but maybe this?
```elisp
(general-create-definer my-mm-definer
  :states 'normal
  :prefix "SPC m")

(my-mm-definer emacs-lisp-mode-map
  "b" #'eval-buffer)
```

**Comment by abeluck** [comment]
Thanks @noctuid this works great, also this as well:

```elisp
(my-mm-definer 
  :keymaps 'emacs-lisp-mode-map
  "b" #'eval-buffer)
```
