### ISSUE TITLE
Is it possible to provide an argument to a function inside a binding?

### ISSUE THREAD

**Issue by xvrdm** [noctuid/general.el#136]
> This question is probably a problem of elisp knowledge but I cannot find example in the doc that would prove me wrong. Very sorry if it is not the right place...

Is it possible to run a function with an argument for a specific binding?

I have a function that I use to insert unicode numbers.

```
(defun insert-unicode-number (n)
  "Create unicode symbol"
  (interactive)
  (let* ((prefix "DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ")
         (code (concat prefix n)))
    (insert (char-from-name code))))
```

I am trying to use it "dynamically" from general (the config works with all the functions I use without arguments.

None of these has worked so far:

```
  ...
   "u8" '(insert-unicode-number "EIGHT" :which-key "Number 8")
  ...
```

```
...
   "u8" '((insert-unicode-number "EIGHT") :which-key "Number 8")
...
```

```
...
   "u8" '((funcall insert-unicode-number "EIGHT") :which-key "Number 8")
...
```

Thanks again for the awesome package!

**Comment by noctuid** [comment]
General expects a command name; you cannot put arguments for that command in the extended definition plist. It looks like you want a function that takes an argument and returns another function:
```elisp
(defun insert-unicode-number (n)
  "Return a command that creates a unicode symbol"
  `(lambda ()
     (interactive)
     (let* ((prefix "DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ")
            (code (concat prefix ,n)))
       (insert (char-from-name code)))))
;; if you enable lexical binding at the file top, the quoting is unnecessary
;; -*- lexical-binding: t -*-
(defun insert-unicode-number (n)
  "Return a command that creates a unicode symbol"
  (lambda ()
    (interactive)
    (let* ((prefix "DINGBAT NEGATIVE CIRCLED SANS-SERIF DIGIT ")
           (code (concat prefix n)))
      (insert (char-from-name code)))))
```

You could then bind a key to the result of running the function:
```elisp
(general-def ... "u8" (list (insert-unicode-number "EIGHT") :which-key "Number 8"))
```

Alternatively you could create a function that used the prefix argument or prompted for a number to determine what unicode character to insert.

For inserting unicode characters, if you insert numbers a lot, dedicated bindings may be better, but you might want to consider using completion if you haven't already (e.g. `counsel-unicode-char`).

**Comment by xvrdm** [comment]
Thanks a lot for the answer!
I thought my `funcall` attempt to create a partial was kind of defining a function that could be used in `general`. But I will try your recommended route with `lambda` and `list`!
