### ISSUE TITLE
Use multiple keys under a prefix

### ISSUE THREAD

**Issue by sondr3** [noctuid/general.el#14]
Sorry for the confusing title, couldn't figure out how to write it properly. Anyways, I'm currently using this with Evil and really like it, and am currently using `<SPC>` as my main prefix key with a few commands mapped to keys with it. I wanted to map a few git commands to all have to start with `<SPC>g`, so for example `magit-status` would be `<SPC>g s`, but whenever I try to add two keys to it throws this error message: `Error (use-package): general :config: Key sequence SPC g s starts with non-prefix key SPC g`. I was wondering if this was possible with `general.el`? Thanks for the great plugin! :smile:

**Comment by noctuid** [comment]
The problems is probably that `SPC g` is bound to something else. Binding `SPC g` to nil beforehand will probably fix the problem. I don't think this is a problm with general, but let me know if that doesn't work.

**Comment by sondr3** [comment]
I'm a bit new to Emacs and all, how would I figure out what it's bound to before?

**Comment by noctuid** [comment]
You can use `describe-key` which is bound to `C-h k`. So `C-h k SPC g` should tell you what it is bound to. Also, I forgot to mention this, but may need to use `define-key` or `evil-define-key` to bind it to nil for now. I haven't yet added support for unbinding using `general-define-key`.

**Comment by sondr3** [comment]
Awesome, thanks! I managed to fix it. :smile:
