### ISSUE TITLE
Cannot bind to org-agenda-mode-map (evil-define-key works)

### ISSUE THREAD

**Issue by rieje** [noctuid/general.el#143]
I'm having trouble trying to bind to `org-agenda-mode-map`. The following does not work:

    (general-def :keymaps 'org-agenda-mode-map
      "j" #'org-agenda-next-line
      "k" #'org-agenda-previous-line
      "N" #'org-agenda-next-item)

However, if I add `emacs` to `:keymaps`, it will work, but only if I manually evaluate it after emacs starts up (so presumably, Emacs is somehow overriding it):

    (general-def :keymaps '(emacs org-agenda-mode-map)
      "j" #'org-agenda-next-line
      "k" #'org-agenda-previous-line
      "N" #'org-agenda-next-item)

On the other hand, the following works without any problems:

    (evil-define-key 'emacs org-agenda-mode-map "j" #'org-agenda-next-line)
    (evil-define-key 'emacs org-agenda-mode-map "k" #'org-agenda-previous-line)
    (evil-define-key 'emacs org-agenda-mode-map "N" #'org-agenda-next-item)

I'm on the latest version of `general.el`.

**Comment by noctuid** [comment]
Your `general-def` and `evil-define-key` statements are not the same. If you want to bind a key in emacs state for a keymap, you should use `:states 'emacs` or specify it the same way as with `evil-define-key`. I think this is what you want:
```elisp
(general-def 'emacs org-agenda-mode-map
  "j" #'org-agenda-next-line
  "k" #'org-agenda-previous-line
  "N" #'org-agenda-next-item)
```
