### ISSUE TITLE
How to remap C-x and C-c properly?

### ISSUE THREAD

**Issue by AmaiKinono** [noctuid/general.el#148]
I am trying to rebind `C-x` and `C-c` to `kill-region`(cut) and `kill-ring-save`(copy), and move the "original" `C-x` and `C-c` to `<leader> C-x` and `<leader> C-c`. I don't know if this is even possible, but here's what I did.

I created a definer for the leader key:

``` emacs-lisp
(general-create-definer toki-leader-def
  :prefix "C-j"
  :keymaps 'override)
```

[Here](https://www.reddit.com/r/emacs/comments/4k5gu3/can_i_reliably_remap_the_cc_and_cx_prefixes/d3cu3ws?utm_source=share&utm_medium=web2x) it says:

> C-x is bound to Control-X-prefix and C-c to mode-specific-command-prefix. Just bind them like any other command. You can use the following code to find the sparse keymap associated to a prefix:
>
> ``` emacs-lisp
> (lookup-key (current-global-map) (kbd "C-x"))
> ```

So I did this:

``` emacs-lisp
(toki-leader-def
  "C-x" '(Control-X-prefix :wk "C-x")
  "C-c" '(mode-specific-command-prefix :wk "C-c"))

(general-def
  "C-x" 'kill-region
  "C-c" 'kill-ring-save)
```

But not all things goes right:

- `<leader> C-x` works great, but `<leader> C-c` seems like an empty prefix. `which-key` told me that "there are no keys to show" after pressing `<leader> C-c`.
- `C-x` became some weird prefix. `which-key` shows this after pressing `C-x`:
  ```
  8: +prefix  @: +prefix  r: +prefix  u: undo-tree-visualize
  ```
- `C-c` still does what "the original `C-c`" does.
- `(lookup-key (current-global-map) (kbd "C-x"))` told me it's `kill-region`, and for `C-c` it's `kill-ring-save`, which is what I expected...

So, do you have any idea what should I do? Thanks!

**Comment by noctuid** [comment]
Packages that make `C-c` keybindings generally don't actually bind keys in `mode-specifc-map` / `mode-specific-command-prefix`, so it's not really useful for remapping. To bind another key to `C-c`, [simulation](https://github.com/noctuid/general.el#simulating-keypresses) is the best option I'm aware of. I should probably put this in the FAQ.

As for your rebindings for `C-x` and `C-c` not working, the global map has very low priority. Trying using `:keymaps 'override` instead.

**Comment by AmaiKinono** [comment]
@noctuid Thanks for the reply. But:

- Using `:keymaps 'override` makes `C-c` works as expected, but `C-x` doesn't work in insert state. It do work in normal or visual state, so adding a `:states` line makes it works, but I'd like to have it work no matter evil is used or not.
- If i rebind `C-c` to `kill-ring-save`, simulating it would work as copy but not "the original `C-c`". But I guess I'll just give up on this, since it looks like impossible. Just having `<leader> C-x` work as `C-x` is good enough for me.

**Comment by noctuid** [comment]
> but C-x doesn't work in insert state

You can just unbind evil's default insert state keybinding for `C-x` when using evil then.

> If i rebind C-c to kill-ring-save, simulating it would work as copy but not "the original C-c"

You can simulate keys in specific states and keymaps. At least with evil, you could bind your key in normal/insert to simulate `C-c` in emacs state. I'd imagine it's possible to do the same without evil. One possible way might be by binding in general's override keymap and simulating `C-c` with `general-override-mode` temporarily disabled so you still get the original bindings.

**Comment by AmaiKinono** [comment]
@noctuid Thanks for your kind help! It all works now.

> You can just unbind evil's default insert state keybinding for C-x when using evil then.

Put `(general-unbind 'insert "C-x")` in `(use-package evil)`'s `:config` block, and `C-x` works now.

> One possible way might be by binding in general's override keymap and simulating C-c with general-override-mode temporarily disabled so you still get the original bindings.

Yes, that definitely works. I'll paste my code below so that others can refer to it:

``` emacs-lisp
(defun mycopy ()
  (general-override-mode -1)
  (kill-ring-save)
  (general-override-mode 1))

(general-def
  :keymaps 'override
  "C-x" 'kill-region
  "C-c" 'mycopy)
```

**Comment by AmaiKinono** [comment]
@noctuid Thanks for your kind help! It all works now.

> You can just unbind evil's default insert state keybinding for C-x when using evil then.

Put `(general-unbind 'insert "C-x")` in `(use-package evil)`'s `:config` block, and `C-x` works now.

> One possible way might be by binding in general's override keymap and simulating C-c with general-override-mode temporarily disabled so you still get the original bindings.

Yes, that definitely works. I'll paste my code below so that others can refer to it:

``` emacs-lisp
(general-def :keymaps 'override "C-c" 'kill-ring-save)

(general-simulate-key "C-c")
(defun myC-c ()
  (interactive)
  (general-override-mode -1)
  (general-simulate-C-c)
  ;; somehow you have to delay it a bit or it'll not work.
  (run-with-idle-timer 1 nil 'general-override-mode))

(toki-leader-def "C-c" 'myC-c)
```

**Comment by noctuid** [comment]
When using `general-simulate-key`, you have to do something weird like use an idle timer like you are or use a hook like `post-command-hook` to re-enable the mode. There's not a cleaner way to do it. `general-key` would be a better option here, and I could extend it make it easy to do setup like this, but the downside is that it won't currently work well with which-key (see justbur/emacs-which-key#177).

**Comment by AmaiKinono** [comment]
@noctuid I see. I guess I'll use this temporary solution for now. Thank you again!

**Comment by AmaiKinono** [comment]
@noctuid Hi. I am playing with the evil scheme. It looks like this:

``` emacs-lisp
(general-unbind 'insert
  "C-x"
  "C-c"
  "C-z")

(general-def
  :states 'insert
  :keymaps 'override
  "C-c" 'kill-ring-save)

;; I have `:keymaps 'override` when creating this definer. I guess that's not the problem.
(toki-leader-def
  "C-c" (general-simulate-key "C-c" :state 'emacs))
```

But `<leader> C-c` only works in normal state. In insert state it works like `kill-ring-save`, while `describe-key` still tells me it runs `general-simulate-C-c-in-emacs-state`. Do you have any idea about this?

**Comment by noctuid** [comment]
This is a bug. Could you open a new issue? I'd fix this real quick but I'm having issues with keymaps given to `set-transient-map` not going away, and evil only provides commands to switch either emacs or normal state for the next command (so I may need to create an equivalent for any state). For now, you can either use `general-key` or create a new command that runs `evil-execute-in-emacs-state` before simulating the key.

**Comment by AmaiKinono** [comment]
I've just discovered `general-predicate-dispatch`, and here's what I come up with:

``` emacs-lisp
(general-def
  :keymaps 'override
  "C-x" (general-predicate-dispatch nil
          (region-active-p) 'kill-region
          t (general-key "C-x" :setup (general-override-mode -1) :teardown (general-override-mode)))
  "C-c" (general-predicate-dispatch nil
          (region-active-p) 'kill-ring-save
          t (general-key "C-c" :setup (general-override-mode -1) :teardown (general-override-mode))))

(toki-leader-def
  "C-x" '(Control-X-prefix :wk "C-x")
  "C-c" (general-key "C-c" :setup (general-override-mode -1) :teardown (general-override-mode)))
```

This works like a charm. I was shocked, `general.el` is just awesome... I think my problem is perfectly solved, and this issue can be closed. What do you think?
