### ISSUE TITLE
Can't use C-j as prefix key in ielm buffer

### ISSUE THREAD

**Issue by AmaiKinono** [noctuid/general.el#152]
I have `C-j` defined as the leader key:

``` emacs-lisp
(defconst my-leader-key "C-j")

(general-create-definer my-leader-def
  :prefix my-leader-key
  :keymaps 'override)
```

But in an `ielm` buffer, `C-j` runs `ielm-send-input`. This is defined in `inferior-emacs-lisp-mode-map`. I thought maybe `general-override-mode-map` was overriden by it, but I looked up `emulation-mode-map-alists` and `overriding-local-map`, and seems nothing wrong with them.

I ran `(describe-mode)`, it tells me `C-j` "is currently shadowed by another mode", and I assume that is `general-override-mode`. So `general.el` does its work well, while not doing its work well? How is that possible?

**Comment by noctuid** [comment]
I can't replicate this; it works correctly for me (with and without evil). I know the other code you were using temporarily disabled `general-override-mode`. Can you check wither `general-override-mode` is enabled in the ielm buffer?

**Comment by AmaiKinono** [comment]
Yes, it's enabled.

And I did some test with evil. It works without evil, but not with evil. I have cut my evil configuration to:

``` emacs-lisp
(use-package evil
  :config
  (evil-mode))
```

and the same will happen. I wonder maybe you did some configuration for evil that makes it work?

**Comment by noctuid** [comment]
Thanks, that makes sense. Evil keymaps will override `:keymaps 'override`. You'll either want to also bind the prefix in normal state or whatever or you can do `(setq evil-overriding-maps nil)` before loading evil for this specific case. Let me know if that doesn't work for you.

**Comment by AmaiKinono** [comment]
@noctuid. Thanks! I should have learn more about evil. This:

``` emacs-lisp
(evil-make-overriding-map general-override-mode-map)
```

gives me what I want.
