### ISSUE TITLE
How to wrap general-simulate-key in my own function?

### ISSUE THREAD

**Issue by AmaiKinono** [noctuid/general.el#153]
I want to create a function, when there's no active region, it works like `C-c` in emacs state; when there's an active region, it copies the text. But I can't figure out how to wrap a `general-simulate-key` expression in the function. Let's look at a simpler example:

``` emacs-lisp
(defun my-C-c ()
  (interactive)
  (eval `(general-simulate-key "C-c" :state 'emacs)))

(general-def
  :states '(visual insert)
  "C-c" 'my-C-c)
```

But `C-c` in visual / insert state doesn't do anything. `M-x my-C-c` doesn't do anything too.

**Comment by noctuid** [comment]
`general-simulate-key` returns a function. You should use `funcall` instead of `eval`.

**Comment by AmaiKinono** [comment]
Ah, I see. Thanks!
