### ISSUE TITLE
[question] How to use with evil-lisp-state

### ISSUE THREAD

**Issue by abeluck** [noctuid/general.el#158]
Sorry asking a question as an issue, but I'm not sure of another support channel.

I'm trying to get [evil-lisp-state](https://github.com/syl20bnr/evil-lisp-state) working with general.

Unlike other packages evil-lisp-state doesn't provide a list of commands to manually bind, rather the idea is you provide it a leader key and it will bind a bunch of commands from other packages to those keys.

I want to set the evil-lisp-state leader to `SPC k` but as you can see below I'm not sure what to pass in:

```elisp
(use-package evil-lisp-state
             :ensure t
             :init (setq evil-lisp-state-global t)
             :general
             ???
             )
```

Also, I've tried just manually  configuring it like below, but this has no effect, the leader isn't set.
```elisp
(use-package evil-lisp-state
             :ensure t
             :init (setq evil-lisp-state-global t)
             :config (evil-lisp-state-leader "SPC k"))
```

Is there any way to use evil-lisp-state with general?

**Comment by noctuid** [comment]
You should be able to bind a key to `evil-lisp-state` and then use `:states 'lisp` for your lisp state keybindings. That said, I would recommend looking at other packages like cleverparens, lispyville, and lispy as well if you haven't already. In terms of number of keypresses (and other features), evil-lisp-state is not very good comparatively.

Untested, but it would look something like this:
```elisp
(cl-pushnew '(lisp . evil-lisp-state-map) general-keymap-aliases)
(general-def 'normal "SPC k" 'evil-lisp-state)
;; or
(general-def 'normal '(emacs-lisp-mode-map lisp-mode-map ...)
  "SPC k" 'evil-lisp-state)
(general-def 'lisp ...)
```

**Comment by abeluck** [comment]
Thank you! I will check out lispyville, I'm all for less key strokes.
