### ISSUE TITLE
[unrelated][help] A bit out of my depth and was hoping for the help of a keybinding expert...

### ISSUE THREAD

**Issue by jjzmajic** [noctuid/general.el#160]
Hi @noctuid, the flexibility of `general.el` kind of made it possible for me to drop my hydra configs. To facilitate that I wrote [https://gitlab.com/jjzmajic/hercules.el](hercules.el).

Everything on `master` is working just fine, but I want to implement key- and function-based whitelists/blacklists for `hercules-def` for users who don't use `general.el` and so can't modify keymaps quite so quickly and succinctly. 

After 20+ hours of staring at my code, I still don't know what the problem is. I'm hoping someone with your experience can nudge me forward if you have the time...

**Comment by noctuid** [comment]
Sure, I can try to help. Can you give me some more information?  Is the issue with all the new code on develop? What's the actual problem you are having? Is it not working at all? I'm not at my computer right now but will try to take a look later.

**Comment by jjzmajic** [comment]
Thank you so much! All the new code in develop. The function in question is `hecules--graylist'. Whitelists never work, and only some keys can be blacklisted. There seems to be no pattern whatsoever. I should also probably wipe the keymaps clean and create new ones from scratch for whitelists, but I want to find the problem first., since blacklists don't work properly either.

**Comment by noctuid** [comment]
Have you stepped through the function with edebug? Also, could you give an example invocation of `hercules--graylist` that you expect to work but doesn't? I'm still not at my computer but can look at it later tonight.

**Comment by noctuid** [comment]
Yeah, some examples would be nice. The basic case seems to work fine:
```elisp
(defvar noct-test-map (make-sparse-keymap))

(general-def noct-test-map
  "a" #'a
  "b" #'b
  "c" #'c)

(hercules-def
 :toggle-funs #'foo
 :keymap 'noct-test-map
 :blacklist-keys "a"
 :blacklist-funs #'b)

;; evaluating noct-test-map gives the expected result
```

Swapping blacklisting with whitelisting seems to work fine for this example too.

As a side note, you can use `(symbol-value keymap)` instead of `(eval keymap)`.

**Comment by jjzmajic** [comment]
Hmmm. I did step through it, and the values collected by the loop seem fine. It's just the binding step that fails. When I nuke the old keymap no new bindings appear. Lemme sit down with that test case after work today. Want to see how you managed to get it to work. I must be missing something

**Comment by jjzmajic** [comment]
And thanks again

**Comment by jjzmajic** [comment]
Oh, and in blacklists only one key at a time works, but sometimes not even that. For example in macrostep-keymap, "c" can be hidden, but "e" cannot. I changed the implementation of the loop, but it still has exactly the same problem, which coupled with the debugging leads me to believe that the problem was with the binding part of the function. I checked, and the "right" values are definitely getting passed to define-key. The only thing that crosses my mind is that I might be passing a symbol instead of a value or vice versa somewhere. My experiments with that only made things worse (actual errors) thus far though.

**Comment by jjzmajic** [comment]
Ok, thanks to your tests, I got the blacklists to work with multiple arguments. The whitelists however are still being a pain though. You're the man. I'll do some more digging and keep you posted i (if you don't mind).

**Comment by jjzmajic** [comment]
Aaaand done. `define-key` takes a keymap value, not a symbol, which meant I needed to re-evaluate it after wiping it clean. Thanks again @noctuid!

Question about `symbol-value` though. Doesn't it return the global value of the symbol?

**Comment by noctuid** [comment]
`symbol-value` will still work for buffer-local keymaps if that's what you mean. With lexical binding, it will return the global value of the symbol even if you've bound it in a let, for example (though I can't actually seem to get this to happen). You generally won't temporarily bind a keymap to something in a let, so this doesn't really matter. And if you did, you would probably already have access to the variable and wouldn't need `symbol-value`.

**Comment by jjzmajic** [comment]
And this my friends, is why you ask the pros.

**Comment by noctuid** [comment]
I've been using `symbol-value` in general which is why I know it works. I honestly am not sure how to demonstrate this using the new lexical binding, but here's an example with the old `lexical-let`:
```elisp
(defvar foo 0)

(let ((foo 9))
  (symbol-value 'foo))
;; => 9

(lexical-let ((foo 9))
  (symbol-value 'foo))
;; => 0
```

If you ever did want the default value for a buffer-local variable, you could use `default-value`:
```elisp
;; create buffer local variable and set default value
(defvar-local bar 0)

;; set local value
(setq-local bar 9)

;; get local value
(symbol-value 'bar)
;; => 9

;; get default value
(default-value 'bar)
;; => 0
```

Generally, you should avoid `eval` where possible.

Anyway, closing this. Let me know if you have any other questions. Glad you were able to figure out the issue. Nice package idea; I'll probably start using it for edebug.
