### ISSUE TITLE
Which-key replacements do not work when prefix map is bound elsewhere

### ISSUE THREAD

**Issue by wurosh** [noctuid/general.el#162]
I realize which-key's replacement mechanisms can be limiting at times, but I wonder if there is a way around this...

## Example
```elisp
(general-def
               :prefix-map 'my:code:dap-map
               :prefix-command #'my:code::dap-command
               "." #'dap-mode-hercules
               "e" #'dap-eval
               "r" #'dap-eval-region
               "r" #'dap-restart-frame
               "t" #'dap-eval-thing-at-point
               "i" #'dap-step-in
               "n" #'dap-next
               "o" #'dap-step-out
               "o" #'dap-go-to-output-buffer
               "S" #'dap-stop-thread
               "c" #'dap-continue
               "D" #'dap-disconnect

               "u" '(:ignore t :wk "ui")
               "us" #'dap-ui-sessions
               "ul" #'dap-ui-locals
               "ub" #'dap-ui-breakpoints
               "ui" #'dap-ui-inspect
               "us" #'dap-ui-repl
               "ur" #'dap-ui-inspect-region
               "ut" #'dap-ui-inspect-thing-at-point

               "d" '(:ignore t :wk "debug")
               "dd" #'dap-debug
               "dl" #'dap-debug-last
               "dr" #'dap-debug-recent

               "s" '(:ignore t :wk "session")
               "sf" #'dap-switch-stack-frame
               "ss" #'dap-switch-session
               "st" #'dap-switch-thread

               "b" '(:ignore t :wk "breakpoint")
               "bt" #'dap-breakpoint-toggle
               "ba" #'dap-breakpoint-add
               "bd" #'dap-breakpoint-delete
               "bc" #'dap-breakpoint-condition
               "bh" #'dap-breakpoint-hit-condition
               "bm" #'dap-breakpoint-log-message)

(hercules-def
              :toggle-funs #'dap-mode-hercules
              :keymap 'my:code:dap-map
              :transient t)

;; or simply
(which-key-show-keymap my:code-dap-map)
```
The prefix replacements are visible when the map is displayed directly.

But when I bind the prefix command elsewhere all I get is `+prefix`

**Comment by noctuid** [comment]
I can look at this when I have some time and see if it's possible. If you want to look into it more, I'd suggest seeing if you can get what you want working just using which-key and making an issue for which-key if you can't.

**Comment by jjzmajic** [comment]
Definitely will do. Busy week ahead so I basically put this up as a to-do for myself as much as a ping to you. From digging through which-ley code to make hercules.el, I have a couple of thoughts, but I have a sneaking suspicion they might not pan out. I'll ping you with any updates/PRs.

**Comment by jjzmajic** [comment]
My reasoning for posting here was that which-key replacements were definitely not designed with this in mind, so a workaround was more likely on this end. If it turns out the issue can only be addressed from the which-key side, I'll change tack.

**Comment by jjzmajic** [comment]
Nope, you were right, with the current design of which-key this doesn't seem to be possible. It would be a nice feature, but it would require keeping lookups somewhere for every keymap I think. Not really worth it

**Comment by leifhelm** [comment]
I tried the following and the `+prefix` was replaced by the specified string.
```emacs-lisp
(which-key-add-keymap-based-replacements my:code:dap-map
  "u" '("ui"))
```
This lets me conclude that it would be possible.

**Comment by noctuid** [comment]
Closing in favor of #193. Follow that issue. Once it is implemented, this should be fixed.
