### ISSUE TITLE
support bind-map like minor-mode and major-mode predicates for bindings.

### ISSUE THREAD

**Issue by MoHKale** [noctuid/general.el#163]
[emacs-bind-map](https://github.com/justbur/emacs-bind-map) has support for creating bindings (to maps) that're active only while a given major or minor mode is active. Does general have support for these kinds of bindings (I know :major-modes exists as part of which-key, but whatabout minor-modes?), or is there any intention to support it in the future? I tried using the predicate argument in general-define-key with a test for whether a mode was active, but non-mode dependent bindings then don't regain control after the mode is turned off. I'd rather not use bind-map for some bindings and general for others when general should suffice & this seems like the kind of feature general should have.

Love general by the way ❤️ hopefully I'll soon be able to remove all their binding dependencies and use just general 😀

**Comment by noctuid** [comment]
To bind a key for a major mode or minor mode, specify the keymap as the mode's keymap (e.g.`org-mode-map`). I'd suggest becoming familiar with the built-in `define-key` and Emacs' keymap system (see the links at the top of general's readme). Even if you don't use `define-key` (or `evil-define-key` if you use evil) directly, general will make more sense if you know how you would do something without general. The majority of general's functionality already exists, and general just makes the syntax more concise/convenient.

Let me know if you have any other questions.

**Comment by MoHKale** [comment]
That's one way to go about it. I was trying to use general to duplicate spacemacs's leader key features. So you can set mode dependent bindings using just the mode symbol, I suppose I could just define a macro which formats the symbol like "%s-map" where for example the argument is c++-mode and it resolves to `c++-mode-map` but I was worried what would happen if the mode wasn't loaded yet. In the end I managed to basically ~copy and paste~ *develop* a [working](https://github.com/MoHKale/.dotfiles/blob/pure-emacs/.emacs.d/init.org#leader) spacemacs like leader key system.

So now I can create bindings in my leader map that're mode dependent like this:

```elisp
(mohkale/set-leader-keys-for-major-mode 'c++-mode
  "f" 'foo
  "b" 'bar)
```

because of bind-map, none of these are evaluated until c++ is loaded, and the entire prefix map under which these're bound is swapped whenever the major mode changes. does general have a feature like this built in ~(meaning I've spent a lot of time doing stuff I don't have to 😢😢😢)~?. I couldn't really see how to go about this, from any of the examples on the extensive README for general.

Sorry if I didn't explain myself properly, perhaps this example better explains what I meant.

**Comment by noctuid** [comment]
>  I was worried what would happen if the mode wasn't loaded yet

General defers keybindings until the keymap exists. You can create a macro around a general definer that adds "-map" to keymap names, but I probably won't support this directly in general. It looks like that's all the example you do points to. If there is some other functionality you want, I'm still not fully understanding. Could you give an concrete example with the behavior of keys when a mode is on vs not?

**Comment by MoHKale** [comment]
actually, that's fine, I'll probably just do the macro thing and wrap it in an eval-after-load for the mode at some point in the future. Thnx for taking the time to offer some advice. Again, really grateful for this package 😄.

**Comment by noctuid** [comment]
>  eval-after-load for the mode at some point in the future

General will already wait to make the keybinding, so this should be necessary.

Let me know if you have any further questions then.
