### ISSUE TITLE
binding M-SPC seems to introduce an empty prefix key under ESC.

### ISSUE THREAD

**Issue by MoHKale** [noctuid/general.el#169]
I'm not really sure why this is happening, but if I use general to bind a key in some map to "M-SPC" then another prefix is also defined under the "ESC" key without any bindings.

# steps to replicate
* run emacs -q
* run `M-x package-initialize`
* paste the following into your scratch buffer and then evaluate it.
```elisp
(package-initialize)
(require 'general)
(setq my-test-map (make-sparse-keymap))
(general-define-key 
  :keymaps 'my-test-map
  "M-SPC" 'foo)
```
* if you then inspect `my-test-map` you'll notice another key ESC defined without any value.
  * you can use `describe-keymap` from [`help-fns+`](https://raw.githubusercontent.com/emacsmirror/emacswiki.org/master/help-fns%2B.el) to do this.
  * you can bind the map to some key `(general-define-key "SPC" my-test-map)` and then `(require 'which-key)` to inspect the available bindings. Remember to enable `which-key-mode`.
  * as a last resort, you can just evaluate the map & you should see an extra 27 in the list. `M-: my-test-map`.

# what I see
![Capture](https://user-images.githubusercontent.com/23294780/65935412-ec810980-e410-11e9-805f-d3e759ff9f55.PNG)

# my config
I'm running `GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30`.

**Comment by noctuid** [comment]
This is the expected behavior; you should get `(keymap (27 keymap (32 . foo)))`. You'll get this by just using `define-key` as well. This is how Emacs handles the meta key (see `meta-prefix-char`) because for many terminals, pressing meta sends escape.

**Comment by MoHKale** [comment]
oh, I wasn't aware. Thnx.
