### ISSUE TITLE
general-simulate-key only works sometimes to simulate keypresses

### ISSUE THREAD

**Issue by codygman** [noctuid/general.el#172]
I'm making behavior tests for my emacs config. One thing I want to make sure I have is `ctrl u` scrolling up working since I somehow break it all the time.

This works sometimes for reasons I don't understand when I eval-expression in emacs:

```
(defun open-lorem-ipsum-goto-end-scroll-up-return-char-position ()
  (save-excursion
    (find-file "~/.emacs.d/testdata/loremipsum.txt")
    (goto-char (point-max))
    (require 'general)
    (require 'evil)
    (funcall (general-simulate-key "C-u" :state 'normal))
    (point)))
```

So before something is loading it looks like for some reason it calls `evil-scroll-up` with `nil`. But on a fresh emacs it calls `evil-scroll-up` with 4. Oh... it's passing universal argument I guess?

I used trace-function to see what it looks like when I scroll up with evil-scroll-up normally and it looks like this:

```
======================================================================
1 -> (evil-scroll-up nil)
1 <- evil-scroll-up: 0
```

I instrumented my batch run ert test to print out the trace-output as well and it gave me this:

```
1 -> (evil-scroll-up nil)
1 <- evil-scroll-up: !non-local\ exit!
```

Here is the traceback I get when that happens:

```
However, upon opening emacs fresh I get this reproducible error:

```
Debugger entered--Lisp error: (wrong-type-argument fixnump nil)
  posn-at-x-y(nil nil)
  evil-scroll-up(nil)
  funcall-interactively(evil-scroll-up nil)
  call-interactively(evil-scroll-up nil nil)
  general--call-interactively(evil-scroll-up t)
  general--simulate-keys(nil "C-u" normal nil t t)
  general-simulate-C-u-in-normal-state()
  funcall(general-simulate-C-u-in-normal-state)
  (save-excursion (find-file "~/.emacs.d/testdata/loremipsum.txt") (goto-char (point-max)) (require 'general) (funcall (progn (eval-after-load 'evil #'(lambda nil (evil-set-command-property #'general-simulate-C-u-in-normal-state :repeat 'general--simulate-repeat))) (if nil (progn (if (if (stringp ...) (load-history-filename-element ...) (featurep ...)) (progn (setq which-key-replacement-alist ...)) (eval-after-load 'which-key #'...)))) (defalias 'general-simulate-C-u-in-normal-state #'(lambda nil "Simulate 'C-u' in normal state." (interactive) (general--simulate-keys nil "C-u" 'normal nil t t))) #'general-simulate-C-u-in-normal-state)) (point))
  open-lorem-ipsum-goto-end-scroll-up-return-char-position()
  eval((open-lorem-ipsum-goto-end-scroll-up-return-char-position) t)
  eval-expression((open-lorem-ipsum-goto-end-scroll-up-return-char-position) nil nil 127)
  funcall-interactively(eval-expression (open-lorem-ipsum-goto-end-scroll-up-return-char-position) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```


Possibly related to #75?

**Comment by noctuid** [comment]
You can replicate this without general by running `(call-interactively 'evil-scroll-up)` before loading evil. If you bind a key to `evil-scroll-up` before requiring evil, it won't work either. If I add an autoload for `evil-sroll-up` and bind it to a key, I get this error as well. If that's a problem and you want that to work as expected, I'd suggest making an issue on the evil repo (it may not be easy to change that behavior though).

**Comment by codygman** [comment]
I wasn't able to reproduce my issue or the issues you noted in your comment when I tried to make a minimal reproduction before posting an issue to evil. Here is the minimal repro code where I tried to make the first 2 scenarios happen and a version of the second using general in `case 3`:

```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package general :ensure t
     :config (general-define-key "M-u" 'evil-scroll-up))

(use-package evil :ensure t 
  :init
  (setq evil-want-keybinding nil)
  (setq evil-want-C-u-scroll t)
  ;; case 1: call evil-scroll-up-before loading evil
  ;; result:
  ;; Error (use-package): evil/:init: Wrong type argument: commandp, evil-scroll-up
  ;; (call-interactively 'evil-scroll-up) 
  ;; end case 1
  ;; case 2: bind a key to evil-scroll-up before requiring evil, then in :config after evil loaded call it
  ;; (global-set-key (kbd "M-u") 'evil-scroll-up)
  ;; result
  ;; no issue, scrolls successfully errors with 'Beginning of buffer'
  ;; end case 2
  ;; case 3: bind to a key with general before requiring evil, and try calling it after
  ;; see use-package general :config block for the bind
  ;; see :config below for the interactive call
  ;; result: 
  ;; no issue, scrolls successfully errors with 'Beginning of buffer'
  ;; end case 3
  :config
   (call-interactively (global-key-binding (kbd "M-u"))) 
   ;; (call-interactively 'evil-scroll-up) 
  (evil-mode 1))```

**Comment by noctuid** [comment]
Minimal repro for me:
```elisp
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package evil
  :commands (evil-scroll-up)
  :defer t
  :ensure t)
;; after starting Emacs, M-: (call-interactively 'evil-scroll-up)

;; after starting Emacs, (global-set-key (kbd "M-u") 'evil-scroll-up)
;; it may still work, but you should get the same error message
```
Let me know if that doesn't work for you.

**Comment by codygman** [comment]
That doesn't work for me. I'm on emacs 27.0.50. I did reproduce the fixnum error with this [config](https://github.com/codygman/my-emacs-everywhere/blob/83bd0f3a66ec5ca9949ee003b9d87494e0b9b7b7/emacs-config.ell) without general though. Thank you for your help.
