### ISSUE TITLE
Does :general key word accept using general-chord?

### ISSUE THREAD

**Issue by dylanjm** [noctuid/general.el#173]
I'm having trouble getting `:general` to cooperate in making key-chords in `use-package`. Here is a current example 

```
  (use-package avy
    :straight t
    :general
    ((general-chord "jk") #'avy-pop-mark
     (general-chord "jl") #'avy-goto-line)
    :config
    (setq avy-keys '(?a ?s ?d ?e ?f ?g ?r ?v ?h ?j ?k ?l ?n ?m ?u))
    (avy-setup-default))
```

I assume `:general` expands into `(general-define-key ...)` and figured this would work. After loading my `init.el` file these chords do not load the package and do as expected.

**Comment by noctuid** [comment]
No, if you want this, you'll either have to evaluate a backquoted form such as:
```
`(use-package avy ... :general (,(general-chord) ...
```

Or I can potentially update `:general` to accept a lambda that it will evaluate to get the arglist:
```
:general (lambda () (list (general-chord "jk") #'avy-pop-mark ...))
```

See jwiegley/use-package#160 or search "backquote" on use-package issues.

**Comment by dylanjm** [comment]
Excellent, Thank I'll give that a try. I'll go ahead and close this issue.
