### ISSUE TITLE
general-key-dispatch not falling back to default Evil actions

### ISSUE THREAD

**Issue by AssailantLF** [noctuid/general.el#18]
Trying out the `general-key-dispatch`, if I use the example given by the readme:

    (general-evil-setup)
    (general-nmap "c"
                    (general-key-dispatch 'evil-change
                    "ow" 'toggle-word-wrap
                    "c" 'evil-change-whole-line))

I'm able to use `cow` and `cc`, but any normal `c*` bindings (like `cw`, `cf`, etc.) give the error: `Key sequence contains no complete binding.`

It may be related to a separate setting or package on my end.

**Comment by noctuid** [comment]
> Key sequence contains no complete binding

I don't think this is related to anything separate as I was initially getting this error when testing it. The original method worked by binding the fallback command to a key in a locally created map and then faking that key. Weirdly, depending on what key you bind it to, you may get this error. I "fixed" it for myself just by changing the key, but it seems this is not a real solution.

I've changed `general-key-dispatch` to use a different method. After updating, let me know if it works now.

**Comment by AssailantLF** [comment]
That seems to have fixed it. 

One thing to note regarding Evil is that even using `general-nmap`, `c` is broken in visual state. This is easily fixed for me by explicitly binding `c` (operator key) to `evil-change` (operator key's function).

Also hooray, now I can use unimpaired-like option toggling with `co*`!

**Comment by noctuid** [comment]
Thanks for testing.

> c is broken in visual state

That's a good point. `c` isn't bound in `evil-visual-state-map` so it gets its keybinding from `evil-normal-state-map` if you don't explicitly bind it. I've added a note to the readme to make this more clear.
