### ISSUE TITLE
[Question] Configuring Universal Abort Key for Which-Key

### ISSUE THREAD

**Issue by kingbari** [noctuid/general.el#181]
Is it possible to use general to configure a key sequence that universally aborts any which-key sequence? If yes, how? Thanks.

**Comment by noctuid** [comment]
It's bound to `C-h a` by default.

You can rebind it like this:

``` elisp
(general-def which-key-C-h-map "b" #'which-key-abort)
```

You can also change the prefix key from `C-h` to something else if you want. Take a look at which-key's documentation.

**Comment by kingbari** [comment]
Thanks for the guidance re: rebinding. I wasn't aware it was possible to change the prefix key. I've searched `which-key`'s documentation a few times now and haven't found guidance on that topic. I'll continue to search, but if you happen to know where in the documentation the configuration is explained I'd appreciate you sharing.

**Comment by noctuid** [comment]
Looks like which-key uses `help-char`. If you don't want to modify `help-char` entirely, I guess a which-key specific variable could be added. In any case, I'd suggest making a feature request or question on the which-key repo if you'd rather have some other behavior.
