### ISSUE TITLE
question: how to use a key to activate another definer

### ISSUE THREAD

**Issue by tshu-w** [noctuid/general.el#185]
I want to use general to simulate spacemacs key bindings, however, I meet the following issue that I don't know how to use a key to activate another definer.

To be more clearly, here is my current setting, however, when in general-non-normal-states, `M-SPC m` will not activate `despot-def`. Is there any way to achive this?
```emacs-lisp
  (general-create-definer tyrant-def
    :states '(normal insert visual motion emacs evilified)
    :keymaps 'override
    :prefix "SPC"
    :non-normal-prefix "M-SPC")
  (tyrant-def "" nil)

  (general-create-definer despot-def
    :states '(normal insert visual motion emacs evilified)
    :keymaps 'override
    :major-modes t
    :prefix ","
    :non-normal-prefix "M-,")
  (despot-def "" nil)

  (general-def universal-argument-map
    "SPC u" 'universal-argument-more)
  (tyrant-def
    "m"       (general-simulate-key "," :which-key "major mode"))
```

I tried to find the answer from the README, but I failed.

**Comment by noctuid** [comment]
> when in general-non-normal-states, M-SPC m will not activate despot-def

You don't have `,` bound as a prefix in any non-normal states. Probably you want something like `(general-key "," :state 'normal)`.

**Comment by tshu-w** [comment]
@noctuid Thx, it's what I need. One small problem is that when I press `SPC-m`, I got `SPC m-  which-key: There are no keys to show`

**Comment by tshu-w** [comment]
aha, I prefer `general-simulate-key` on my side, adding `:state` is enough for me.
