### ISSUE TITLE
general-key-dispatch not compatible with evil . repeat

### ISSUE THREAD

**Issue by AssailantLF** [noctuid/general.el#19]
I dunno how I didn't notice earlier, but if you set `general-key-dispatch` to an operator and then attempt to repeat it, strange behavior occurs.

It's somewhat difficult to explain. For `c` (the only thing I tried/used), motion-based changes will add extra letters in, like `cw` would add an extra `w` to the beginning of your repeated change. Still for `c`, when text objects are used like `ciw`, it gives an error: `After 0 kbd macro iterations: Quit`.

It seems to be quite a fickle feature. :P

**Comment by noctuid** [comment]
This was happening because duplicate keys were being recorded by evil. I haven't decided on the best way to handle repeating for a `general-simulate-keys` in a `general-key-dispatch`, but the problems you mentioned should be fixed.

**Comment by AssailantLF** [comment]
Everything's seems to be working well now. :)
