### ISSUE TITLE
space leader key not working in some modes like dired and the help pages

### ISSUE THREAD

**Issue by Soundtoxin** [noctuid/general.el#190]
I read about the override stuff in the readme, but it didn't make sense to me and I didn't see an example. It also seemed like maybe it was per keybind, but the thing that needs to work globally is my prefix key itself.
If I press space in dired it moved my cursor down. In the help pages it scrolls the text a bit. I rely on these bindings to change buffers and windows quickly, so now if I open dired or a help page it disrupts my flow really badly. Hopefully this is fixable. I haven't managed to figure it out after reading the readme and thinking on it for a bit.
(oh, and the non-normal-prefix doesn't work in these modes either, by the way...)
My general.el stuff from init.el below.
```
(general-define-key
:states '(normal visual insert emacs)
:prefix "SPC"
:non-normal-prefix "M-SPC"
"/" '(counsel-rg :which-key "ripgrep")
"TAB" '(switch-to-prev-buffer :which-key "previous buffer")
"SPC" '(counsel-M-x :which-key "M-x")
"ff"  '(counsel-find-file :which-key "find files")
"fs"  '(save-buffer :which-key "save file")
;; buffers
"bb" '(ivy-switch-buffer :which-key "buffers list")
"bd" '(kill-buffer :which-key "delete buffer")
"bp" '(previous-buffer :which-key "previous buffer")
"bn" '(next-buffer :which-key "next buffer")
;; eval
"eb" '(eval-buffer :which-key "eval buffer")
"er" '(eval-region :which-key "eval region")
;; open
"ot" '(link-hint-open-link-at-point :which-key "open this")
"ol" '(link-hint-open-link :which-key "open link")
"om" '(link-hint-open-multiple-links :which-key "open multiple links")
"oa" '(link-hint-open-all-links :which-key "open all links")
;; layout
"ll" '(persp-load-state-from-file :which-key "load state")
"lS" '(persp-save-state-to-file :which-key "save state")
"la" '(persp-add-buffer :which-key "add buffer")
"lA" '(persp-set-buffer :which-key "set buffer")
"lc" '(persp-kill :which-key "kill")
"lk" '(persp-remove-buffer :which-key "remove buffer")
"ln" '(persp-next :which-key "next")
"lp" '(persp-prev :which-key "previous")
"lr" '(persp-rename :which-key "rename")
"ls" '(persp-switch which-key "switch")
;; tabs
"tn" '(tab-next :which-key "next tab")
"tp" '(tab-previous :which-key "previous tab")
"tt" '(tab-new :which-key "new tab")
"tf" '(find-file-other-tab :which-key "find file other tab")
"td" '(dired-other-tab :which-key "dired other tab")
"tb" '(switch-to-buffer-other-tab :which-key "buffer other tab")
"tk" '(tab-close :which-key "tab kill")
"ts" '(tab-bar-select-tab-by-name :which-key "tab select")
"tr" '(tab-rename :which-key "tab rename")
;; window
"wl" '(windmove-right :which-key "move right")
"wh" '(windmove-left :which-key "move left")
"wk" '(windmove-up :which-key "move up")
"wj" '(windmove-down :which-key "move bottom")
"w TAB"	 '(other-window :which-key "back and forth")
"w/" '(split-window-right :which-key "split right")
"w-" '(split-window-below :which-key "split bottom")
"wd" '(delete-window :which-key "delete window")
;; quitting
"qq" '(save-buffers-kill-terminal :which-key "save and quit")
;; anime
"ad" '(anime-double-del :which-key "delete watched")
"as" '(anime-sort-new :which-key "sort new anime")
;; others
"at" '(ansi-term :which-key "open terminal")
)
```

**Comment by noctuid** [comment]
For reference, see [keymap precedence](https://github.com/noctuid/evil-guide#keymap-precedence). Your current setup is in evil's global state keymaps. By default, evil creates an overriding keymap for dired, which has a higher precedence. If you don't want want to bind your keys in an higher precedent keymap (e.g. `:keymaps 'override`) and do not use any of the functionality from `evil-keybindings.el`, you can disable this dired configuration by setting `evil-want-keybindings` to nil before loading evil. Alternatively, you can [undo the overriding keymap](https://github.com/noctuid/evil-guide#undoprevent-overridingintercept-maps) afterwards.

Evil has some modes default to motion state, which is another reason why your keybindings may not be working (see `evil-motion-state-modes` and [here](https://github.com/noctuid/evil-guide#make-evil-normal-state-the-initial-state-always)).

**Comment by Soundtoxin** [comment]
I want evil keybinds to keep working in dired, it's nice to move around with j and k, and use / for search, but I also want my space leader key general binds to work. I'm a bit confused about all these various options here. I tried setting evil-motion-state-modes to nil with setq like in the example and it didn't seem to make a difference. Space just made my cursor move down.
I'm not against setting my keys to a higher precedent, I just don't really know how that works, and it seemed like it'd be for the keys after the leader key and thus not help space being treated wrong.
I've just tried `:keymaps 'override` now like you said, and it seems to fix my problem, though! Both help pages and dired accept my general binds now. I'll close the issue now.

**Comment by bakku** [comment]
Just a follow-up question on this issue if that is okay since it is somewhat related. I had the same problem as @Soundtoxin so I added `:keymaps 'override` to my `general-define-key` configuration:

```
(general-define-key
 :states '(normal visual emacs motion)
 :keymaps 'override
 :prefix "SPC"
 "" nil
 "." '(counsel-find-file :which-key "Find file")
 "b" '(switch-to-previous-buffer :which-key "Switch to previous buffer")
 "B" '(ivy-switch-buffer :which-key "Show all buffers")
 "x" '(switch-to-scratch-buffer :which-key "Switch to *scratch* buffer")
 "p" '(:keymap projectile-command-map :which-key "Projectile commands")
 "w" '(:ignore t :which-key "Window management")
 "w v" '(split-window-right :which-key "Split window vertically")
 "w h" '(split-window-below :which-key "Split window horizontally")
 "c" '(:ignore t :which-key "Emacs config")
 "c h" '(open-emacs-home :which-key "Open emacs.d folder")
 "c s" '(open-emacs-settings :which-key "Open emacs settings.org"))
```

Sadly however, that does not seem to work in all types of buffers. At least in the `*Messages*` buffer it does not, similarly to this issue here: https://github.com/noctuid/general.el/issues/54. There @noctuid suggested to use `:keymaps '(normal visual emacs motion)` instead of `:states`. However, if I use that then again my keybindings won't work for dired or the help pages as stated in this issue. Is there a possibility to have my keybindings work in both cases?

**Comment by noctuid** [comment]
@bakku Keybindings will work after a state change. I'm not exactly sure why this is (you can look for or open a bug report on the evil repo if you want). `messages-buffer-mode` starts in normal state, but the motion state keybindings are used initially, and running `evil-normalize-keymaps` in `messages-buffer-mode-hook` does not seem to help. As a workaround you can probably also specify `motion` as a state.

**Comment by rakyi** [comment]
I'm also trying to make space work as a leader in dired and help buffers and it seems `:keymaps 'override` has no effect. Here is part of my config:

```elisp
(use-package general
  :config
  (general-override-mode)
  (general-create-definer leader-def
    :keymaps 'override
    :prefix "SPC"))

(use-package evil
  :demand t
  :general
  (leader-def 'normal
    :keymaps 'override
    "SPC" 'execute-extended-command
    "TAB" 'switch-to-previous-buffer
    "ad" 'dired
    "bd" 'kill-this-buffer
    "be" 'ibuffer
    "ff" 'find-file
    "fs" 'save-buffer
    "h" '(:keymap help-map)
    "u" 'universal-argument
    "w" '(:keymap evil-window-map))
  :init
  (setq evil-move-beyond-eol nil
        evil-undo-system 'undo-fu
        evil-want-C-u-scroll t
        evil-want-Y-yank-to-eol t
        ;; evil-want-change-word-to-end nil
        evil-want-fine-undo t
        evil-want-integration t
        evil-want-keybinding nil)
  :config
  (evil-mode 1))
```

I read a lot of the docs and related issues and I still can't figure this out. I tried setting several different/multiple :states and :keymaps and nothing seems to work. What am I missing?

**Comment by rakyi** [comment]
Switching to `(leader-def 'normal 'override ...)` works now, but I have no idea why.

**Comment by Private-inventory** [comment]
> I'm also trying to make space work as a leader in dired and help buffers and it seems `:keymaps 'override` has no effect. Here is part of my config:
> 
> ```emacs-lisp
> (use-package general
>   :config
>   (general-override-mode)
>   (general-create-definer leader-def
>     :keymaps 'override
>     :prefix "SPC"))
> 
> (use-package evil
>   :demand t
>   :general
>   (leader-def 'normal
>     :keymaps 'override
>     "SPC" 'execute-extended-command
>     "TAB" 'switch-to-previous-buffer
>     "ad" 'dired
>     "bd" 'kill-this-buffer
>     "be" 'ibuffer
>     "ff" 'find-file
>     "fs" 'save-buffer
>     "h" '(:keymap help-map)
>     "u" 'universal-argument
>     "w" '(:keymap evil-window-map))
>   :init
>   (setq evil-move-beyond-eol nil
>         evil-undo-system 'undo-fu
>         evil-want-C-u-scroll t
>         evil-want-Y-yank-to-eol t
>         ;; evil-want-change-word-to-end nil
>         evil-want-fine-undo t
>         evil-want-integration t
>         evil-want-keybinding nil)
>   :config
>   (evil-mode 1))
> ```
> 
> I read a lot of the docs and related issues and I still can't figure this out. I tried setting several different/multiple :states and :keymaps and nothing seems to work. What am I missing?

I don't know what's going on, but I think it's very important to inform you that the only thing @noctuid cares more about than this website is yanking his dick, and if you're not careful around him he'll jizz all over your keyboard.

**Comment by noctuid** [comment]
`(leader-def 'normal :keymaps 'override)` is setting the :keymaps argument twice, which was the issue. If you only provide one positional argument, it acts as the :keymaps argument.
