### ISSUE TITLE
Can't use variable as key definition

### ISSUE THREAD

**Issue by thomasheartman** [noctuid/general.el#191]
Hey,

I'm trying to configure a key binding for a specific key map using a variable, but I'm not having much luck. If I replace the variable with the literal string that it represents, it works just fine. Is this intended? Am I doing something wrong?

## Use case

I'd like to have a key that, in any relevant buffer, will format the current buffer. I'd like this key to be the same regardless of what the major or minor modes of the buffer are. In some cases I'll use `lsp-format-buffer`, in other cases it's `prettier-js` or some custom command. When a minor mode launches that provides formatting, I'd like to have my formatting key be mapped to the relevant command.

## Current setup 

To do achieve this, I have defined the key as a const:

```lisp
(defconst my-format-buffer "<f7>")
```

When trying to bind it, I've used `general-def`. No matter what the keymap is, this doesn't seem to work.
```lisp
(general-def
  my-mode-map
  my-format-buffer 'prettier-js)
```

However, this *does* work:
```lisp
(general-def
  my-mode-map
  "<f7>" 'prettier-js)
```

While the latter works, it means that I'll have to duplicate the key multiple places in my config, which makes it more likely that it'll get out of sync. Is there an easier way to achieve what I'm looking for? 

Thanks a lot for any input and also for a *very* useful package that really improves configuring Emacs.

**Comment by noctuid** [comment]
See the bottom of [this section of the readme](https://github.com/noctuid/general.el#positional-argument-wrappers), and let me know if you have any questions.

**Comment by thomasheartman** [comment]
Ah, right! I think I got it. The important bit is this, right?

> Note that all leading quoted and unquoted symbols and lists are considered to be positional arguments. This means that if you want to use a variable or function for a key that could be a positional argument, you should either use the definer `general-def` would end up using (`general-define-key`, `general-emacs-define-key`, or `evil-define-key`) or explicitly separate the positional arguments from the first key with a bogus keyword argument

Thanks! That seems to have fixed it. Reading it again, I know I've seen it a couple times, but the use case / importance hasn't really sunk in previously and it wasn't really obvious to me what was going on. Part of that may be my relative inexperience with emacs lisp and General, but it was also hard to find exactly the information I was looking for in the readme. Would it be a good idea to make it more visible somehow? Maybe by adding a separate little subheading or something?

Cheers!
