### ISSUE TITLE
Swap keys

### ISSUE THREAD

**Issue by excalamus** [noctuid/general.el#195]
There are two scenarios in which I want to swap keys.  

In the `python-mode-map`, I want to swap `-` with `_`.  I usually do this like:

```lisp
;; snakecase requires constant pressing of shift; be gone!
(define-key python-mode-map "-" #'(lambda () (interactive) (insert "_")))
(define-key python-mode-map "_" #'(lambda () (interactive) (insert "-")))
```

In `general`, I have tried to no avail:

```lisp
(general-translate-key '(insert emacs) 'python-mode-map
  "-" "_"
  "_" "-")
```

Secondly, for a Dvorak layout, I want to keep the physical position of `M-x` on the keyboard.  On Dvorak, the 'x' physical key translates to 'q'.

```lisp
(define-key key-translation-map (kbd "M-x") (kbd "M-q"))
(define-key key-translation-map (kbd "M-q") (kbd "M-x"))
```

I would think that, `general`ly speaking, this could be achieved with:

```lisp
(general-translate-key nil 'key-translation-map
  "M-x" "M-q"
   "M-q" "M-x")
```

I am mistaken.

How would I achieve each of these with `general`?

**Comment by excalamus** [comment]
With fresh eyes, it looks like I can do a straight `general-define-key` on the relevant key map:

```lisp
    (general-define-key
     :keymaps 'python-mode-map
     :states '(insert emacs)
     "-" #'(lambda () (interactive) (insert "_"))
     "_" #'(lambda () (interactive) (insert "-"))
     )
```

```lisp
    (general-define-key
     :keymaps 'key-translation-map
     "M-x" "M-q"
     "M-q" "M-x"
     "<next>" "<tab>"
     "<prior>" "<escape>"
     )
```

I notice #178, but the form of lamba there is confusing.

Unless anyone has anything to add, or if I encounter issues not revealed in my testing, this works me.

**Comment by noctuid** [comment]
Yes, `general-translate-key` only works if the key is bound in that keymap. The [simulating keys readme section](https://github.com/noctuid/general.el#simulating-keypresses) may also be helpful.
