### ISSUE TITLE
describe-personal-keybindings integration

### ISSUE THREAD

**Issue by blaenk** [noctuid/general.el#23]
It would be great if we could either integrate with bind-key's `describe-personal-keybindings` or replicate that behavior on our end. I really like being able to see all of the bindings that _I've_ made, for every mode. It allows me to, for example, scan through them every once in a while to see if there are some I'm not really using. This is much faster and efficient than tracking down the specific configuration file and the binds for it etc.

It seems like all we'd have to do is add each binding made by `general-define-key` to the `personal-keybindings` list, see [this](https://github.com/jwiegley/use-package/blob/master/bind-key.el#L162-L164). Perhaps this can be opt-in, and only if the bind-key package is present.

This and #22 are the only things I'm sorely missing from bind-key.

**Comment by noctuid** [comment]
Yes, this feature is planned. I was planning on doing it somewhat differently from bind-key and will implement it directly in this package. Let's continue any further discussion in #7.

**Comment by blaenk** [comment]
Ah sorry, I should've seen that issue.

Awesome!
