### ISSUE TITLE
general-evil-setup: Wrong type argument: symbolp, (insert emacs)

### ISSUE THREAD

**Issue by VanLaser** [noctuid/general.el#25]
Hi!

After updating to latest version, I can't call `(general-evil-setup)` (with or without `t`). When using:

```emacs-lisp
(use-package general
  :ensure t
  :config
  (general-evil-setup))
````

... I get: `Error (use-package): general :config: Wrong type argument: symbolp, (insert emacs)`. 

The debugger backtraces it to `general--evil-keymap-for-state((insert emacs))`, used with `mapcar` from `general-create-dual-vim-definer`, called from `general-evil-setup`.

**Comment by noctuid** [comment]
Sorry about that; I thought I added tests for this case but apparently not. It should be fixed now.

**Comment by VanLaser** [comment]
:+1:  Thanks! (not too big a problem, since I was able to revert to using `general-define-key`, but using `mmap` directly is nicer).

Talking about convenience -  when I'm using `SPC` as prefix (in motion map): since the key is "taken", so to speak, I have to map it to `nil` before declaring it as `:prefix` with general, or I get an error. Do you think an additional `:force` (or whatever) flag/propriety/additional-argument could make sense with `general-define-key` (and its other incarnations) so that, when used/enabled, the "map to nil before using a key as prefix" takes place automatically?

**Comment by noctuid** [comment]
Sure, I can add something like that.

**Comment by VanLaser** [comment]
( This should go without saying - please do so only if you think it fits to how you want to shape the project :) )

**Comment by noctuid** [comment]
Thinking about it more, I'm not sure if the added complexity is worth it since having to unbind the prefix beforehand isn't really a big deal. Also, if you didn't know, you can actually unbind the prefix key in the same `general-...` statement with a map of `"" nil`. Is that good enough for your use case?

**Comment by VanLaser** [comment]
While I *can't* do something like:

```emacs-lisp
(general-evil-setup t)
(mmap "SPC" nil
            :prefix "SPC"
            ...))
````

... I agree it's not a big deal having to bind it to `nil` beforehand. :)
