### ISSUE TITLE
support multiple prefixes

### ISSUE THREAD

**Issue by blaenk** [noctuid/general.el#27]
I'm not sure if this would be inherently incompatible with the way you've set up general.el, but the [bind-map](https://github.com/justbur/emacs-bind-map) package from which I migrated over to yours supports an arbitrary number of prefix keys. So for example in the readme it shows:

``` elisp
(bind-map my-elisp-map
  :keys ("M-m m" "M-RET")
  :evil-keys ("SPC m" ",")
  :major-modes (emacs-lisp-mode
                lisp-interaction-mode))
```

That means that in evil mode both `SPC m` and `,` work as prefixes to the same map. I have a feeling this might seem like unnecessary functionality but I found myself missing when transitioning from one prefix to another.

If it is something that you can add, perhaps you can simply optionally take a list like you do with `:keymaps`. I personally don't care that it's currently singular `:prefix` instead of `:prefixes` but perhaps for consistency you can add support for the other one as well, or only document the newer one from now on while continuing to support the singular form.

**Comment by blaenk** [comment]
This is no longer a big concern for me because I just figured out how to get the setup I wanted:

``` elisp
(general-create-definer my-bind
  :states '(emacs normal visual motion insert)
  :global-prefix "C-c"
  :non-normal-prefix "M-SPC"
  :prefix "SPC")
```

So now can use `C-c` from anywhere which is what I primarily cared about, but I can also get used to the `M-SPC` prefix for non-normal mode which was giving me trouble because I'd sometimes reach for `C-c` instead. And I can use `SPC` from normal mode. Great stuff!

Feel free to close this if you want.

**Comment by noctuid** [comment]
I initially didn't add support for multiple prefixes because it's redundant and seemed useless. This has been requested before with a reasonable use case, but `:global-prefix` met that use case as well. For now, I won't add support for multiple prefixes.

**Comment by jkroes** [comment]
What about this use case: binding a prefix map to "C-@" for MacOS and "C-SPC" for Windows 10, where you want the same init.el file to be used on both operating systems with similar functionality?

**Comment by noctuid** [comment]
You can check the OS and then conditionally choose the prefix based on that.
