### ISSUE TITLE
support ad-hoc prefixes

### ISSUE THREAD

**Issue by blaenk** [noctuid/general.el#28]
Consider something like this:

``` elisp
(bind*
  "k e" 'save-buffers-kill-terminal
  "k b" 'my-kill-this-buffer
  "k f" 'delete-frame
  "k o f" 'delete-other-frames
  "k o w" 'delete-other-windows)
```

It requires repeating `k` many times. Perhaps we can add some kind of convenience around this, perhaps if we have something like `:append-prefix "k"` so that it's another prefix that gets appended to the existing `:prefix`.

``` elisp
(bind* :append-prefix "k"
  "e" 'save-buffers-kill-terminal
  "b" 'my-kill-this-buffer
  "f" 'delete-frame
  "o f" 'delete-other-frames
  "o w" 'delete-other-windows)
```

Perhaps an alternative wouldn't require making separate calls for separate prefixes, so e.g. they could nest multiple prefixes:

``` elisp
(bind*
  "k" '(:nest
    "e" 'save-buffers-kill-terminal
    "b" 'my-kill-this-buffer
    "f" 'delete-frame
    "o" '(:nest
      "f" 'delete-other-frames
      "w" 'delete-other-windows
    )
  ))
```

Although that seems to get more messy and probably more complex to handle, so I'm content enough with `:append-prefix` or something like that, or perhaps you can come up with something better, perhaps you can keep specifying things like that, like:

``` elisp
(bind*
  ;; non-append prefix
  "t" 'thing

  ;; C-c k e for example
  :append-prefix "k"
  "e" 'save-buffers-kill-terminal
  "b" 'my-kill-this-buffer
  "f" 'delete-frame
  "o f" 'delete-other-frames
  "o w" 'delete-other-windows

  ;; C-c j p for example
  :append-prefix "j"
  "p" 'whatever
)
```

That doesn't really support nesting but it supports multiple differently-prefixed keys.

Honestly though I think it'd be simpler and more consistent with the existing interface to just support one `:append-prefix` and then we can make separate calls with different values for that as needed.

**Comment by noctuid** [comment]
This seems to me like it would add extra complexity wih little benefit. You could always just specify/override `:prefix` to be something like `SPC k` or `SPC k o` and use seperate `general-define-key`s.

`:append-prefix` would only be useful for wrapper functions, and for your second example, `bind* :prefix "SPC k"` (replace SPC with whatever you're using for your prefix with `bind*`) would be just as simple (and even shorter here).

I think the nesting would end up being uglier than just specifying the same key repeatedly. I kind of like the idea of the tree layout, but this would be a lot more complicated to implement than `:append-prefix`, and it seems like overkill.

The third example isn't possible with standard keyword arguments, and I'd rather not completely change how keyword arguments are handled just for this. It's less s-expressions/function calls, but it's not much shorter than just using `:prefix` with multiple `bind`s.

**Comment by blaenk** [comment]
> :append-prefix would only be useful for wrapper functions, and for your second example, bind* :prefix "SPC k" (replace SPC with whatever you're using for your prefix with bind*) would be just as simple (and even shorter here).

The problem is that that would "hard code" it to `SPC`, whereas I want it to be on all of the prefixes I have setup (global, non-normal, evil). Or am I missing something?

**Comment by noctuid** [comment]
> I want it to be on all of the prefixes I have setup

Ah okay; the use case would be for when `:non-normal-prefix`/`:global-prefix` were used. That's a good idea; I'll add it.

**Comment by blaenk** [comment]
Hey if it's too much trouble don't worry, it's probably less trouble for me to just type that prefix in the keys. I just thought I'd bring it up.

**Comment by noctuid** [comment]
Well `:prefix` is designed to support a prefix of an arbitrary length, and this:

```
(bind* :append-prefix "g"
  "a" 'command
  "b" 'command
  ...)
```

is a lot nicer than something like this:
```
(bind :prefix "SPC g"
      :non-normal-prefix "M-SPC g"
      :global-prefix "C-c g"
  "a" 'command
  "b" 'command
  ...)
```

That seems useful to me and would be trivial to add (the way it behaves in the first example), so I'll add it if you like. What do you think about calling it `:prefix-append` or just `:append` instead?

**Comment by blaenk** [comment]
I'm all for shorter names, but perhaps append by itself would be too
ambiguous for others. If so I prefer :append-prefix over :prefix-append
because it reads better I think.

**Comment by blaenk** [comment]
Also :prefix-append gives the impression (more so/relative to
:append-prefix) that it only applies to :prefix, whereas :append-prefix
doesn't have that strong of a connotation I think.

**Comment by noctuid** [comment]
To me, it wouldn't be immediately clear whether `:prefix-append` or `:append-prefix` applied only to `:prefix` or not. I'd have to look at the docs (or see whether there were equivalently named `:global-prefix-append`s to guess). `:append` is probably too vague. What do you think about `:infix`? That seems a bit more descriptive to me (and short as well).

**Comment by blaenk** [comment]
Yeah I guess `:infix`, meaning it's in between the prefix and whatever keys are bound in that call? Makes sense to me.

**Comment by noctuid** [comment]
Yeah, I added it as `:infix`. Let me know if you have any problems.
