### ISSUE TITLE
less dependency?

### ISSUE THREAD

**Issue by redguardtoo** [noctuid/general.el#3]
I'm still using Emacs 24.3 on certain machine.

Another issue is dependency on dash. I intend to use source code of general.el instead of elpa, as the way I use evil-leader. That's my strategy to manage critical packages. So critical package's dependency has to be also installed through source code. But I'm sure dash is also used by other packages installed through elpa,

Thus I could have two version's of dash which I want to avoid.

**Comment by noctuid** [comment]
The emacs 24.4 dependency is actually unnecessary, so I will remove it. I used to have a `with-eval-after-load` with multiple clauses, but I don't anymore (and eval-after-load with progn isn't that bad anyway).

I'm only using one dash function; I'll try to remove the dash dependency as well.

**Comment by noctuid** [comment]
Okay, the dash and emacs 24.4 dependencies are gone.

**Comment by redguardtoo** [comment]
cool
