### ISSUE TITLE
general-define-key error with lambda

### ISSUE THREAD

**Issue by suryakiran** [noctuid/general.el#30]
The latest general pkg from elpa is erroring out when a lambda function is bound to the keybinding.

Defined keybinding like this.

```
(general-define-key
"C-m" '(lambda () (interactive) (some-function))
)
```

Now C-m (just an example) errors out saying 'wrong type argument: commandp lambda'

It was working fine a week back.

**Comment by suryakiran** [comment]
It was working fine in version [5bae12e](https://github.com/noctuid/general.el/commit/5bae12e082d1f740c5c66b95aa051b71ce853fc2). The problem started with [5ae2056](https://github.com/noctuid/general.el/commit/5ae20567284eacb254f7387b9ed703f6dc5eb566)

**Comment by noctuid** [comment]
Thanks for reporting. I didn't know that lambdas evaluate to lists in elisp. It should be fixed now. On an unrelated note, you should avoid quoting lambdas (sharp quoting is fine though).
