### ISSUE TITLE
Eager macro-expansion failure: (void-variable keymap)

### ISSUE THREAD

**Issue by xianghx** [noctuid/general.el#31]
here:
Eager macro-expansion failure: (void-variable keymap)

**Comment by noctuid** [comment]
I think I know what the problem is, but can you give me steps to reproduce this and an example `general-define-key` statement?

**Comment by noctuid** [comment]
Nevermind, I don't think I need any more information. The problem should be fixed.

**Comment by xianghx** [comment]
yes, that's work.
thanks.
