### ISSUE TITLE
Better support for hydra?

### ISSUE THREAD

**Issue by jlee-made** [noctuid/general.el#33]
I have to start by admitting that I haven't thought this through.

Here's an example of the problem (note the `hydra-org-nav`, then look down for the next reference to that symbol):

https://github.com/AssailantLF/emacsconfig/blob/master/config.org#evil-org

The problem is that the key bindings (both keys and what they're bound to) have to be repeated, which is a shame.  Maybe general.el could support hydra better, or replace it with something equivalent?

By the way I really appreciate general.el, my emacs config is much better for using it (together with use-package)!

**Comment by noctuid** [comment]
In that example, there doesn't seem to be any repetition of keybindings to me. The hydra is defined and then bound to `zx`. Having to bind `zxj`, `zxk`, etc. would be repetition, but `zj`, `zk`, etc. are different keys. If you can give any other examples or maybe give me some suggested syntax for `general-define-key` that would do something with hydra in the background, that would be great. Right now, I'm not quite sure what it would look like to have the two integrated better.

**Comment by jlee-made** [comment]
You're right!  I thought that was required to get it to work at all, but it's not.
