### ISSUE TITLE
Overriding a default binding with nmap

### ISSUE THREAD

**Issue by sooheon** [noctuid/general.el#34]
I expect both of the following to allow me to press `-` inside a dired buffer while in normal state and jump to the upper directory. However, only the latter binding works. What am I doing incorrectly?

```
(setq general-vim-definer-default 'states)
(nmap :keymaps 'dired-mode-map
      "-" 'dired-jump)
```

```
(general-define-key :keymaps 'dired-mode-map
                    "-" 'dired-jump)
```

**Comment by noctuid** [comment]
This is probably because of the `(evil-make-overriding-map dired-mode-map 'normal)` in `evil-integration.el`. The latter works because it is not binding in `evil-normal-state-map` (the overridden keymap). See [here](https://github.com/noctuid/evil-guide#prevent-overridingintercept-maps) for other possible solutions.

**Comment by sooheon** [comment]
You are correct, this was user error. Sorry! Dired+evil was doing some remapping of keys apparently?

**Comment by sooheon** [comment]
I'm having other weirdness, I'll leave open for now and revisit with better replication steps.

**Comment by noctuid** [comment]
Sorry, that was my fault for not looking at your first section incorrectly. If you don't have the default as `states`, it won't work without extra setup, but since you do, your first command should be equivalent to the second.

**Comment by sooheon** [comment]
I think this may be related to my other issue, symbol's value as variable is void: key. When eval'ing any general form, or sometimes even when calling a general-bound key for the first time after startup, I will get that error.

**Comment by sooheon** [comment]
Closed for being a duplicate.
