### ISSUE TITLE
Better Defaults for Vim Definers

### ISSUE THREAD

**Issue by noctuid** [noctuid/general.el#37]
Currently if setting `:keymaps` is the default, `nmap`, for example, cannot be used as a wrapper for `evil-define-key` (bind in a mode for a state) without wrapping the definer in a let and changing `general-vim-definer-default`. A more ideal default would be to set `:states` if the user manually used `:keymaps`:

```
;; define key in evil-normal-state-map
(nmap "key" #'func)
;; define key in normal state for emacs-lisp-mode-map
(nmap :keymaps 'emacs-lisp-mode-map "key" #'func)
```

By setting `general-vim-definer-default` to `states` similar behavior can be achieved currently except without `:keymaps`, the global keymap is used which is not the standard way of defining a generic normal state key binding.

**Comment by dieggsy** [comment]
Ah, I like this idea a lot, actually. It's kinda more intuitive for me (what I'd "expect" to happen) and can be more concise than the `general-def` mentioned in #73

**Comment by noctuid** [comment]
It's not really that much more concise. If you use unprefixed names `(nmap ...)` vs. `(def n ...)` (or `(map n ...)`) is only a one character difference. You previously also had to specify `:keymaps` with `nmap`. I understand the appeal of `nmap`, `vmap`, etc., and this functionality is now implemented on the development branch (I will close this issue once it is merged). I also made it wrap `general-def` instead of `general-define-key`, so you can now use `nmap` in the same way:

```
(nmap org-mode-map ...) ; instead of (nmap :keymaps 'org-mode-map ...)
```

**Comment by dieggsy** [comment]
Oh, sweet. Thanks! Also is `def` supposed to be aliased by default? (I could just alias it myself anyway)

**Comment by dieggsy** [comment]
@noctuid Interestingly, when I try `(nmap org-mode-map ...)` inside `(use-package org :general ...)`, I get the following error:
```
Debugger entered--Lisp error: (void-variable nmap)
  (general-define-key nmap org-mode-map "<" 'org-metaleft ">" 'org-metaright "gh" 'outline-up-heading "gl" 'outline-next-visible-heading "gj" 'org-forward-heading-same-level "gk" 'org-backward-heading-same-level "gt" 'org-todo "ga" 'org-archive-subtree "M-l" 'org-metaright "M-h" 'org-metaleft "M-k" 'org-metaup "M-j" 'org-metadown "M-L" 'org-shiftmetaright "M-H" 'org-shiftmetaleft "M-K" 'org-shiftmetaup "M-J" 'org-shiftmetadown :package 'org)
  (ignore (general-define-key nmap org-mode-map "<" 'org-metaleft ">" 'org-metaright "gh" 'outline-up-heading "gl" 'outline-next-visible-heading "gj" 'org-forward-heading-same-level "gk" 'org-backward-heading-same-level "gt" 'org-todo "ga" 'org-archive-subtree "M-l" 'org-metaright "M-h" 'org-metaleft "M-k" 'org-metaup "M-j" 'org-metadown "M-L" 'org-shiftmetaright "M-H" 'org-shiftmetaleft "M-K" 'org-shiftmetaup "M-J" 'org-shiftmetadown :package 'org) (d/leader-keys "C" 'org-capture "bo" 'org-iswitchb "ao" '(:ignore t :wk "org") "ao#" 'org-agenda-list-stuck-projects "ao/" 'org-occur-in-agenda-files "aoO" 'org-clock-out "aoa" 'org-agenda-list "aoe" 'org-store-agenda-views "aol" 'org-store-link "aom" 'org-store-tags-view "aoo" 'org-agenda "aos" 'org-search-view "aot" 'org-todo-list :package 'org))
  eval-buffer(#<buffer  *load*> nil "/home/diego/.emacs.d/init.el" nil t)  ; Reading at buffer position 26293
  load-with-code-conversion("/home/diego/.emacs.d/init.el" "/home/diego/.emacs.d/init.el" t t)
  load("/home/diego/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x25ee6d>)()
  command-line()
  normal-top-level()
```
I can evaluate such an expression after init just fine, though.

**Comment by noctuid** [comment]
> Also is def supposed to be aliased by default

I don't want to include anything without the `general-` prefix by default, so it isn't.

The use-package issue was a known problem mentioned in the readme (positional arguments were only supported for the original two positional argument definers) and should be fixed now. `general-def` is also used by default with the `:general` keyword instead of `general-define-key`.

**Comment by dieggsy** [comment]
@noctuid thanks for the quick response, though that update seems to have broken keybindings like the following:
```emacs-lisp
:general
(:states 'normal
"a" 'b)
```
and 
```emacs-lisp
:general
("M-x" 'something)
```
Where there's no function call at first.

And I suppose I meant to ask whether `def` is supposed to be generated along with `nmap` and the like.

**Comment by noctuid** [comment]
I force pushed a minute or two after commenting last. That should be fixed.

**Comment by noctuid** [comment]
The development branch has been merged.
