### ISSUE TITLE
Help binding to evil-commentary

### ISSUE THREAD

**Issue by ivanbrennan** [noctuid/general.el#40]
Apologies if there's a solution to this that I've just overlooked, but I'm unable to get a working binding to [evil-commentary](https://github.com/linktohack/evil-commentary), which ports [commentary.vim](https://github.com/tpope/vim-commentary) to evil.

evil-commentary provides a `gc` comment operator (e.g. `g c a p` to comment the current paragraph, `g c c` for the current line) by default, which I'd like to bind to `SPC ;` (so `SPC ; a p` to comment the current paragraph, `SPC ; ;` to comment the current line, etc.).

I was previously using evil-leader to accomplish this:
```emacs-lisp
(evil-leader/set-leader "<SPC>")
(global-evil-leader-mode)
(evil-leader/set-key ";" 'evil-commentary)
```

My best attempt to do the same using general.el is:
```emacs-lisp
(general-define-key :states '(normal visual)
                    :keymaps 'evil-commentary-mode-map
                    :prefix "SPC"
                    ";" 'evil-commentary)
```

When I type `SPC ;`, I get an error reporting, "No command bound to  ;", which I've tracked down to [`evil-extract-count`](https://bitbucket.org/lyro/evil/src/f2648b841f9bcded8764ce63410065d2b8c5f856/evil-common.el?at=default&fileviewer=file-view-default#evil-common.el-679:696) in evil-common.el.

It looks like `evil-extract-count` is called with the result of `this-command-keys` as its *KEYS* argument from [`evil-operator-range`](https://bitbucket.org/lyro/evil/src/f2648b841f9bcded8764ce63410065d2b8c5f856/evil-macros.el?at=default&fileviewer=file-view-default#evil-macros.el-526:556). So in this case, it's been passed `SPC ;` (" ;").

My knowledge of Emacs keymaps is still pretty feeble. Any help you can provide would be much appreciated.

And thanks for the great plugin! Aside from this one issue, I've been really enjoying it.

**Comment by noctuid** [comment]
If you want to make a global keybinding for evil, you need to bind the key in `evil-normal-state-map` (or bind in it in the global map for normal state). 

You can abbreviate the keymaps with general (or use one of the "vim definers" like `general-nvmap`):
```
(general-define-key :keymaps '(normal visual) :prefix "SPC"
                    ";" #'evil-commentary)
```

Let me know if you encounter any problems with this.

**Comment by ivanbrennan** [comment]
@noctuid It's still not working for me. I tried
```emacs-lisp
(general-define-key :keymaps '(normal visual)
                    :prefix "SPC"
                    ";" #'evil-commentary)
```
and
```emacs-lisp
(general-define-key :states '(normal visual)
                    :keymaps 'global-map
                    :prefix "SPC"
                    ";" #'evil-commentary)
```

**Comment by noctuid** [comment]
Yeah, it probably shouldn't matter what keymap it's bound it. I can't replicate this problem. Just to ensure that it's a problem with general, does this work?

```
(define-key evil-normal-state-map (kbd "SPC ;") #'evil-commentary)
```

What does `C-h k SPC ;` message? Is this the only keybinding you've had trouble with?

**Comment by ivanbrennan** [comment]
I'm getting the same results from calling `define-key` directly. Seems less like a problem with general than just some intricacy to evil-commentary that evil-leader happened to play nice with.

`C-h k SPC ;` reports:
> SPC ; runs the command evil-commentary (found in
evil-normal-state-map), which is an interactive compiled Lisp function...
...It is bound to g c, SPC ;, \<normal-state> g c.

If I revert to my old setup using evil-leader, it reports that `SPC ;` is found in `evil-normal-state-local-map`, so maybe that's a key difference?

**Comment by noctuid** [comment]
Maybe it does matter what keymap it's bound in. That would be really strange. I'd make sure you have the latest version of evil and evil-commentary. It's understandable if `SPC ; ;` isn't working, but `SPC ; a p` or something similar works fine for me, and `SPC ; SPC` works to comment the line as well.

I see you made an issue on the evil-commentary repo. I can't help if `SPC ;` isn't working at all. I'm not sure if there is a better way to have `SPC ; ;` comment a line, but you could potentially use `general-key-dispatch` as a workaround if you really would prefer to use `SPC ; ;` to `SPC ; SPC`:

```
(general-define-key :keymaps 'evil-commentary-map
                    :prefix "SPC"
                    ";" (general-key-dispatch #'evil-commentary
                          ";" #'evil-commentary-line))
```

**Comment by ivanbrennan** [comment]
@noctuid Thanks for your help. I'll let you know if I manage to figure it out.
