### ISSUE TITLE
Any way to "share" the `c` keyspace, like in vim?

### ISSUE THREAD

**Issue by sooheon** [noctuid/general.el#43]
In vim's clj-refactor, for example, (https://github.com/clojure-vim/clj-refactor.nvim) they have used the key space "cr" in normal mode to bind all the refactorings.

If I naively try something like 
```
(nmap :keymaps 'clj-refactor-mode :prefix "c"
    "r" 'cljr--all-helpers)
```

Obviously this doesn't work because "c" is bound to `evil-change` or `lispyville-change`. Is this something that emacs just isn't designed to handle very well? The only thing I can think of is that you'd have to add the case of pressing "r" to the definition of `lispyville-change` to pass off to the other map. This sounds impossible to maintain for the variety of different configs out there. Is there a better way?

**Comment by vyp** [comment]
https://github.com/noctuid/general.el#mapping-under-non-prefix-keys ?

**Comment by noctuid** [comment]
Yeah, does `general-key-dispatch` meet your requirements? `general-define-key` doesn't try to automatically rewrite key definitions though, you have to do it manually. 

Emacs doesn't have a good way to do this, as you point out, so you have to defer judgement, call the command once a unique key sequence (or timeout) is reached, and the re-simulate the prior keys. I won't say it works perfectly. There have been problems with repeating, but I've fixed all the ones I'm currently aware of (including for some pretty unlikely cases).

**Comment by sooheon** [comment]
Ah thanks @vyp, I'd read the README when I first installed, but apparently not well enough. Thanks again @noctuid for putting a lot of thought into this!

**Comment by sooheon** [comment]
@noctuid Could you help me out with binding the keys/function pairs of [`cljr--all-helpers`](https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L305) under "cr"?

I want it to work something like this:

```
(nmap :keymaps 'clj-refactor-map
    "c" (general-key-dispatch 'lispyville-change
            "r" 'cljr--all-helpers
            "c" 'evil-change-whole-line))
```

**Comment by noctuid** [comment]
Right now i just have a separate `general-key-dispatch` for each, but maybe just create a function for that and set it as the fallback (I haven't tested this):

```
(defun lispyville-or-evil-change ()
  (interactive)
  (if (bound-and-true-p lispyville-mode)
      (call-interactively #'lispyville-change)
    (call-interactively #'evil-change)))
```

As for binding r, it seems like those keys are all bound under `clj-refactor-map`, so try bindiing `"r" clj-refactor-map`.

**Comment by noctuid** [comment]
`general-key-dispatch` will now check to see if the command has been remapped, so there is no longer a need to have a separate `general-key-dispatch`. For `(general-key-dispatch 'evil-change...')`, `lispyville-change` will automatically be used instead of `evil-change` when lispyville-mode is active (with the latest versions of general and lispyville).
