### ISSUE TITLE
which-key support for general-key-dispatch

### ISSUE THREAD

**Issue by yyadavalli** [noctuid/general.el#44]
Thank you for this wonderful package.

One feature request I have is, to support `:which-key` for `general-key-dispatch`. Atleast for the top level command should be good.

Also support to add a docstring for the generated function would be good, it can be used to document sublevel bindings when using a `:timeout`

Here is a small example use case I have in mind, I would like `, w` to show `g` with 
"Search google"

```emacs-lisp
(general-define-key :prefix ","
   "w g" (general-key-dispatch 'engine/search-google
             :timeout 0.5
             "i" 'engine/search-google-images
             "m" 'engine/search-google-maps)
    "w h" '(engine/search-github :which-key "Search Github")
    "w y" '(engine/search-youtube :which-key "Search Youtube"))
```

**Comment by noctuid** [comment]
This is in a way related to #39.

With the recent change to which-key a few days ago, I could now add a `:which-key` keyword to `general-key-dispatch` (even not knowing the key the function will be bound to). At the moment, you could add an additional `"w g" '(:ignore t :which-key "description")'`.

`general-key-dispatch` already supports replacing the docstring with the `:docstring` keyword. Note that I do plan on adding listing the mappings in the docstring by default in the future.

**Comment by noctuid** [comment]
Alright, I've added it. It requires a recent version of which-key though. Let me know if you have any problems.

**Comment by yyadavalli** [comment]
Thanks a lot, it is working as expected.
