### ISSUE TITLE
is :prefix really supported for nmap?

### ISSUE THREAD

**Issue by ninrod** [noctuid/general.el#46]
hi @noctuid, 

I've just installed general.el with this setup (it's a snippet that is written on the readme page)

```elisp
(general-evil-setup)
;; all keywords arguments are still supported
(general-nmap 
              :prefix "s"
              "d" 'dired)
```

but when I restart emacs, I'm greeted with an error:

```txt
Warning (initialization): An error occurred while loading ‘/Users/ninrod/.emacs.d/init.el’:
error: Key sequence s s starts with non-prefix key s
```

Am I missing something here?

**Comment by noctuid** [comment]
If `s` is already bound, you need to unbind it before you try to use it as a prefix. For example, add a `"" nil` before `"d" 'dired`.

**Comment by ninrod** [comment]
it worked! but what exactly does `"" nil` do? seems hacky. 
I did not bind s, but evil did.

**Comment by noctuid** [comment]
`""` just corresponds to the prefix if you want to bind it by itself in the same statement. You could also do `(general-nmap "s" nil)` if you prefer.

**Comment by ninrod** [comment]
Oh, all right. It is working fine with this line. Thanks! Awesome package by the way!
