### ISSUE TITLE
Conditional prefix

### ISSUE THREAD

**Issue by excalamus** [noctuid/general.el#460]
How might I go about toggling a prefix key for a given map?

I have two input devices, a standard keyboard and a steno machine.  I use "SPC" as a prefix key with the keyboard (in evil normal state).  The steno device, however, sometimes prefixes spaces to strokes, creating conflicts.  One solution is to have a different prefix, such as "→", which is difficult to write with a keyboard and easy to write with steno.  I have a state variable which indicates whether the steno machine is active.  

- Is there a conditional similar to `general-predicate-dispatch` for prefixes? 

- Can I "reload" bindings?  I imagine this could be done by first unbinding and then rebinding.  I know of `general-unbind`.  I understand it to only work on a key-by-key basis, though.  I could unbind all keys and then rebind them, one-by-one, but that's a lot of duplication.  Is there a way to unbind en-masse for an entire map?  Perhaps something like 

```lisp
(defun xc/general-reload ()
  "Toggle prefix based on `xc/plover-enabled'."
  (interactive)
  (let ((prefix (if xc/plover-enabled "→" "SPC")))
    (general-unbind :states '(normal visual))
    (general-def :states '(normal visual)
      :prefix prefix
          "m" '(lambda () (interactive) (message "Hello world")))))
```

- Do you have any recommendations?

Thank you, kindly, for your time and for the wonderful general.el library.

**Comment by juihyufs** [comment]
please don't flatter him too hard he's already married to this website

**Comment by excalamus** [comment]
Apologies if my words appear insincere.  They're not.  I believe thanks should be given when felt, especially when deserved.  Both apply here.  Clearly, "there is no warranty for the work".  There's no obligation to read, let alone respond to my questions, by the author or anyone else.  The FLOSS community has a reputation for rudeness leading to burnout.  If I can't ease that through monetary or labor contribution, let my words at least express gratitude.

**Comment by noctuid** [comment]
Thanks for the kind words. Key definitions in Emacs can't be predicates. You could create a minor mode and enable/disable that when switching to/from the steno machine, but this would only work for global keybindings. You might be able to do something hacky with key translations, but I'm not sure. I can't think of a better idea than the one you had.

To make it easier to write `general-unbind` would need some changes. You can try evaluating these redefinitions:


```elisp
(defun general--split-on-positional-args (rest)
  "Remove all positional arguments from the list REST.
Return a list of containing the list of positional arguments and the and a list
of the other arguments. The order of arguments will be preserved."
  (let (positional-args)
    (while (general--positional-arg-p (car rest))
      (push (pop rest) positional-args))
    (list positional-args rest)))

(cl-defmacro general-unbind (&rest args)
  "A wrapper for `general-def' to unbind multiple keys simultaneously.
Insert after all keys in ARGS before passing ARGS to `general-def.' \":with
#'func\" can be optionally specified to use a custom function instead (e.g.
`ignore'). :full t can be used to specify that ARGS contains key/command pairs
instead of just keys. This can be useful to create a command that either binds
or unbinds commands."
  (declare (indent defun))
  ;; Note: :with can be at an odd position, so must handle internally and not
  ;; with &key
  (let* (with
         full
         (split-args (general--remove-keyword-args args))
         (kargs (cl-loop for (key val) on (cadr split-args) by 'cddr
                         if (memq key '(:with :full))
                         do (if (eq key :with)
                                (setq with val)
                              (setq full val))
                         else
                         collect key
                         and collect val))
         (split-maps (general--split-on-positional-args (car split-args)))
         (maps
          (if full
              (cl-loop for (key _) on (cadr split-maps) by 'cddr
                       collect key
                       and collect (if (eq with t)
                                       nil
                                     with))
            (cl-loop for key in (cadr split-maps)
                     collect key
                     and collect (if (eq with t)
                                     nil
                                   with))))
         (args (append (car split-maps) maps kargs)))
    `(general-def ,@args)))


(defvar xc/steno-hook nil)
(defmacro xc/steno-define (&rest args)
  `(progn
     (general-def ,@args :prefix "→")
     (general-add-hook 'xc/steno-hook
                       (lambda ()
                         (if xc/plover-enabled
                             (general-unbind ,@args :prefix "SPC" :full t)
                           (general-def ,@args :prefix "SPC"))))))

(xc/steno-define 'normal "m" #'command)
```

I assume it's okay to always keep the "→" keybindings.

I haven't tested this. Let me know if this works, and I can add the changes to `general-unbind` so that you can create `xc/steno-define`.

You could call `(run-hooks 'xc/steno-hook)` when switching between inputs to reload all keybindings.

**Comment by excalamus** [comment]
Thank you, @noctuid, for taking the time to look into my question and for developing a solution.  When time permits, I'll grok it and give it a trial run.
