### ISSUE TITLE
using hydra along with general.el

### ISSUE THREAD

**Issue by ninrod** [noctuid/general.el#48]
hi @noctuid, 

I have all my hydras organized to the `SPC h` keybind. So for example, `SPC hz` will execute my zooming hydra, and so on and so forth. 

What I would like to do is this:

```elisp
(general-create-definer spc-map
   :states '(normal visual motion)
   :prefix "SPC")
  (spc-map
   "h" 'here-would-go-my-zooming-hydra?)  ; I wish that worked!
```

But is seems that hydra requires a premade keymap for the `defhydra` macro. Does general.el creates a custom keymap when I call my custom `spc-map` function so I could feed into the `defhydra` macro like this? 

```elisp
(defhydra hydra-zoom (my-awesome-custom-spc-map "hz") ; here!
  "zoom"
  ("i" text-scale-increase "in")
  ("o" text-scale-decrease "out"))
(which-key-declare-prefixes "SPC h" "hydras")
(which-key-add-key-based-replacements "SPC hz" "zooming hydra")
```

**Comment by ninrod** [comment]
Ok, I've just found a solution:

```elisp
(defhydra hydra-zoom ()
    "zoom"
    ("i" text-scale-increase "in")
    ("o" text-scale-decrease "out"))

  (spc-map
   "hz" 'hydra-zoom/body
   )

  (which-key-declare-prefixes "SPC h" "hydras")
  (which-key-add-key-based-replacements "SPC hz" "zooming hydra")
```

**Comment by noctuid** [comment]
As a note, general also allows adding which key replacement strings, but I haven't yet updated it for the newest version of which-key (see #39 for some related discussion).

**Comment by ninrod** [comment]
hum. I don't know what replacements mean, but these are working for me:

```elisp
(defhydra hydra-zoom ()
    "zoom"
    ("i" text-scale-increase "in")
    ("o" text-scale-decrease "out"))

  (spc-map "z" '(:ignore t :which-key "ma[g]it"); here!
   "hz" 'hydra-zoom/body
   )
```
