### ISSUE TITLE
`Which-key` not working with `general-chord` prefix

### ISSUE THREAD

**Issue by markgdawson** [noctuid/general.el#486]
The following code:
```
(general-define-key
 :prefix (general-chord "op")
 "~c" 'some-function)
```
Will pop up the which-key window on the keychord `[key-chord ?y ?u]` (i.e. the letters yu in quick succession). But won't show which-key for nested maps (i.e. if I then hit `~` the which key popup won't show.

To clarify, I was expecting that the which key popup would appear on `[key-chord ?y ?u] b`.

Using a non-chord prefix key it seems to work as I expected, for example:
```
(general-define-key
 :prefix "C-x"
 "~c" 'some-function)
```
will pop up the which-key popup on `C-x ~`

**Comment by noctuid** [comment]
This is unrelated to general. You can see the same behavior with `define-key`:

```
(define-key global-map (kbd "<key-chord> o p ~ c") 'some-function)
```
The same behavior seems to happen when binding the key chord to a keymap and then binding keys in the keymap. Maybe make an issue on the which-key repository.
