### ISSUE TITLE
Add an option to disable autoloading a command in `use-package` integration

### ISSUE THREAD

**Issue by VojtechStep** [noctuid/general.el#489]
When using the `:general` keyword in a `use-package` declaration, general unconditionally adds all bound commands to the `:commands` section, which triggers `use-package`'s autoloading mechanism. However, sometimes the bound function is defined somewhere else than the package's file, which can lead to warnings when byte-compiling the configuration.

For example, I structure my config in the following way (contrived example):
```elisp
(use-package projectile
  :general
  ('override
    "f" '(vs-ff-dwim :wk "files in project"))
  :preface
  (defun vs-ff-dwim ()
    ...))
```
which expands to (abbreviated)
```elisp
(progn
  ...
  (eval-and-compile
    (defun vs-ff-dwim nil nil))
  (unless
      (fboundp 'vs-ff-dwim)
    (autoload #'vs-ff-dwim "projectile" nil t))
...
```

Byte-compiling this code raises a warning:
```
init.el:544:10: Warning: function ‘vs-ff-dwim’ defined multiple times in this file
```
because the function is both defined and autoloaded.

I propose a new keyword argument be added to the keybinding definition, `:no-autoload`, which prevents the keybinding from generating an autoload.

**Comment by noctuid** [comment]
Yes, definitely. I think there should probably also be a global setting to disable generating autoloads.
