### ISSUE TITLE
the Info-mode keymap war

### ISSUE THREAD

**Issue by ninrod** [noctuid/general.el#49]
Hi @noctuid, 

I want that when I'm in Info-mode, `"DEL"` goes back in history, and `"SPC"` invokes `counsel-M-x`. 

I'm trying this following snippet, to no success. Info-mode's keybinds remain the same! How would one go about setting up this keybind modification?

edit: if I specify `:states 'normal` is does not make a difference, either

```elisp
(general-define-key
 :keymaps '(Info-edit-map
            Info-edit-mode-map
            Info-link-keymap
            Info-merged-map
            Info-mode-line-node-keymap
            Info-mode-map
            Info-speedbar-key-map
            Info-tool-bar-map)
 "SPC" nil
"DEL" nil
)

(general-define-key
   :keymaps '(Info-edit-map
              Info-edit-mode-map
              Info-link-keymap
              Info-merged-map
              Info-mode-line-node-keymap
              Info-mode-map
              Info-speedbar-key-map
              Info-tool-bar-map)
   "DEL" 'Info-history-back
   "SPC" 'counsel-M-x)
```

**Comment by noctuid** [comment]
My first guess is that you have motion state as the initial state (evil binds space and DEL in the motion state keymap for Info-mode-map). Try binding these keys in motion state instead or changing the initial state to normal. Please see [here](https://github.com/noctuid/evil-guide#evils-tools) and [here](https://github.com/noctuid/evil-guide#make-evil-normal-state-the-initial-state-always) and let me know if this isn't the issue.

**Comment by ninrod** [comment]
Thank you very much @noctuid! this follwing snippet is working!

ps: I probably don't need all those info keymaps, but I was in despair.

```elisp
(general-create-definer
   info-keybind-war
   :keymaps '(Info-edit-map
              Info-edit-mode-map
              Info-link-keymap
              Info-merged-map
              Info-mode-line-node-keymap
              Info-mode-map
              Info-speedbar-key-map
              Info-tool-bar-map))
(info-keybind-war
   :states 'motion
   "DEL" 'Info-history-back
   "SPC" 'counsel-M-x)
```

**Comment by ninrod** [comment]
for completeness, all those extra maps are not needed. this works just fine:

```elisp
(general-define-key
   :keymaps 'Info-mode-map
   :states 'motion
   "DEL" 'Info-history-back
   "SPC" 'counsel-M-x)
```
