### ISSUE TITLE
Key sequence starts with non-prefix key.

### ISSUE THREAD

**Issue by apoorv569** [noctuid/general.el#492]
I am having a problem with `general.el` package. I have `SPC` set as a prefix and then other keys as sub-prefix, then some other keys as actions, like how `Doom Emacs` has.

``` elisp
(nvmap :states '(normal visual) :keymaps 'override :prefix "SPC"
  "SPC"   '(find-file :which-key "Find file")
  .
  .
  .
  "m"       '(:ignore t :which-key "Org")
```

All this works.. But when I add this line,

```elisp
"m i"     '(:ignore t :which-key "Insert")
"m i i"   '(org-insert-item :which-key "Org insert item")) 
```

It gives error saying,

> "Key sequence SPC m i i starts with non-prefix key SPC m i"

I basically want `SPC m` to be a preifx for `Org` related actions, then `i` for `Org` insert related actions.

**Comment by noctuid** [comment]
Have you bound `SPC m i` somewhere else? What does `C-h k SPC m i i` show?

**Comment by apoorv569** [comment]
> Have you bound `SPC m i` somewhere else? What does `C-h k SPC m i i` show?

Ah! Yes, it was already bound to something else, I forgot to unbind it. I set it to `:nil` first, then changed to `:ignore`. Now its working.

Thanks!

Will close this now.
