### ISSUE TITLE
Overriding mapping in minor modes 

### ISSUE THREAD

**Issue by husainaloos** [noctuid/general.el#494]
I would like to setup a mapping that works in all modes, and override it in specific mode. In particular, I want to use `SPC o` for `ace-link`, but I want to override it if the minor mode is `w3m-minor`, in which case I want to override it to a custom function.

I tried 
```
(general-nmap
    :keymaps 'override
    :prefix "SPC"
    "o" 'ace-link)

(general-nmap
    :keymaps 'w3m-minor-mode-map
    :prefix "SPC"
    "o" 'my-custom-function)
```

This did not work because `override` overrides everything. Hence in `w3m-minor-mode`, "o" calls `ace-link`. This is expected.

I tried also 

```
(general-nmap
    :prefix "SPC"
    "o" 'ace-link)

(general-nmap
    :keymaps 'w3m-minor-mode-map
    :prefix "SPC"
    "o" 'my-custom-function)
```

In this case "o" calls `ace-link` in every mode, but in w3m-minor-mode, "o" does nothing.

I was wondering if there is a way to do a minor override.

(UPDATE: quoted the keymaps  map)

**Comment by noctuid** [comment]
It should be

```elisp
(general-nmap
    :keymaps 'w3m-minor-mode-map
    :prefix "SPC"
    "o" 'my-custom-function)
```

**Comment by husainaloos** [comment]
> It should be
> 
> ```emacs-lisp
> (general-nmap
>     :keymaps 'w3m-minor-mode-map
>     :prefix "SPC"
>     "o" 'my-custom-function)
> ```

Thanks. I updated the question. It was a typo.

**Comment by noctuid** [comment]
That should work fine if that's the keymap you want to use. If `o` no longer does anything with w3m minor mode, that sounds like an issue with your custom command.
