### ISSUE TITLE
Using key-combo for evil-escape truncates one character from repeat

### ISSUE THREAD

**Issue by pearofducks** [noctuid/general.el#50]
#### Steps to repeat:

1. Use the config below
2. Enter insert-mode, type "Hello", then hit "kj" to enter normal-mode
3. Hit `.` to repeat in evil

#### Result:

"Hell" is output as the repeat

#### Expected result:

"Hello" is output as the repeat

---

- I've minimized my `.emacs` down to minimal packages and this still happens, so doesn't appear to be caused by other packages.
- Using `ESC` instead of the key combo will produce the correct result, so this doesn't appear to be caused by evil itself either.

---

Config:

```
(use-package general
  :config
  (general-evil-setup t)
  (general-imap "k" (general-key-dispatch 'self-insert-command :timeout 0.25 "j" 'evil-normal-state)))
```

**Comment by noctuid** [comment]
`general-key-dispatch` has to do a lot to get `evil-repeat` working for different situations, so this most likely is a bug. I'll look into it when I get the chance.

**Comment by noctuid** [comment]
It's probably not directly related, but some of the other repeat tests are now failing for me (even on previous commits where they were working; it most likely has to do with the newest evil version). I've been meaning to try to simplify the handling of repeating and address #45, and I will fix this issue then. It will probably be at least a few weeks before I can work on it.

I recommend using `key-chord` for this functionality instead if repeating works for it.

**Comment by noctuid** [comment]
This issue is now fixed.
