### ISSUE TITLE
How to pass a command list to `general-define-key`

### ISSUE THREAD

**Issue by kguidonimartins** [noctuid/general.el#501]
Hi! Congratulations on your work on this package. This is really helpful!

Sorry for bothering you with this. I've been using Emacs recently and haven't found a solution to this challenge yet.
I would like to avoid repeating of the command list passed to `general-define-key`. It would be nice if I could have two leader-keys (comma and space) with the same commands. I tried passing a `cons` to the `general-define-key`, but it doesn't seem to work.

My current configuration with the repeated command list is this:

```elisp
(use-package general
  :config
  (general-create-definer first-leader-key
    :keymaps '(normal insert visual emacs motion operator)
    :prefix ","
    :global-prefix "C-,")

  (general-create-definer second-leader-key
    :keymaps '(normal insert visual emacs motion operator)
    :prefix "SPC"
    :non-normal-prefix "C-SPC")

  (first-leader-key
    "b" 'switch-to-buffer
    "d" 'delete-window)

  (second-leader-key
    "b" 'switch-to-buffer
    "d" 'delete-window))
```

To avoid repetition, I tried something like:

```elisp
(setq general-cmd-list '(("b" 'switch-to-buffer)
                         ("d" 'delete-window)))

(first-leader-key general-cmd-list)
(second-leader-key general-cmd-list)
```

Thanks in advance for any help.

**Comment by noctuid** [comment]
It is simpler to just create a single definer for both:
```elisp
(defmacro both-leader-keys (&rest args)
  `(progn
     (first-leader-key ,@args)
     (second-leader-key ,@args)))

(both-leader-keys
 "b" 'switch-to-buffer
 "d" 'delete-window)
```
