### ISSUE TITLE
Prefix is not working with local leader definer

### ISSUE THREAD

**Issue by noghartt** [noctuid/general.el#504]
When I try to do something like:
```elisp
(localleader-def
 :states 'normal
 :keymaps 'emacs-lisp-mode-map
 :prefix "b"
 "e" #'eval-buffer)
```
When I hit `SPC m e b`, that is: local leader + `"b e"`, this isn't working. Without `:prefix` works.

**Comment by noctuid** [comment]
Assuming your `localleader-def` specifies `:prefix "SPC"`, you are overriding that with `:prefix "b"`.  You should use `:infix "b"` instead.
