### ISSUE TITLE
which-key labels not shown in prefix-command keymaps

### ISSUE THREAD

**Issue by ghost** [noctuid/general.el#505]
Hello,
I am using the following configuration (inspired by Spacemacs):

```emacs-lisp
(general-define-key
 :states 'normal
 "SPC" '(:prefix-command my/space-menu-map :wk "S P A C E  menu")
 )

(general-define-key
 :keymaps 'my/space-menu-map
 "b" '(:prefix-command my/buffer-menu-map :wk "Buffer…")
 "f" '(:prefix-command my/file-menu-map :wk "File…")
 "h" '(:prefix-command my/help-menu-map :wk "Help…")
 )

(general-define-key
 :keymaps 'my/file-menu-map
 "s" '(save-buffer :wk "save")
 )
```

This works fine, except that the which-key labels are not shown (I just see the keymap or command name). Which-key does work outside of `:prefix-command` keymaps.

**Comment by noctuid** [comment]
Use [keymap-based replacements](https://github.com/justbur/emacs-which-key#keymap-based-replacement) instead of `:wk`. 

For the prefix commands, you might be able to just replace `:wk` with `:prefix-name`.  If not, you will have to bind to a cons (e.g. `(cons "Buffer…" 'my/buffer-menu-map)`.
