### ISSUE TITLE
general-define-key hangs when using evil features and lexical-binding

### ISSUE THREAD

**Issue by rcj** [noctuid/general.el#51]
When using evil features in combination with lexical-binding, general-define-key hangs.

Minimal repro: emacs -Q --load test.el

```
;;; -*- lexical-binding: t -*-
(require 'evil)
(evil-mode t)
(require 'general)
(general-define-key :states '(normal) "M-x" M-x)
```

**Comment by noctuid** [comment]
Thanks for reporting. I was originally going to wait for another evil release to make the change that fixes this particular issue, but evil isn't even on melpa stable, and `evil-define-key*` has existed long enough. It should be working now.

As a small side note that may or may not be helpful, unless you intentionally need to use `:states` for something like this, I'd recommend using `:keymaps 'normal` instead.
