### ISSUE TITLE
Hydra - pink color argument type

### ISSUE THREAD

**Issue by sho-87** [noctuid/general.el#52]
I'm having some difficulty getting pink hydras to work with `general-define-key` (i've posted this in the hydra repo as well, but the problem doesn't seem to be hydra related)

I have a `SPC` prefix setup so that a subsequent press of `z` will activate a hydra body:

```
(general-define-key
 :states '(normal visual emacs)
 :prefix "SPC"
 :non-normal-prefix "C-SPC"

 "SPC" 'helm-M-x
 "z" '(hydra-zoom/body :which-key "zoom")
 )
```

I'd like to create a pink hydra so the hydra doesn't exit when I press an unbound key:

```
(defhydra hydra-zoom (:color pink)
  "
Zoom
----
_+_ in
_-_ out
_r_eset
"
  ("+" text-scale-increase)
  ("-" text-scale-decrease)
  ("r" (text-scale-adjust 0) :color blue)
  )
```

However, when I try to activate the hydra (`SPC z`) I get the following error:

`Wrong type argument: commandp, hydra-zoom/body`

This works fine when I use a normal red (or blue) hydra, but pink is causing some issues. I'm not sure what the implementation differences are (in either hydra or general) that is causing this colour type to behave differently to the others

I'm wondering if theres a specific way I should be setting up general keybindings to work with that colour type?

**Comment by noctuid** [comment]
The nature of the command (color of the hydra in this case) shouldn't matter. I can't replicate this on master (everything works fine). Are hydra, evil, and general up to date? Does this work?

```
(evil-define-key 'normal (current-global-map)
  (kbd "SPC z") 'hydra-zoom/body)
```

If that doesn't work, then it is not an issue with general.el. I'd try using `global-set-key` as well.

**Comment by sho-87** [comment]
This seems to be working now with the original code - I'm not sure what the issue was
