### ISSUE TITLE
Can't create key bindings using the Meta key along with Evil and use-package

### ISSUE THREAD

**Issue by ZzAntares** [noctuid/general.el#53]
Hello, I'm getting this error while trying to define keybindings that make use of the `Meta` key:

```
error: Key sequence M-k starts with non-prefix key ESC
```

Perhaps I'm not understanding well how to use general along with `evil`, I'm using the `:general` keyword for `use-package` like this:

```elisp
(use-package general
  :ensure t
  :config
  (setq general-default-states 'normal))

(use-package drag-stuff
  :ensure t
  :general
  ("M-k" #'drag-stuff-up
   "M-j" #'drag-stuff-down))
```

What I want is that `M-k` should be available globally without caring in which Evil mode I am.

I've tried some variants without success. Could you give me an intuition about why it's not working?

Thanks.

**Comment by noctuid** [comment]
That works fine for me. Does this also cause the problem?

```
(evil-define-key 'normal (current-global-map)
  (kbd "M-k") #'drag-stuff-up
  (kbd "M-j") #'drag-stuff-down)
```

If that results in the same error, then the problem is not with general.el. If it doesn't cause an error, try it outside of `use-package` and let me know if the error happens. The issue may be with another part of your config. You may want to try this with a minimal config or `emacs -Q`.

**Comment by ZzAntares** [comment]
Thanks for pointing me in the right direction, it turns out you're right using `evil-escape` seems to be the problem, so I've removed it in favor of the suggested `key-chord.el` for defining an escape sequence `kj`. But now my escape sequence does not work, I have this:

```elisp
(use-package key-chord
  :ensure t
  :general
  (:keymaps 'evil-insert-state-map
            (general-chord "kj") 'evil-normal-state))
```

I am using it correctly? pressing `kj` in insert state literally inserts `kj`, it doesn't escape at all. Could you help me?

I think we can close this since it's not an issue unless you explicitly want to make `general` usable with `evil-escape`. It that is the case, this is what I was using:

```elisp
(use-package evil-escape
  :after evil
  :diminish evil-escape-mode
  :ensure t
  :config
  (evil-escape-mode)
  (setq evil-escape-key-sequence "kj")
  (setq evil-escape-delay 0.3)
  :general
  ("ESC" 'evil-escape))
```

Thanks for everything!

**Comment by noctuid** [comment]
I don't have time to look into it right now (I can later when I get the chance), but it may it may be a problem the `:general` use-package keyword. Could you try that `general-chord` in a normal `general-define-key` or `define-key`?

**Comment by ZzAntares** [comment]
Hey, I'm sorry for the late reply, didn't have the time to check, but I finally did 😀 

Using `general-define-key` works but only if I use `:states` rather than `:keymaps`, i. e. This did not work:

```elisp
(general-define-key :keymaps 'evil-insert-state-map
                    (general-chord "kj") 'evil-normal-state)
```

But this does work:
```elisp
(general-define-key :states 'insert
                    (general-chord "kj") 'evil-normal-state)
```

However when using the `:general` keyword it doesn't work at all:
```elisp
(use-package key-chord
  :ensure t
  :config
  (key-chord-mode 1)
  :general
  (:states 'insert
	   (general-chord "kj") 'evil-normal-state))
```

I don't have any problem to place the `general-chord` in my `:config` section, but it would be nice that the `:general` keyword could also do this to improve mappings organization.

Thanks for the help, please do tell if you want me to open up a new issue. Thanks again!

**Comment by noctuid** [comment]
All of these are working as expected for me on master. Just to confirm, is your `key-chord-two-keys-delay ` high enough that you can consistently trigger the action?

As a side note, you can abbreviate `evil-insert-state-map` to `insert` (or in the future, just `i`) if you would like.

**Comment by ZzAntares** [comment]
Hi, the default `key-chord-two-keys-delay` is fine, just to test I did make it bigger to `0.5` but I have the same results. I don't know what could be the problem, but doing `emacs -Q --load minimal.el` the problem persisted, I also tested it on [docker `silex/emacs`](https://hub.docker.com/r/silex/emacs/) but doesn't work. Here is what I have:

```elisp
(setq package-enable-at-startup nil)

(setq package-archives '(("org" . "http://orgmode.org/elpa/")
                         ("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")
                         ("melpa-stable" . "http://stable.melpa.org/packages/")))

(package-initialize)

(when (not package-archive-contents)
      (package-refresh-contents))

(unless (package-installed-p 'use-package)
        (package-install 'use-package))

(use-package general
  :ensure t
  :config
  (setq general-default-states 'normal))

(use-package evil
  :ensure t
  :config
  (evil-mode))

(use-package key-chord
  :ensure t
  :config
  (key-chord-mode 1)
  (setq key-chord-two-keys-delay 0.5)
  :general
  (:states 'insert
           (general-chord "kj") 'evil-normal-state))
```

If this works for you, what could be the issue?

**Comment by noctuid** [comment]
Sorry for the late reply. I can replicate the issue with your minimal config, but I don't believe the problem is with general.el. If I examine the `(current-global-map)` after using the `:general` use-package keyword vs. the equivalent `evil-define-key` statement I see the same result. I'm not exactly sure what the cause of the problem is (maybe it has to do with the time of evaluation). Either way, in general you should not use `:states` like this; you should be using `:keymaps`. Looking back at why `:keymaps` isn't working, it is because you are setting a default state (which means you are not defining a key in the global evil insert state keymap but in the normal state auxiliary map for the global evil insert state keymap which is wrong). Please use `:keymaps` and remove `general-default-states` or change it to `general-default-keymaps`. If this does not fix the problem, I will reopen the issue.

**Comment by ZzAntares** [comment]
Hello again! Thanks for all your help, sadly I can't make it work, I have tested multiple variants of the keymaps and states settings, but with no luck. After re-reading the documentation it isn't clear to me how to achieve my settings, even after making the corrections you told me about:

```elisp
(setq package-enable-at-startup nil)

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")
                         ("melpa-stable" . "http://stable.melpa.org/packages/")))

(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(use-package general
             :ensure t)

(use-package evil
             :ensure t
             :config
             (evil-mode))

(use-package key-chord
             :ensure t
             :config
             (key-chord-mode 1)
             (setq key-chord-two-keys-delay 0.5)
             :general
             (:keymaps 'insert
                       (general-chord "kj") 'evil-normal-state))
```

Do you have a working example I can look at?

**Comment by noctuid** [comment]
I sincerely apologize for not noticing this sooner, but I'm pretty sure I figured it out. Using `:general` implies `:defer t` [see here](https://github.com/noctuid/general.el#use-package-keyword) just like use-packages `:bind` keyword. Normally packages will be loaded as soon as you use one of the bound keys, but the problem here is that key-chord needs to be loaded for chords to work at all. 

To fix this, you'll either want to immediately load key-chord with `:demand t` or do something like defer it for an idle time amount (e.g. `:defer 3`). Let me know if that fixes the problem for you.

**Comment by ZzAntares** [comment]
Thanks a lot! you nailed it, if finally works! However I can't say good bye before asking one last question :grin:.

how do you translate this kind of mappings to use with the `:general` keyword?

```elisp
(evil-define-key evil-magit-state magit-mode-map "?" 'evil-search-backward)
```

And when we should use states instead of keymaps? can both be used?

Thanks.

PD: I think we can close this since my problem is solved, and indeed it wasn't an issue with general but with my settings, sorry about that.

**Comment by noctuid** [comment]
Using `:states` basically means "use evil-define-key," so the argument to `:states` would be `'evil-magit-state`, and the argument to `:keymaps` would be `'magit-mode-map`. Using just `:states` will mean the default keymap is used (`'global` unless changed). You probably won't want to do this; the use case is currently limited to a workaround/method to prevent certain keys from being overridden in evil (see [here](https://github.com/noctuid/evil-guide#preventing-certain-keys-from-being-overridden)).

 Note that that there is also `general-evil-define-key` which takes the same arguments as `evil-define-key` and doesn't require the quoting.

**Comment by ZzAntares** [comment]
Thanks for all the help @noctuid! just wanted to say that this

```elisp
:general
(:states 'evil-magit-state
 :keymaps 'magit-mode-map
  	  "?" 'evil-search-backward
  	  "gr" 'magit-refresh)
```

didn't work, but this does:

```elisp
(general-evil-define-key evil-magit-state magit-mode-map "?" 'evil-search-backward)
```

So the `:general` keyword shouldn't be used for this mappings?

Thanks for all the help!

**Comment by noctuid** [comment]
Looks like a bug. I don't use `evil-magit`, but I I'll look into this when I get a chance. Could you post the rest of the use-package statement?

**Comment by ZzAntares** [comment]
Hi, sure, the full statement is this:

```elisp
(use-package evil-magit
  :ensure t
  :general
  (:states 'evil-magit-state
   :keymaps 'magit-mode-map
            "?" 'evil-search-backward))
```

Thanks in advance!

**Comment by noctuid** [comment]
The issue is that the state should be `evil-magit` not `evil-magit-state`. I didn't notice this the first time I looked at it.

**Comment by noctuid** [comment]
`evil-define-key` does automatically add `-state`, but your problem was actually that you are quoting `evil-magit-state`. In the first example, you are using it as a variable and defining in normal state (evil-magit doesn't add any new states).

**Comment by ZzAntares** [comment]
Hi, thanks for looking back into this, but if I understood you correctly then `evil-magit-state` is just a variable and not a vaild state? So I can't use that in the general's `:states` keyword?

I tried this and still didn't work:

```elisp
(use-package evil-magit
  :ensure t
  :after magit
  :init
  (add-hook 'git-commit-mode-hook 'evil-insert-state)
  :general
  (:states 'evil-magit
           :keymaps 'magit-mode-map
           "?" 'evil-search-backward))
```

**Comment by noctuid** [comment]
If it was an actual state, it would be `'evil-magit`. Since it is a variable, it should be `evil-magit-state`. In this case you could just use `'normal` as well.

**Comment by ZzAntares** [comment]
Thanks for pointing that @noctuid , I start to clear some misconceptions about `evil-magit` now.

I made this work:

```elisp
(use-package evil-magit
  :ensure t
  :after magit
  :init
  (add-hook 'git-commit-mode-hook 'evil-insert-state)
  :general
  (:states 'normal
           :keymaps magit-status-mode-map
           "?" 'evil-search-backward))
```

Now the keymap needs to be `magit-status-mode-map` but when doing this all bindings are gone when for example I'm in `magit-log-mode` because the map is now `magit-log-mode-map`.

So why does not work when I put `magit-mode-map` in the `:keymaps`?

Thanks again for all the help, I'm learning a ton =D. Sorry to bother again!

**Comment by noctuid** [comment]
I don't know if this is causing your specific issue, but keymap names should always be quoted with `:keymaps`.

**Comment by ZzAntares** [comment]
Sorry, that was a mistake of mine while pasting the snippet, the quote is there, but does not work either.

The thing is that `magit-status-mode-map` and `magit-log-mode-map` as `:keymaps` works but using `magit-mode-map` does not. Why?

**Comment by noctuid** [comment]
Does evil-magit bind `?`? My first guess would be that evil-magit is overriding your keybinding; try using `:config` instead. Normally if you have `?` bound globally in normal state, you wouldn't need to bind it in `magit-mode-map` at all.

If that doesn't fix it, does `general-define-key` by itself work?

**Comment by ZzAntares** [comment]
Yes thank you 😄  with `:config` and `general-define-key` works great. And no, evil-magit doesn't bind `?` magit does.

So I suppose `:general` keyword is not entirely equivalent after all, what's the difference then?, shouldn't work regardless of using `:general` vs `:config` + `general-define-key`?

Thanks for everything!

**Comment by noctuid** [comment]
The `:general` keyword is comparable to the `:bind` keyword. It immediately makes the keybindings (before the package is loaded), so it is possible for the package to overwrite those keybindings.
