### ISSUE TITLE
binding "TAB" in company-active-map to company-complete-selection problem

### ISSUE THREAD

**Issue by Zuffle** [noctuid/general.el#547]
Hello! Great package, but I am running into an issue I am puzzling over and I can't find any help online.

It might be similar to #176 

I am trying to bind "TAB" to `company-complete-selection` in `company-active-map` to no avail:

```emacs-lisp
(use-package company
  :after lsp-mode
  :hook (lsp-mode . company-mode)
  ;; This works
  ;; :bind (:map company-active-map
  ;;        ("<tab>" . company-complete-selection))
  ;;       (:map lsp-mode-map
  ;;        ("<tab>" . company-indent-or-complete-common))
  :general
  ;; this is the part that doesn't work
  (:keymaps 'company-active-map
	    ;; tried to set to nil just in case
            ;; "TAB" 'nil
            "TAB" 'company-complete-selection)
  (:keymaps 'lsp-mode-map
        "TAB" 'company-indent-or-complete-common)
  :config
  (gsetq company-minimum-prefix-length 1
	 company-idle-delay 0.0)
  ;; This works
  ;; (general-def
  ;;   :keymaps 'company-mode-map
  ;;   "TAB" 'company-complete-selection
  ;;   )
  )

``` 
The most confusing part for me is that when I check `company-active-keymap` the binding seems to be there:

![image](https://user-images.githubusercontent.com/8173816/234763626-4d3d4dd6-fb09-4eb7-9793-d35d7154ab83.png)

I know I could just not use the `:general` keyword if the other methods worked but I wanted to figure out why this wasn't working. I am thinking that it is something to do with when `company-active-map` is loaded (since it could be a buffer local keymap that isn't loaded until `company-mode` is on) but I haven't seen anyone else having this specific issue. 

See anything wrong with the way I am using `:general`?

**Comment by noctuid** [comment]
`TAB` and `<tab>` are different keys (see [tab key](https://www.emacswiki.org/emacs/TabKey)).  I think you want to bind `<tab>` not `TAB` here (or unbind it first).

**Comment by Zuffle** [comment]
That was it! Thanks a bunch! Great work on this
