### ISSUE TITLE
How to use custom definer in use-package definition?

### ISSUE THREAD

**Issue by IllustratedMan-code** [noctuid/general.el#549]
Say I want to use a custom definer in a `:general` block like so:

```elisp
(use-package general
    :config
    (general-create-definer leader :states '(normal) :prefix "SPC"))
  
 (use-package counsel 
    :general (leader "f" 'counsel-find-file))
```

When I do this, the binding is simply not created. I *can* however run the `leader` macro I created in the freshly started emacs.

Am I doing something wrong, or is this not supposed to work?

**Comment by IllustratedMan-code** [comment]
In fact, I can't get any definer to work in any capacity.

This bit of code fails with (invalid-function my-leader-def)
```elisp
  (use-package general
        :config
        (general-create-definer my-leader-def
        :prefix "C-c")

        (my-leader-def
        "a" 'org-agenda
        "b" 'counsel-bookmark
        "c" 'org-capture))

```

**Comment by noctuid** [comment]
I suspect there is a problem with your use-package config or config elsewhere.  Can you provide a minimal init reproduction?

**Comment by IllustratedMan-code** [comment]
I think I may have found the issue. It seems to have something to do with the fact that I am using a `default.el` instead of the normal init directory. I also use nix, so that may be a factor.

You might be able to reproduce with the following `default.el`
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(eval-when-compile (require 'use-package))
(require 'bind-key)

(use-package general
:ensure t
:config
(general-create-definer leader! :prefix "SPC")
(leader! "a" 'org-agenda))
```

If I start emacs with no config and `M-x load-file RET default.el` I can't reproduce this issue. It is only when the default.el is put in the standard search path for libraries in Emacs, see the [manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html).

If you happen to use nix, my derivation of emacs looks like this: 
```nix
            (pkgs.emacsWithPackagesFromUsePackage
              {
                package = pkgs.emacsUnstable; #Emacs 29
                config = ./default.el;
                defaultInitFile= true;
                alwaysEnsure = false;
                extraEmacsPackages = epkgs: [
                  epkgs.use-package
                ];
              });
```

**Comment by Kintaro** [comment]
I also just stumbled upon this. I can report to have the exact same issue. Is there any solution to it?

**Comment by gustavomedeiross** [comment]
I also have exactly the same issue, and I'm also using emacs-overlay. @IllustratedMan-code Did you figure out a way to fix this issue?

**Comment by IllustratedMan-code** [comment]
I did not, though I haven't looked at it in a while. I ended up just working around it by using the normal init directory for emacs

**Comment by noctuid** [comment]
> specifically general-create-definer is broken

I don't think so.  That `:after (evil which-key)` is not recommended and is likely the issue if you are not loading evil/which-key immediately, and if you are, it's pointless.  If that's not the issue, please open a new issue with a minimal config to reproduce.

**Comment by Thundertheidiot** [comment]
Apologies for that, this definition was pasted from my original config, and that was stolen from somewhere else, but i am pretty sure that i didn't do that when i tested this with a very minimal config, i'll retest that tomorrlw though, just in case i was being an idiot.
Also evil and which-key have :demand t, so they should be loaded.

**Comment by starptr** [comment]
I'm also seeing this behavior where `general-create-definer` doesn't seem to define the function. Like others, I'm using emacs-overlay's `emacsWithPackagesFromUsePackage` function, with the `defaultInitFile = true` parameter.
