### ISSUE TITLE
Incompatibility with spacemacs?

### ISSUE THREAD

**Issue by rgrinberg** [noctuid/general.el#55]
So I have this bit:

```
  (general-define-key
   :states '(normal)
   :keymaps '(messages-buffer-mode-map prodigy-view-mode-map prodigy-mode-map)
   "q" #'quit-window)

  (general-define-key
   :states '(normal)
   :keymaps '(prodigy-mode-map)
   ";" #'prodigy-display-process
   "<RET>" #'prodigy-display-process)
```

And strangely enough the `q` bindings succeeds while the `;`/`<RET>` binding fails. When I do `general-describe-keybindings` all the keys are there. But it's not quite working.

Could it be because of this line in spacemacs:

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/prodigy/packages.el#L14-L33

I'm not quite sure what is wrong and how to debug.

**Comment by noctuid** [comment]
I'm not familiar with `evilified-state`, but it seems that it changes the default state for a minor mode, and you're binding keys in `normal` not `evilified` state. If you don't want to use the `evilfied` state, run `(evil-set-initial-state 'prodigy-mode 'normal)` afterwards. If you never want to use the `evilfied` state, you could also override the relevant functions to `#'ignore`.

If you do want to use the `evilfied` state, please use that in `:states` and let me know if you encounter in problems.

**Comment by rgrinberg** [comment]
Thanks, adding `evilified` to my list of states in general is indeed what I wanted.

Given that spacemacs very popular and general is extremely good, does it make sense to leave a note for spacemacs users in the manual?

**Comment by noctuid** [comment]
It would make sense to add this information to the spacemacs documentation if it isn't there already, but that information isn't relevant to general.el specifically.
