### ISSUE TITLE
Error (use-package): general :config: Key sequence SPC z starts with non-prefix key SPC

### ISSUE THREAD

**Issue by gigavinyl** [noctuid/general.el#57]
I just started using general but I'm getting the error: `Error (use-package): general :config: Key sequence SPC z starts with non-prefix key SPC`.
The relevant part of my `init.el` (I'm only binding one thing so far so I can make sure I get it working) is:
```emacs-lisp
(use-package general
  :ensure t
  :config
  (setq general-default-prefix "SPC")
  (general-define-key "z" 'find-file))

```

**Comment by noctuid** [comment]
In emacs, you need to unbind keys before you can use them as prefix keys. Are you trying to use `SPC` as a prefix for evil? If so, you will need to use `:states`.

**Comment by pmagwene** [comment]
I'm running into a similar issue, even when I unbind the key before hand:

```
(general-define-key "C-'" nil)
(general-define-key :prefix-map 'my-general-prefix-map
                    :prefix-command 'my-general-prefix-command
                    :prefix "C-'"
                    "x" 'execute-extended-command)
```

The above code returns the error `error: Key sequence C - ' starts with non-prefix key C`

**Comment by noctuid** [comment]
@pmagwene Thanks for bringing that to my attention; that is an unrelated bug (it was trying to bind the letter `C` which was a non-prefix key not `C-'`). Prefixes were being bound without `(kbd)` even when `general-implicit-kbd` was used; this is fixed now. If you have any other problems, please open a new issue.

**Comment by noctuid** [comment]
I'm going to close this now. @gigavinyl If you have any other problems or questions, feel free to open a new issue.

**Comment by vyp** [comment]
@noctuid Hmm it seems like I cannot use `SPC` as a prefix key at all. I'm on the `buttercup` branch, b516a34. For example, I tried the following but still get the same error as gigavinyl (when pressing `"SPC l"`):

``` elisp
(setq my/leader "SPC")
(general-define-key my/leader nil)
(general-def
 'motion
 :prefix my/leader
 "l" 'buffers)
```

**Comment by noctuid** [comment]
If you'd rather just use one `general-def`, you can also just add `"" nil`.
