### ISSUE TITLE
Modify keymaps such as `ediff-mode-map' which loads at a later stage

### ISSUE THREAD

**Issue by terlar** [noctuid/general.el#59]
Is there a recommended keymaps such as this, I searched and read through the documentation, but couldn't find any example like that.

Currently I do like this:

```
(add-hook 'ediff-keymap-setup-hook
          #'(lambda ()
              (general-define-key
               :keymaps 'ediff-mode-map
               "d" '(ediff-copy-both-to-C      :which-key "Copy both to C")
               "j" '(ediff-next-difference     :which-key "Next difference")
               "k" '(ediff-previous-difference :which-key "Previous difference"))))
```

But it would be nice not to have the hook wrapping, if general-define-key could handle it somehow. If I define the keys directly on the keymap they don't seem to take affect, probably due to the way ediff sets up it's own keymaps.

**Comment by noctuid** [comment]
It looks like `ediff-mode-map` is a local keymap that is reset and set up every time an ediff command is run. There is no way around this; you have to use a hook. I agree this isn't ideal. I'd suggest making a bug report and asking that they add a keymap that the user can make keybindings in that won't be overriden.

**Comment by terlar** [comment]
Thanks for the suggestion, that sounds reasonable
