### ISSUE TITLE
Weird which-key behavior in buttercup branch

### ISSUE THREAD

**Issue by therockmandolinist** [noctuid/general.el#62]
My config:

```emacs-lisp
(general-evil-setup t t)

(general-create-definer
 diego/leader-keys
 :states '(emacs normal visual motion insert)
 :non-normal-prefix "C-SPC"
 :prefix "SPC")

```
I've got some bindings under "a", for example:
```emacs-lisp
(diego/leader-keys "ax" 'xkcd)
```
But when I try to add a prefix key like this (in a separate declaration, because of how i want to organize my config currently):
```
(diego/leader-keys
 "a" '(:ignore t :which-key "applications"))
```
_Every_ command turns into "applications" under which-key, even non-prefix ones. If I add more which key replacements similar to above, everything gets named whatever the last one was. 

I don't think I was seeing this behavior on master.

**Comment by noctuid** [comment]
The defaults weren't correctly available for the which-key options, so before the mentioned commit, you would have to manually specify them. Please try now, and thanks for pointing this out.

**Comment by therockmandolinist** [comment]
That seemed to fix it, thanks!
