### ISSUE TITLE
[Feature request] Allow :major-modes to be a list of major modes.

### ISSUE THREAD

**Issue by dieggsy** [noctuid/general.el#63]
This might be too specific, but one might have similar editing commands for multiple modes (for example sexp evaling/editing commands for different lisp modes), so it would be cool to be able to do which key major-mode replacements for a list, kinda like this:
```emacs-lisp
(d/mode-leader-keys
 :keymaps '(emacs-lisp-mode-map lisp-interaction-mode-map)
 :major-mode '(emacs-lisp-mode lisp-interaction-mode)
 "e" '(:ignore t :wk "eval")
 "eb" 'd/eval-buffer
 "ef" 'eval-defun
 "er" 'eval-region
 "eR" 'd/eval-and-replace
 "es" 'd/eval-surrounding-sexp
 "el" 'eval-last-sexp
 "p"  '(:ignore t :wk "pp")
 "pm" 'd/pp-macroexpand-surrounding-sexp
 "ps" 'd/pp-eval-surrounding-sexp)
```

**Comment by noctuid** [comment]
This would really only be useful if you ended up having the same exact key sequence bound to the same exact command in different major modes and wanted their descriptions to be different (e.g. "eval elisp" vs. "eval python"), so it may not be often that this is needed. That said, thanks for the suggestion; I think this is probably how I should have implemented it originally. What I'll probably do is rename `:major-mode` to `:major-modes` for consistency and allow for the following values:

List value options:
- Nil (the keymap does not correspond to a major mode map); nil would be assumed if the list length does not match the keymap length
- the major mode name
- some special value special value to indicate that the major mode name is the map name without `-map`

There would also be a special value (e.g. `:major-modes t) that would automatically try dropping `-map` from all keymaps.

**Comment by therockmandolinist** [comment]
Ok, that seems reasonable.

**Comment by noctuid** [comment]
This is now implemented on the development branch (see the readme there for additional details; generally you can just use `:major-modes t`). I haven't had time to add tests yet but manually tested it for a few cases. Let me know if you try it and find any issues.

**Comment by noctuid** [comment]
The development branch has been merged.

**Comment by dieggsy** [comment]
Thanks!
