### ISSUE TITLE
leader key mapping

### ISSUE THREAD

**Issue by myimages** [noctuid/general.el#64]
Hi , and thank you for this package , I am using it now, and I like the configuration that looks like vim.

however I am having a little issue with some mappings.

```elisp
(general-evil-setup t)
(setq general-default-prefix ",")
(nmap "e" 'helm-projectile-switch-project
      "cd" 'cd ;; this one
      "c" 'iwb ;; and this
      "rn" 'rename-file-and-buffer)
```

is there a work around ?

I apologize if this is not  general.el issue but since it seems the most up to date evil leader package I would like to stick to it and I am sure somebody else had this issue before.

**Comment by noctuid** [comment]
This is not possible by default in emacs; you cannot bind a prefix key to a command. For a workaround, see [this part of the README](https://github.com/noctuid/general.el#mapping-under-non-prefix-keys), but be aware that this is still a work in progress (e.g. #45 and #50).
