### ISSUE TITLE
:predicate bindings don't seem to work

### ISSUE THREAD

**Issue by rgrinberg** [noctuid/general.el#66]
Here's an attempt at a predicate binding that fails: 

```emacs-lisp
  (defun rg/is-http-response ()
    (string= (buffer-name) "*HTTP Response*"))

  (general-define-key
   :states '(normal evilified)
   :keymaps 'local
   :predicate '(rg/is-http-response)
   "q" #'quit-window)
```

I'm not really sure why, but it's probably something simple and silly. Would appreciate some help.

**Comment by noctuid** [comment]
Are you using the `buttercup` branch? There is a problem that I need to fix with local evil keybindings that is probably causing this problem (they aren't being defined in the normal way and don't have high enough precedence). Sorry about this.

**Comment by noctuid** [comment]
It should be fixed now.

**Comment by rgrinberg** [comment]
Did this land in melpa yet? This still doesn't work for me.

**Comment by vyp** [comment]
@rgrinberg No because the fix is only in the buttercup branch for now, so try the buttercup branch in the meantime.

**Comment by noctuid** [comment]
@rgrinberg Are you having this problem on master then? The specific issue I fixed on the buttercup branch is not on the master branch. I'll have too look into it further. Sorry for the inconvenience; I'll fix it as soon as I have some free time.

**Comment by noctuid** [comment]
The development branch has been merged.
