### ISSUE TITLE
[feature request] Sort bindings listed in general-describe-bindings?

### ISSUE THREAD

**Issue by rieje** [noctuid/general.el#68]
It seems that the current order of keybindings listed is the order in init.el (from top to bottom). I think it makes more sense for `general-describe-bindings` to sort keys alphabetically (either as a default or as an option) so it's easy for the user to parse through the keybindings and determine at a glance which keys are free of use and can be assigned to a binding (of course you can manually check each key individually in Emacs but when a user wants to assign a function to a key, he wants to know most/all available options to find the one that's ideal, rather than test which keys he wants whether or not it's already used).

Of course a workaround is to alphabetically sort them in the config files, but with the use of `use-package` and other methods of encapsulating package-related settings, this is not possible (e.g. I want to use a leader key for different packages and I use bind it throughout my config file in the relevant `use-package` declaration.

**Comment by noctuid** [comment]
Users generally group keybindings by package or theme, so I think that definition order makes the most sense as a default. `general-describe-keybindings` is not really the right tool to determine what keys are free (for one, it only shows user keybindings). Something like [free-keys](https://github.com/Fuco1/free-keys) is much better suited for this purpose.

That said I'm planning on making `general-describe-keybindings` more customizable in the future and will probably either include alphabetical sorting as an option or make it easily possible.

**Comment by noctuid** [comment]
This is now possible. [Here](https://github.com/noctuid/general.el#displaying-keybindings) is the relevant section of the readme. It now has examples for doing alphabetical sorting.
