### ISSUE TITLE
[Question] "Standard" way to override evil bindings?

### ISSUE THREAD

**Issue by dieggsy** [noctuid/general.el#73]
I had previously been using `(general-evil-setup t t)`, but I realized I didn't like how some of those bindings lingered, even when doing a `evil-make-overriding-map`. I also realized the readme says that using `:keymaps` instead of `:states` is preferable or "standard", so I switched to this method, which I'm liking better. This solves some of my problems, but I'm not sure of the recommended how to solve a new problem: I'd like to override certain keybindings such as `gk` in certain modes, so I was doing an
```emacs-lisp
;; In general config
(general-evil-setup t)
;; In :general for use-package org
(nmap :keymaps 'org-mode-map
  "gk" 'org-backward-heading-same-level)
```
But these bindings are not taking effect like they were when I was preferring the `:states` method. Any input on this?

**Comment by dieggsy** [comment]
Huh. I may have misunderstood. Is nmap in the above case only good for "global" bindings? That is, is using states _necessary_ when `:keymaps` is specified?

**Comment by noctuid** [comment]
Yes, all nmap does by default is to set the default `:keymaps` (though this may change in the future to work for your example; see #37). 

I'm going to start recommending using `general-def` for everything once it is in master. A global keybinding looks like `(general-def 'normal ...)` (or `(general-def 'n ...')`; single quote is optional), and your keybinding would look like `(general-def 'normal org-mode-map "gk"...)` .
