### ISSUE TITLE
which-key integration - attaching replacements to prefixes/infixes

### ISSUE THREAD

**Issue by tummychow** [noctuid/general.el#77]
First off, thank you for general; this package is sweet.

In my [emacs configuration](https://github.com/tummychow/emacs/blob/master/init.org#evil), I have a prefix tree `SPC d` for desktop-related commands. If I type `SPC` and wait for the which-key popup, it will say `d -> +prefix`. I want it to say `d -> +desktops` instead.

I can do this with `(which-key-add-key-based-replacements "SPC d" "desktops")`, but then I have to add another replacement for `M-SPC d`, and so on. I would prefer to use general's which-key integration for this, but it doesn't appear to support my intended use case. Basically I want this piece of elisp:

```
(private/with-leader
 :infix "d"
 :wk "desktops"
 "h" 'split-window-horizontally
 ...)
```

to result in "desktops" as a replacement for `SPC d`. I'm also open to other interfaces for implementing this feature.

**Comment by noctuid** [comment]
`:wk` is not a global keyword. If you want to create an extended definition for the prefixes, you should use `""` (e.g. `"" '(:ignore t :wk "desktops")'`). Does that work for you?

**Comment by tummychow** [comment]
Hmm, I'm trying:

```
      (private/with-leader
       :infix "h"
       "" '(:wk "help"
            :ignore t)
       "h" 'help-for-help
       "f" 'describe-function
       ...)
```

and the which-key prompt still says `h -> +prefix`.

![maim-2017-10-31-21 03 01](https://user-images.githubusercontent.com/4285049/32255521-e863f6be-be7e-11e7-82dc-d9a4561dc9a9.png)

**Comment by noctuid** [comment]
That exact example works for me. Do you have the latest version of general?

**Comment by tummychow** [comment]
:+1:
