### ISSUE TITLE
Question: Give evil prefix even higher precedence

### ISSUE THREAD

**Issue by auwsmit** [noctuid/general.el#81]
I'm trying out this relatively new package, [evil-special-modes](https://github.com/Ambrevar/evil-special-modes), that's attempting to standardize evil-bindings in modes that evil doesn't cover, or that there aren't already popular packages for (like evil-magit, evil-org, etc.).

I have `SPC` as my prefix binding leader key via general:

    (general-define-key
     :states '(normal motion emacs)
     :prefix "SPC"
     ;;etc.
     )

And evil-special-modes will overwrite my binding with `evil-define-key`:

    (evil-define-key 'motion help-mode-map
      (kbd "SPC") 'scroll-up-command)

Is there any way to make sure that specific custom bindings of mine, like my "leader" bindings, will always be there despite something like evil-special-modes being applied afterward?

**Comment by noctuid** [comment]
Yes, you can do this using `evil-make-intercept-map`. I'll post an example a little later.

**Comment by noctuid** [comment]
You can use `evil-make-intercept-map` manually, but with the latest commit of general, you can also do this without extra setup:
```
(general-override-mode)
(general-define-key
 :states ...
 :keymaps 'override
...)
```

**Comment by auwsmit** [comment]
It works! Thanks.
