### ISSUE TITLE
Feature Request: Key to create new map

### ISSUE THREAD

**Issue by justbur** [noctuid/general.el#83]
I've been playing with `general-define-key` and I like it so far, but there's one thing that I like to do in my config that I think could be easier. I'd like to simultaneously create a `leader-map` full of leader bindings and bind it. I thought `:prefix-map` would serve this purpose, but it's unclear how to use it for that purpose. 

To be specific, instead of 
```elisp
(setq leader-map (make-sparse-keymap))
(general-define-key
 :states 'normal
 :prefix "SPC"
 " " leader-map)
(general-define-key
 :states nil
 :prefix nil
 :keymaps 'leader-map
 " " 'counsel-M-x
 "'" 'eshell)
```

I'd like to be able to do something like
```elisp
(general-define-key
 :states 'normal
 :prefix "SPC"
 :make-keymap 'leader-map
 " " 'counsel-M-x
 "'" 'eshell)
```

The reason is I can then easily add leader bindings where they might be shadowed by a minor-mode by binding a key to `leader-map`. Or maybe you have a different solution to this problem?

**Comment by noctuid** [comment]
Right now general.el only creates prefix keymaps using `define-prefix-command`. `:prefix-map` and `:prefix-name` only have an effect when `:prefix-command` is specified. If you replace `:make-keymap` with `:prefix-command`, your example should work.

If you think it would be useful to have `:prefix-map` work by itself (either because you don't want to the prefix command or because it would be more intuitive), I could do that.

**Comment by justbur** [comment]
Hm, I'm fine with having to specify both, although I think to the average user just being able to specify a map would be useful. 

I'm still having some trouble though. This doesn't appear to do what I expect.
```elisp
(general-define-key
 :states 'normal
 :prefix "SPC"
 :prefix-command 'leader-cmd
 :prefix-map 'leader-map
 " " 'counsel-M-x
 "'" 'eshell) 
```
I'd like `leader-map` to be bound to `SPC` in `evil-normal-state-map` and `counsel-M-x` to be bound to `SPC` in `leader-map`. Does that make sense?

**Comment by noctuid** [comment]
If you don't mind the command and map being named the same, you can just use `:prefix-command`. I'll change it so that specifying just `:prefix-map` works when I get the chance though.

Looking at the example now, `" "` should be `"SPC"`.

**Comment by justbur** [comment]
>If you don't mind the command and map being named the same, you can just use :prefix-command. I'll change it so that specifying just :prefix-map works when I get the chance though.

Great thanks

>Looking at the example now, " " should be "SPC".

Oh, that works now. I see now. It's because you apply `kbd` to every key.

**Comment by noctuid** [comment]
It should work now.
