### ISSUE TITLE
using :definer with the :general keyword. How exactly?

### ISSUE THREAD

**Issue by moesasji** [noctuid/general.el#84]
When I try to override the key-bindings of magit using :general I have magit-status failing to load on the first attempt with a non-prefix error message. However it is consistently working fine on the second attempt with all keybindings working as expected.

This must be related to the evil-bug mentioned at the end of your readme. Unfortunately having read this information and the links I'm still puzzled on how to use the :definer 'minor-mode to fix this. 

Could you clarify how to correctly incorporate the use of the :definer option in the code below so that the package loads correctly on the first attempt?

```
(use-package magit
   :ensure t
  :commands magit-status
  :general
  ;; enable navigation with n and e (line-based)
  (:keymaps '(magit-mode-map
              magit-status-mode-map
              magit-diff-mode-map)
            "n" 'evil-next-visual-line
            "e" 'evil-previous-visual-line
            "C-n" 'magit-section-forward
            "C-e" 'magit-section-backward
            "gn" 'magit-section-forward-sibling
            "ge" 'magit-section-backward-sibling
            "gr" 'magit-refresh
            "gR" 'magit-refresh-all
            "/" 'evil-search-forward
            "h" 'evil-search-next
            "H" 'evil-search-previous
            "C-u" 'evil-scroll-up
            "C-d" 'evil-scroll-down)
  :config
  (add-hook 'git-commit-mode-hook 'evil-insert-state))
```

**Comment by noctuid** [comment]
No evil keybindings are made, so that can't be the issue. `g` is bound by default to `magit-refresh`, so you'll have to unbind it (`"g" nil`) first. I don't know why it works the second time. Instead of that `add-hook`, I'd also recommend using `(evil-set-intiial-state 'git-commit-mode 'insert)`.

I'm considering adding an option to automatically unbind keys in situations like this. If you'd like this feature, please reply or 👍 on #85.

**Comment by moesasji** [comment]
1) Indeed setting '"g" nil' fixes my problem; For some reason I wrongly tried '"g" '(nil)" earlier. Thanks for the pointer on both!

2) I struggle to get my head around the complexities of evil + keybindings, so not really in a position to know whether a feature to automatically unbind would be beneficial. A FAQ on recommended practices and common issues might do the job equally well.
