### ISSUE TITLE
verify if evil's pull 976 can simplify code

### ISSUE THREAD

**Issue by ninrod** [noctuid/general.el#86]
@noctuid Just bringing pull https://github.com/emacs-evil/evil/pull/976 to your attention because maybe this can provide some simplification for general.el.

**Comment by noctuid** [comment]
Thanks for pointing that out. I don't think it will do anything to simplify the implementation. With regards to #85, I may just start passing `'global` directly to `evil-define-key` instead of warning though (which would make `:states 'normal` alone the same as `:keymaps 'normal` alone).
