### ISSUE TITLE
Can't override evil movement keys on some modes

### ISSUE THREAD

**Issue by ZzAntares** [noctuid/general.el#89]
Hello!, I'm having a little trouble, you see, since I updated last weekend some keybindings stopped working, as an example currently I'm being unable to make this key bindings work in `dired-mode-map`.

```elisp
(use-package dired
  :general
  (:states 'normal :keymaps 'dired-mode-map
           "h" 'dired-previous-line
           "k" 'dired-next-line))
```

It seems that I can't override evil movement keys because if I put another key binding not involved with `hjkl` then it works. Why is that? It was working fine a couple days ago. How should I rewrite the key bindings to make it work again?

Thanks for the help!

- Emacs version: `GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83) of 2017-10-06`
- Evil version: `Evil version evil-git-125f43b`

**Comment by noctuid** [comment]
I'm surprised this ever worked. I'd recommend [undoing the overriding keymap](https://github.com/noctuid/evil-guide#undo-overridingintercept-maps) that `evil-integration` creates for `dired-mode-map`.

**Comment by ZzAntares** [comment]
I couldn't make it work, it works with other keys but not with `k` or `h`. Would you mind sharing your `.emacs.d`? Looked for it in your dotfiles repo but I didn't see any general.el usage, I think I need to see how others use general.

Thanks.

**Comment by noctuid** [comment]
What did you add to your config? Did you try `(define-key dired-mode-map [override-state] nil)` after loading evil?

**Comment by ZzAntares** [comment]
I tried before/after loading dired/evil, the only configuration that doesn't give an error is when I added it to the `:config` section of the `(use-package dired ...`, if I add it to the `:config` in `(use-package evil ...` or somewhere else I get:

```
Error (use-package): evil/:config: Symbol’s value as variable is void: dired-mode-map
```

I suppose it's because dired loading is deferred, if I don't do this my emacs takes ages to start =S.

If I evaluate `(define-key dired-mode-map [override-state] nil)` manually, it has no effect, the bindings related to `hjkl` still didn't work.

**Comment by dieggsy** [comment]
I've got 
```emacs-lisp
(use-package dired
  ;; ... (truncated)
  :config
  (nmap dired-mode-map
    ;; ... (truncated)
    "h" 'dired-up-directory
    "l" 'dired-open-file)
```
In my init.el, which seems to be working fine

**Comment by ZzAntares** [comment]
mmm for me that doesn't work (no error, just it has no effect), I'm already looking to your config to see if I missing something.

If I use this it works fine:

```elisp
(use-package dired
  ;; ... (truncated)
  :config
  (evil-define-key 'normal dired-mode-map "k" 'dired-next-line))
```

But if I use `general-evil-define-key` it doesn't work right away, if I explicitly evaluate the expression then it works, and finally using `:general` keyword will not work (only with `hjkl`)

**Comment by noctuid** [comment]
Yeah my bad, this has absolutely nothing to do with the overriding map (which only affects the global keymap). I don't know why I was thinking you were talking about global keybindings. I'll look into this.

**Comment by noctuid** [comment]
This is because of evil-integration though. It seems that the `evil-add-hjkl-bindings` is being run after the general key definition.

**Comment by noctuid** [comment]
`evil-integration`'s keybindings are made afterwards because of the `eval-after-load`. There's nothing general can do about this. You need to use `with-eval-after-load`/`:config`. For example, this works fine for me:
```
(use-package dired
  :config
  (general-def 'normal dired-mode-map
    "h" 'dired-previous-line))
```
