### ISSUE TITLE
The recent prefix-map changes breaks key bindings

### ISSUE THREAD

**Issue by jschaf** [noctuid/general.el#90]
All of my keybindings stopped working with https://github.com/noctuid/general.el/commit/306cfed70a583ae49bc9191200542ecfa7870021.  I did a `git bisect` to find that commit.

By stopped working, I mean the key is listed as undefined when pressed.

I'm having trouble getting it down to a minimal reproducible case.  Here's kind of what my config does:

```elisp
;; /tmp/general-bug.el
;; Run with:
;; emacs -Q --debug-init -l /tmp/general-bug.el

(add-to-list 'load-path "~/prog/general.el")
(add-to-list 'load-path "~/.emacs.d/elpa/evil-20171210.501")
(require 'general)

(defvar abn-leader-map (make-sparse-keymap))

(general-create-definer abn/define-leader-keys :keymaps 'abn-leader-map)

(defvar abn-leader-key "SPC")
;; Set keybindings in all evil modes to invoke `abn-leader-map'.
(general-define-key
 :states '(normal insert visual motion emacs)
 :prefix abn-leader-key
 :non-normal-prefix "M-m"
 :prefix-command 'abn-cmds
 :prefix-map 'abn-leader-map)

(abn/define-leader-keys
 "u" #'universal-argument)

(require 'evil)
(evil-mode)
```

The real config is at [jschaf/dotfiles:core-keybindings.el](https://github.com/jschaf/dotfiles/blob/master/emacs/core/abn-core-keybindings.el)

**Comment by noctuid** [comment]
You should remove `(defvar abn-leader-map (make-sparse-keymap))`. General.el already creates the prefix keymaps and prefix commands and will not redefine them when they already exist (so as to not clobber previously created keybindings). In this case, because the prefix keymap already exists, general.el does not create the prefix command.

**Comment by noctuid** [comment]
Thanks for this issue as I also noticed an unrelated issue with the new `:prefix-map` functionality (when `:prefix-command` is not specified). Also, sorry for the inconvenience. If you think a alternate behavior would be more desirable or think the documentation could be improved with regards to this issue, let me know.
