### ISSUE TITLE
use-package :general integration completely broken

### ISSUE THREAD

**Issue by wbolster** [noctuid/general.el#91]
hi,

first of all, thanks for working on this package. much appreciated.

that said... ;)

it seems `general.el` is completely broken using the current `use-package`.

when i start emacs without any flags, it just hangs, eats 100% cpu and i see memory usage increase steadily (until i kill the process).

when i start emacs with `--debug-init` i see this instead (no hanging with 100% cpu in this case):

```
Debugger entered--Lisp error: (error "use-package: Unrecognized keyword: :general")
  signal(error ("use-package: Unrecognized keyword: :general"))
  error("use-package: %s" "Unrecognized keyword: :general")
  use-package-normalize-plist(helpful (:general ("C-h f" (quote helpful-function)) ("C-h v" (quote helpful-variable))) nil use-package-merge-keys)
[...]
```

i replaced the `general.el` file installed from melpa with the one from commit ade91c6dbb42ee9d389c828d19a9bc6b7ec2bcab in this repo so it seems the current `master` (as of the time of writing) exhibits the problem.

here is a pretty minimal `init.el` that causes the problem for me:

``` elisp
(setq
 package-archives
 '(("melpa" . "https://melpa.org/packages/")
   ("melpa-stable" . "https://stable.melpa.org/packages/")
   ("gnu" . "https://elpa.gnu.org/packages/"))
 package-enable-at-startup nil)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(setq use-package-always-ensure t)

(use-package general)

(use-package helpful
  :general
  ("C-h f" 'helpful-function)
  ("C-h v" 'helpful-variable))
```

**Comment by dieggsy** [comment]
Latest use-package and general are working fine for me - I am using both straight from git though, perhaps you need to wait for one to be updated on melpa

**Comment by wbolster** [comment]
hmmm, seems a missing `(require 'use-package)` in that minimal `init.el` was causing issues. putting that before any `(use-package ...)` call seems to fix the issue for me.

not sure how this ever worked before for me. apparently i never had that `(require)` in my `.init.el`. now i do. :)

**Comment by raxod502** [comment]
@noctuid This is a bug in `general`. [This line in `general.el`](https://github.com/noctuid/general.el/blob/32a94e066fe2d7bbdc70e7f06a59f1eaa06e4e55/general.el#L1917) should read `(with-eval-after-load 'use-package-core` instead of `(with-eval-after-load 'use-package`.

**Comment by glumanda99** [comment]
I've the same bug. I had to make sure `general.el` will be loaded before any other package using the `:general` keyword.

**Comment by noctuid** [comment]
Unless you are having some other problem, that's not a bug. You need to load general before using its use-package keyword. There's no way for use-package to know what the `:general` keyword is otherwise.

**Comment by glumanda99** [comment]
@noctuid What about @raxod502's answer?

**Comment by dieggsy** [comment]
@glumanda99 your problem and @wbolster's problem are not the same. the original issue was a bug, yours is just a result of how elisp necessarily works.

**Comment by ajrouvoet** [comment]
It is unclear to me how this is fixed/what the solution is.
I just set up the following configuration, which currently fails with the error in this issue:

```
(package-initialize)

(eval-when-compile
  (require 'use-package)
  )

(use-package evil
  :config
  (evil-mode 1)

  :ensure t)

(use-package general
	:ensure t
  :config
  (general-evil-setup t)
  (define-key evil-motion-state-map " " nil)
  )

(use-package ranger
	:ensure t
	:general
  (nmap
	 :which-key "ranger"
	 :prefix "SPC"
	 "ar" 'ranger
	 "ad" 'deer
	 )
	)
```

**Comment by noctuid** [comment]
To clarify, is general being loaded before the ranger use-package statement or is there an implicit `:defer t`?

**Comment by ajrouvoet** [comment]
I'm new to most of this, so I'm not sure how to tell for sure. But adding ":demand" to general does not resolve the problem. AFAIK that should force immediate loading of general.
