### ISSUE TITLE
major mode keybindings leaking

### ISSUE THREAD

**Issue by BrianHicks** [noctuid/general.el#92]
Hi! I'm trying to set up general to use `<SPC>` as a prefix for global keybindings, and `,` as a prefix for major mode keybindings (like localleader in vim.) I think I've almost got it, but need some help!

Basically, the issue is that prior to loading a mode, the `,` does not work. This is as expected. But after loading it, the `,` bindings are available in all buffers. This isn't great! How can I constrain these keybindings to only work in their respective major modes?

Here's what I've got so far:

```elisp
(use-package general
  :init
  (general-evil-setup)
  :config
  (setq general-default-keymaps 'evil-normal-state-map)
  (general-create-definer globalleader :prefix "<SPC>")
  (general-create-definer localleader :prefix ","))

(use-package csv-mode
  :mode "\\.\\(c\\|t\\)sv\\'"
  :config
  (localleader :keymaps 'csv-mode-map
	       "e" '(:ignore t :which-key "edit")
	       "et" 'csv-transpose))
```

**Comment by noctuid** [comment]
When you use `:keymaps`, you are overriding the default keymap (I don't recommend using `general-default-keymaps` or `general-default-states`). You should add `:states 'normal` to the `localleader` call.

**Comment by BrianHicks** [comment]
Hmm, I'm not sure I follow. Now I've got this, and it still does the same thing... how else could I apply this advice in this situation?

```elisp
(use-package general
  :init
  (general-evil-setup)
  :config
  (general-create-definer globalleader
			  :states '(normal visual)
			  :prefix "<SPC>")

  (general-create-definer localleader
			  :states '(normal visual)
			  :prefix ","))

(use-package csv-mode
  :mode "\\.\\(c\\|t\\)sv\\'"
  :config
  (localleader :keymap 'csv-mode-map
               "e" '(:ignore t :which-key "edit")
               "et" 'csv-transpose))
```

I think I missed a little context earlier: I want to be able to define a localleader *per mode*. Is `:keymap` the right way to achieve this? Am I doing something wrong there?

**Comment by noctuid** [comment]
`:keymap` should still be `:keymaps`.

**Comment by BrianHicks** [comment]
Ah! Works great now. Thanks for your help 😁

**Comment by noctuid** [comment]
Alright, glad it's working. Feel free to open another issue if you have any other questions or issues.
