### ISSUE TITLE
using a macro instead of multiple prefix keys

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [noctuid/general.el#94]
Hi,

I read the issues pertaining to `general` accepting multiple prefix keys and your decision not to implement it. I want to bind the prefixex `SPC M ` and `,` to the same bindings as they do in spacemacs. So to do this, I made the following macro. 

    (defmacro add-major-mode-kbd (&rest body)
    `(general-define-key :prefix void-mm-leader-key1 ""  '(:ignore t :wk "Major Mode") ,@body)
    `(general-define-key :prefix void-mm-leader-key2 ,@body))

The third line of the macro works and keys are bound. But the second line using `void-mm-leader-key1` does not work. Nothing is bound. 

For example:
If `void-mm-leader-key1` is `SPC m ` and `void-mm-leader-key2` is `,` and you use my macro like I show below `,W` is bound but not `SPC m W`.

`(add-major-mode-kbd :keymaps 'emacs-lisp-mode-map
                    :states 'normal
                    "W" 'evil-forward-WORD-begin)
`

My mistake is probably minor but I have not been able to find it. Why doesn't the second line of my macro bind anything?

**Comment by noctuid** [comment]
It should be ``` `(progn ...)```; you can't have two quoted expressions like that. Also, a macro isn't necessary. You can just use `apply` for this (e.g. `(apply #'general-define-key :prefix void-mm-leader-key2 rest)`).

**Comment by Luis-Henriquez-Perez** [comment]
I don't understand. If I used apply instead of the macro where I put the `void-mm-leader-key1`? 
In `(apply #'general-define-key :prefix void-mm-leader-key2 rest)`, wouldn't the bindings only be bound with `void-mm-leader-key2`?

**Comment by Luis-Henriquez-Perez** [comment]
Oh I reread the `apply` documentation. Maybe you meant this. 
`(apply #'general-define-key :prefix void-mm-leader-key1 :prefix void-mm-leader-key2 rest)`

**Comment by noctuid** [comment]
You would still have two `apply`s.

**Comment by Luis-Henriquez-Perez** [comment]
Thank you for explaining. That worked out nicely.
