### ISSUE TITLE
Clearify info in readme about evil-like bindings

### ISSUE THREAD

**Issue by ogdenwebb** [noctuid/general.el#96]
[Here](https://github.com/noctuid/general.el#2018-01-20-general-create-vim-definer-and-general-create-dual-vim-definer-have-been-removed) you mark that `general-create-definer is now used instead in general-evil-setup`, but the further all the examples with evil-like bindings still use `general-evil-setup`.

**Comment by dieggsy** [comment]
@ogdenwebb `general-create-definer` is now used instead **_in_**, not instead **_of_**. I think @noctuid was just saying that internally, `general-evil-setup` now uses `general-create-definer` instead of `general-create-vim-definer`. `general-evil-setup` is still valid for use though.

**Comment by ogdenwebb** [comment]
> general-evil-setup is still valid for use though.
I'm not sure, but after the recent changes in general.el my general-imap/nvmap/etc don't work anymore. Maybe this issue is related to my config.

**Comment by dieggsy** [comment]
@ogdenwebb I'm pretty sure? - a quick look at the source code code changes confirm this :) . Also, imap/nmap/etc. are still working for me as far as I can tell.

**Comment by noctuid** [comment]
@dieggsy Is correct; `general-evil-setup` is still valid. What is no longer working for you?

**Comment by noctuid** [comment]
I've updated the message to make it more clear. As for `general-nmap` not working, please make sure that you are also using an up-to-date version of evil. If that's not the reason, there may be some issue with evil. Although all tests are passing for me locally with different emacs versions, the tests aren't currently passing on travis.

**Comment by ogdenwebb** [comment]
Here's the part of my config works before today. 
```emacs-lisp
(use-package general
  :ensure t
  :config
  (setq general-default-keymaps 'evil-normal-state-map)

  (general-evil-setup)

  (general-nvmap
   "g c" 'evil-commentary
   "g y" 'evil-commentary-yank))
```
When I press "g y" for example I can only see the message `g y is undefined` in Emacs minibuffer.
> please make sure that you are also using an up-to-date version of evi
I'm using the most recent version of evil from MELPA, i.e. 1.2.13 version(package version is 20180103.2356).

**Comment by ogdenwebb** [comment]
Well, if I comment the following:
```emacs-lisp 
(setq general-default-keymaps 'evil-normal-state-map)
```
"g c" will work.

**Comment by noctuid** [comment]
Your example is the equivalent of binding with `:keymaps 'normal :states '(normal visual)`. You could change `(setq general-default-states 'normal)` instead, but the `general-default-...` variables will eventually be removed, so I'd recommend using a custom definer.

**Comment by noctuid** [comment]
I've updated the recent changes section to make this more clear (that the vim definers will always set default `:states` now). Let me know if you have any other issues.
