### ISSUE TITLE
Incompatibility with evil version 1.2.13

### ISSUE THREAD

**Issue by Vurp** [noctuid/general.el#98]
Tested on both Windows emacs version 25.2.1 and linux version 25.3.

It seems that the new versions break with evil installed. When I updated it
made several evil related plugins break. 

I disable general and run it after startup instead. Here is the last part of the stacktrace.

```
Debugger entered--Lisp error: (error "Key sequence , u starts with non-prefix key ,")
  define-key((keymap (195 keymap (165 . evil-window-map)) (remap keymap (avy-goto-word-or-subword-1 . evil-avy-goto-word-or-subword-1) (avy-goto-word-1-below . evil-avy-goto-word-1-below) (avy-goto-word-1-above . evil-avy-goto-word-1-above) (avy-goto-word-1 . evil-avy-goto-word-1) (avy-goto-word-0 . evil-avy-goto-word-0) (avy-goto-symbol-1-below . evil-avy-goto-symbol-1-below) (avy-goto-symbol-1-above . evil-avy-goto-symbol-1-above) (avy-goto-symbol-1 . evil-avy-goto-symbol-1) (avy-goto-subword-1 . evil-avy-goto-subword-1) (avy-goto-subword-0 . evil-avy-goto-subword-0) (avy-goto-line-below . evil-avy-goto-line-below) (avy-goto-line-above . evil-avy-goto-line-above) (avy-goto-line . evil-avy-goto-line) (avy-goto-char-timer . evil-avy-goto-char-timer) (avy-goto-char-in-line . evil-avy-goto-char-in-line) (avy-goto-char-2-below . evil-avy-goto-char-2-below) (avy-goto-char-2-above . evil-avy-goto-char-2-above) (avy-goto-char-2 . evil-avy-goto-char-2) (avy-goto-char . evil-avy-goto-char) (ace-jump-word-mode . evil-ace-jump-word-mode) (ace-jump-line-mode . evil-ace-jump-line-mode) (ace-jump-char-mode . evil-ace-jump-char-mode)) (33 . evil-shell-command) (58 . evil-ex) (down-mouse-1 . evil-mouse-drag-region) (21 . evil-scroll-up) (9 . evil-jump-forward) (26 . evil-emacs-state) (down . evil-next-line) (up . evil-previous-line) (right . evil-forward-char) (left . evil-backward-char) (30 . evil-buffer) (22 . evil-visual-block) (86 . evil-visual-line) (118 . evil-visual-char) (122 keymap (72 . evil-scroll-left) (76 . evil-scroll-right) (left . "zh") (104 . evil-scroll-column-left) (right . "zl") (108 . evil-scroll-column-right) (45 . "zb^") (98 . evil-scroll-line-to-bottom) (46 . "zz^") (122 . evil-scroll-line-to-center) (13 . [122 return]) (return . "zt^") (116 . evil-scroll-line-to-top) (43 . evil-scroll-bottom-line-to-top) (94 . evil-scroll-top-line-to-bottom)) (92 . evil-execute-in-emacs-state) (13 . evil-ret) (25 . evil-scroll-line-up) (15 . evil-jump-backward) (6 . evil-scroll-page-down) (5 . evil-scroll-line-down) (4 . evil-scroll-down) (2 . evil-scroll-page-up) (29 . evil-jump-to-tag) (67108918 . evil-switch-to-windows-last-buffer) (23 . evil-window-map) (45 . evil-previous-line-first-non-blank) (95 . evil-next-line-1-first-non-blank) (43 . evil-next-line-first-non-blank) (94 . evil-first-non-blank) (124 . evil-goto-column) (63 . evil-search-backward) (59 . evil-repeat-find-char) (47 . evil-search-forward) (44 . evil-repeat-find-char-reverse) (42 . evil-search-word-forward) (91 keymap (115 . evil-prev-flyspell-error) (123 . evil-previous-open-brace) (40 . evil-previous-open-paren) (93 . evil-backward-section-end) (91 . evil-backward-section-begin)) (93 keymap (115 . evil-next-flyspell-error) (125 . evil-next-close-brace) (41 . evil-next-close-paren) (91 . evil-forward-section-end) (93 . evil-forward-section-begin)) (41 . evil-forward-sentence-begin) (40 . evil-backward-sentence-begin) (39 . evil-goto-mark-line) (96 . evil-goto-mark) (37 . evil-jump-item) (36 . evil-end-of-line) (35 . evil-search-word-backward) (125 . evil-forward-paragraph) (123 . evil-backward-paragraph) ...) ",u" universal-argument)
  evil-define-key*(motion global ",u" universal-argument)
```

Here is my configuration:

```emacs-lisp
(use-package general
  :demand
  :config
  (general-define-key
   :states '(normal emacs motion)
   :prefix ","
   "u" 'universal-argument
   "b" 'ivy-switch-buffer
   "k" 'kill-this-buffer
   "d" 'dired
   "'" 'eshell))
```

**Comment by bluewww** [comment]
I have encountered the very same problem. Here is my code example:
``
(require 'package)

(setq package-enable-at-startup nil)
(setq package-archives '(("org"       . "http://orgmode.org/elpa/")
                         ("gnu"       . "http://elpa.gnu.org/packages/")
                         ("melpa"     . "https://melpa.org/packages/")))
(package-initialize)

(require 'use-package)

(use-package evil :ensure t
  :init
  (setq evil-want-C-u-scroll t)
  :config
  (evil-mode))


(use-package general :ensure t)
(general-define-key
 :states '(motion) ; <-- breaks because of this here
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 "a" 'general-describe-keybindings)
``
with the error

``
 (error "Key sequence SPC a starts with non-prefix key SPC")
``

It seems to break when you use the motion state. Any other state works just fine. Vurp maybe try out your example with just '(motion) too.

**Comment by noctuid** [comment]
You cannot, for example, bind `SPC a` in a keymap where `SPC` is bound in emacs. This is not a bug/incompatability. Please see issue #97 (in short, you need to unbind `SPC` before you can bind `SPC a`). I'm going to add an FAQ entry about this issue in the future, but let me know if I can explain anything else.

**Comment by noctuid** [comment]
`(evil-make-intercept-map general-override-mode-map)` is unnecessary and would only work if you bind directly in `general-override-mode-map` (which evil users likely won't want to do). General.el already makes all evil auxiliary maps for `general-override-mode-map` intercept maps, but evil doesn't currently check whether auxiliary maps are intercept maps (I have a pull request open on evil to change this). Your example keybindings currently will have precedence over evil override maps and the global evil keymaps but won't have the "highest" precedence until my pull request is merged.
