### ISSUE TITLE
key binding not work for dired-mode-map

### ISSUE THREAD

**Issue by showgood** [noctuid/general.el#99]
I tried something like this:
```
(general-define-key
:states '(normal)
:keymaps dired-mode-map
 :prefix "SPC"
 "bB" '(switch-to-buffer :which-key "Switch to buffer")
```

but it doesn't work in dired buffer, I use doom-emacs.

**Comment by noctuid** [comment]
It should be `:keymaps 'dired-mode-map`. Let me know if that does not solve the issue.

**Comment by showgood** [comment]
this:
```
(general-define-key
:states '(normal)
:keymaps 'dired-mode-map
 :prefix "SPC"
 "bB" '(switch-to-buffer :which-key "Switch to buffer")
)
```
worked, thanks!

however it doesn't work if I do it (which supposedly works for all maps):
```
(general-define-key
 :states '(normal visual insert emacs)
 :prefix "SPC"
 :non-normal-prefix "M-m"
  "b" '(:ignore t :which-key "buffers")
  "bb" '(persp-switch-to-buffer :which-key "Switch workspace buffer")
  "bB" '(switch-to-buffer :which-key "Switch to buffer")
  "br" '(rename-buffer :which-key "rename buffer")
)
```
In fact when I press `space` in dired buffer, I can see all the keys listed but
only `bB` works.

if I indeed need to define keys for `dired-mode-map` specifically, then question
is how can I avoid defining all those keys again (there would be quite bit duplication
if I want all the keys I have defined in the global map for dired-mode-map as well).

thanks!

**Comment by noctuid** [comment]
`evil-integration.el` makes `dired-mode-map` an override map, meaning that keys bound in `dired-mode-map` will override keys bound in the global evil keymaps. Auxiliary keymaps have higher precedence than override keymaps. You could do this, for example:
```
(general-override-mode)
(general-define-key
  :states ...
  :keymaps 'override
  :prefix "SPC"
  ...)
```
These will be available globally and in dired mode.

**Comment by showgood** [comment]
works like charm, thanks a lot!
